import { unit } from "./learn-bank-a.mjs";

/** Everyday life units — original Linlin path, all four tracks separately. */

export const UNITS_C = [
  unit(
    "family",
    "A1",
    ["Gia đình", "Family", "家庭", "jiātíng", "ครอบครัว", "khrop-khrua"],
    ["Nói bố mẹ, anh chị em, và người nhà.", "Name parents, siblings, and family.", "说父母、兄弟姐妹和家人。", "", "พูดถึงพ่อแม่ พี่น้อง และครอบครัว", ""],
    [
      ["gia đình", "family", "家庭", "jiātíng", "ครอบครัว", "khrop-khrua"],
      ["bố", "father", "爸爸", "bàba", "พ่อ", "pho"],
      ["mẹ", "mother", "妈妈", "māma", "แม่", "mae"],
      ["bố mẹ", "parents", "父母", "fùmǔ", "พ่อแม่", "pho mae"],
      ["anh trai", "older brother", "哥哥", "gēge", "พี่ชาย", "phi chai"],
      ["chị gái", "older sister", "姐姐", "jiějie", "พี่สาว", "phi sao"],
      ["em", "younger sibling", "弟弟 / 妹妹", "dìdi / mèimei", "น้อง", "nong"],
      ["con", "child", "孩子", "háizi", "ลูก", "luk"],
      ["con trai", "son", "儿子", "érzi", "ลูกชาย", "luk chai"],
      ["con gái", "daughter", "女儿", "nǚ'ér", "ลูกสาว", "luk sao"],
      ["chồng", "husband", "丈夫", "zhàngfu", "สามี", "sa-mi"],
      ["vợ", "wife", "妻子", "qīzi", "ภรรยา", "phan-ra-ya"],
      ["ông", "grandfather", "爷爷", "yéye", "ปู่ / ตา", "pu / ta"],
      ["bà", "grandmother", "奶奶", "nǎinai", "ย่า / ยาย", "ya / yai"],
      ["bé", "baby", "宝宝", "bǎobao", "ทารก", "tha-rok"],
      ["họ hàng", "relatives", "亲戚", "qīnqi", "ญาติ", "yat"],
      ["cùng", "together", "一起", "yìqǐ", "ด้วยกัน", "duai kan"],
      ["yêu", "to love", "爱", "ài", "รัก", "rak"],
      ["nhà mình", "my home", "我家", "wǒ jiā", "บ้านฉัน", "ban chan"],
      ["người nhà", "family member", "家人", "jiārén", "คนในบ้าน", "khon nai ban"],
    ],
    [
      ["Đây là bố mình.", "This is my father.", "这是我爸爸。", "zhè shì wǒ bàba.", "นี่คือพ่อของฉัน", "nee khue pho khong chan"],
      ["Mẹ mình đang ở nhà.", "My mother is at home.", "我妈妈在家。", "wǒ māma zài jiā.", "แม่ฉันอยู่บ้าน", "mae chan yu ban"],
      ["Mình có một chị gái.", "I have an older sister.", "我有一个姐姐。", "wǒ yǒu yí gè jiějie.", "ฉันมีพี่สาวหนึ่งคน", "chan mee phi sao nueng khon"],
      ["Gia đình mình nhỏ.", "My family is small.", "我的家庭很小。", "wǒ de jiātíng hěn xiǎo.", "ครอบครัวฉันเล็ก", "khrop-khrua chan lek"],
      ["Con trai đang ngủ.", "The son is sleeping.", "儿子在睡觉。", "érzi zài shuìjiào.", "ลูกชายกำลังนอน", "luk chai kam-lang non"],
      ["Ông bà sống gần đây.", "Grandparents live nearby.", "爷爷奶奶住在附近。", "yéye nǎinai zhù zài fùjìn.", "ปู่ย่าอยู่ใกล้ๆ", "pu ya yu klai klai"],
      ["Mình yêu người nhà.", "I love my family.", "我爱我的家人。", "wǒ ài wǒ de jiārén.", "ฉันรักคนในบ้าน", "chan rak khon nai ban"],
      ["Hôm nay ăn cùng gia đình.", "Today we eat with family.", "今天和家人一起吃饭。", "jīntiān hé jiārén yìqǐ chīfàn.", "วันนี้กินข้าวกับครอบครัว", "wan-nee kin khao kap khrop-khrua"],
      ["Chồng mình đi làm.", "My husband went to work.", "我丈夫去上班了。", "wǒ zhàngfu qù shàngbān le.", "สามีฉันไปทำงาน", "sa-mi chan pai tham-ngan"],
      ["Bé khóc rồi.", "The baby is crying.", "宝宝哭了。", "bǎobao kū le.", "ทารกร้องแล้ว", "tha-rok rong laeo"],
      ["Em mình còn nhỏ.", "My younger sibling is still little.", "弟弟还小。", "dìdi hái xiǎo.", "น้องยังเล็ก", "nong yang lek"],
      ["Nhà mình có bốn người.", "There are four people in my home.", "我家有四口人。", "wǒ jiā yǒu sì kǒu rén.", "บ้านฉันมีสี่คน", "ban chan mee see khon"],
    ],
  ),
  unit(
    "clothes",
    "A1",
    ["Quần áo", "Clothes", "衣服", "yīfu", "เสื้อผ้า", "suea-pha"],
    ["Nói áo, quần, giày, mặc gì hôm nay.", "Name shirts, trousers, shoes, and what you wear today.", "说衣服、裤子、鞋，以及今天穿什么。", "", "พูดเสื้อ กางเกง รองเท้า และวันนี้ใส่อะไร", ""],
    [
      ["quần áo", "clothes", "衣服", "yīfu", "เสื้อผ้า", "suea-pha"],
      ["áo", "shirt", "衣服 / 上衣", "yīfu", "เสื้อ", "suea"],
      ["quần", "trousers", "裤子", "kùzi", "กางเกง", "kang-keng"],
      ["váy", "dress / skirt", "裙子", "qúnzi", "กระโปรง", "kra-prong"],
      ["giày", "shoes", "鞋", "xié", "รองเท้า", "rong-thao"],
      ["mũ", "hat", "帽子", "màozi", "หมวก", "muak"],
      ["áo khoác", "jacket", "外套", "wàitào", "เสื้อคลุม", "suea-khlum"],
      ["tất", "socks", "袜子", "wàzi", "ถุงเท้า", "thung-thao"],
      ["túi", "bag", "包", "bāo", "กระเป๋า", "kra-pao"],
      ["kính", "glasses", "眼镜", "yǎnjìng", "แว่น", "waen"],
      ["mặc", "to wear", "穿", "chuān", "ใส่", "sai"],
      ["cởi", "to take off", "脱", "tuō", "ถอด", "thot"],
      ["cỡ", "size", "尺码", "chǐmǎ", "ไซซ์", "sai"],
      ["vừa", "it fits", "合身", "héshēn", "พอดี", "pho-dee"],
      ["chật", "tight", "紧", "jǐn", "คับ", "khap"],
      ["rộng", "loose", "宽松", "kuānsōng", "หลวม", "luam"],
      ["màu", "colour", "颜色", "yánsè", "สี", "see"],
      ["mới", "new", "新", "xīn", "ใหม่", "mai"],
      ["cũ", "old", "旧", "jiù", "เก่า", "kao"],
      ["thử", "to try on", "试穿", "shì chuān", "ลองใส่", "long sai"],
    ],
    [
      ["Hôm nay mình mặc áo trắng.", "Today I am wearing a white shirt.", "今天我穿白上衣。", "jīntiān wǒ chuān bái shàngyī.", "วันนี้ฉันใส่เสื้อขาว", "wan-nee chan sai suea khao"],
      ["Giày này chật.", "These shoes are tight.", "这双鞋有点紧。", "zhè shuāng xié yǒudiǎn jǐn.", "รองเท้าคู่นี้คับ", "rong-thao khu nee khap"],
      ["Cho mình thử cỡ lớn.", "I'd like to try a larger size.", "我想试大一号。", "wǒ xiǎng shì dà yí hào.", "ขอลองไซซ์ใหญ่", "kho long sai yai"],
      ["Áo khoác này mới.", "This jacket is new.", "这件外套是新的。", "zhè jiàn wàitào shì xīn de.", "เสื้อคลุมตัวนี้ใหม่", "suea-khlum tua nee mai"],
      ["Cởi giày trước khi vào.", "Take off your shoes before going in.", "进门前请脱鞋。", "jìn mén qián qǐng tuō xié.", "ถอดรองเท้าก่อนเข้า", "thot rong-thao kon khao"],
      ["Váy này vừa.", "This dress fits.", "这条裙子很合身。", "zhè tiáo qúnzi hěn héshēn.", "กระโปรงตัวนี้พอดี", "kra-prong tua nee pho-dee"],
      ["Mình quên túi.", "I forgot my bag.", "我忘了包。", "wǒ wàng le bāo.", "ฉันลืมกระเป๋า", "chan luem kra-pao"],
      ["Màu này đẹp.", "This colour is nice.", "这个颜色很好看。", "zhège yánsè hěn hǎokàn.", "สีนี้สวย", "see nee suai"],
      ["Quần hơi rộng.", "The trousers are a bit loose.", "裤子有点宽松。", "kùzi yǒudiǎn kuānsōng.", "กางเกงหลวมไปนิด", "kang-keng luam pai nit"],
      ["Mình cần tất sạch.", "I need clean socks.", "我需要干净的袜子。", "wǒ xūyào gānjìng de wàzi.", "ฉันต้องการถุงเท้าสะอาด", "chan tong-kan thung-thao sa-at"],
      ["Đeo kính rồi.", "I already have my glasses on.", "我戴眼镜了。", "wǒ dài yǎnjìng le.", "ฉันใส่แว่นแล้ว", "chan sai waen laeo"],
      ["Áo cũ nhưng còn tốt.", "The shirt is old but still fine.", "衣服旧了，但还能穿。", "yīfu jiù le, dàn hái néng chuān.", "เสื้อเก่าแต่ยังใช้ได้", "suea kao tae yang chai dai"],
    ],
  ),
  unit(
    "weather",
    "A1",
    ["Thời tiết", "Weather", "天气", "tiānqì", "อากาศ", "a-kat"],
    ["Nói nắng, mưa, nóng, lạnh, và mang theo gì.", "Say sun, rain, hot, cold, and what to bring.", "说晴、雨、热、冷，以及要带什么。", "", "พูดแดด ฝน ร้อน หนาว และต้องพกอะไร", ""],
    [
      ["thời tiết", "weather", "天气", "tiānqì", "อากาศ", "a-kat"],
      ["nắng", "sunny", "晴", "qíng", "แดดออก", "daet ok"],
      ["mưa", "rain", "雨", "yǔ", "ฝน", "fon"],
      ["mây", "cloudy", "阴", "yīn", "มีเมฆ", "mee mek"],
      ["gió", "wind", "风", "fēng", "ลม", "lom"],
      ["nóng", "hot", "热", "rè", "ร้อน", "ron"],
      ["lạnh", "cold", "冷", "lěng", "หนาว", "nao"],
      ["ấm", "warm", "暖和", "nuǎnhuo", "อุ่น", "un"],
      ["mát", "cool", "凉快", "liángkuai", "เย็นสบาย", "yen sa-bai"],
      ["tuyết", "snow", "雪", "xuě", "หิมะ", "hi-ma"],
      ["bão", "storm", "风暴", "fēngbào", "พายุ", "pha-yu"],
      ["độ", "degree", "度", "dù", "องศา", "ong-sa"],
      ["dự báo", "forecast", "预报", "yùbào", "พยากรณ์", "pha-ya-kon"],
      ["ô", "umbrella", "伞", "sǎn", "ร่ม", "rom"],
      ["mang", "to bring", "带", "dài", "พก", "phok"],
      ["ướt", "wet", "湿", "shī", "เปียก", "piak"],
      ["khô", "dry", "干", "gān", "แห้ง", "haeng"],
      ["hôm nay", "today", "今天", "jīntiān", "วันนี้", "wan-nee"],
      ["tuần này", "this week", "这周", "zhè zhōu", "สัปดาห์นี้", "sap-da nee"],
      ["thay đổi", "to change", "变", "biàn", "เปลี่ยน", "plian"],
    ],
    [
      ["Hôm nay nắng.", "It is sunny today.", "今天是晴天。", "jīntiān shì qíngtiān.", "วันนี้แดดออก", "wan-nee daet ok"],
      ["Mai có mưa.", "It will rain tomorrow.", "明天会下雨。", "míngtiān huì xià yǔ.", "พรุ่งนี้ฝนตก", "phrung-nee fon tok"],
      ["Mang ô theo.", "Bring an umbrella.", "带伞吧。", "dài sǎn ba.", "พกร่มไปด้วย", "phok rom pai duai"],
      ["Trời nóng quá.", "It is too hot.", "天气太热了。", "tiānqì tài rè le.", "อากาศร้อนเกินไป", "a-kat ron goin pai"],
      ["Đêm nay lạnh.", "Tonight will be cold.", "今晚会冷。", "jīn wǎn huì lěng.", "คืนนี้หนาว", "khuen-nee nao"],
      ["Gió to.", "The wind is strong.", "风很大。", "fēng hěn dà.", "ลมแรง", "lom raeng"],
      ["Áo ướt rồi.", "The shirt is wet.", "衣服湿了。", "yīfu shī le.", "เสื้อเปียกแล้ว", "suea piak laeo"],
      ["Dự báo nói mây.", "The forecast says cloudy.", "预报说是阴天。", "yùbào shuō shì yīntiān.", "พยากรณ์บอกว่ามีเมฆ", "pha-ya-kon bok wa mee mek"],
      ["Ba mươi độ.", "Thirty degrees.", "三十度。", "sānshí dù.", "สามสิบองศา", "sam-sip ong-sa"],
      ["Thời tiết hay thay đổi.", "The weather keeps changing.", "天气老是变。", "tiānqì lǎo shì biàn.", "อากาศเปลี่ยนบ่อย", "a-kat plian boi"],
      ["Ngoài trời mát.", "It is cool outside.", "外面很凉快。", "wàimiàn hěn liángkuai.", "ข้างนอกเย็นสบาย", "khang-nok yen sa-bai"],
      ["Tuần này có bão.", "There is a storm this week.", "这周有风暴。", "zhè zhōu yǒu fēngbào.", "สัปดาห์นี้มีพายุ", "sap-da nee mee pha-yu"],
    ],
  ),
  unit(
    "feelings",
    "A1",
    ["Cảm xúc", "Feelings", "心情", "xīnqíng", "ความรู้สึก", "khwam ru-suek"],
    ["Nói vui, mệt, lo, và hỏi người khác thế nào.", "Say happy, tired, worried, and ask how someone feels.", "说开心、累、担心，并问别人怎么样。", "", "พูดดีใจ เหนื่อย กังวล และถามคนอื่นเป็นอย่างไร", ""],
    [
      ["vui", "happy", "开心", "kāixīn", "ดีใจ", "dee-jai"],
      ["buồn", "sad", "难过", "nánguò", "เศร้า", "sao"],
      ["mệt", "tired", "累", "lèi", "เหนื่อย", "nueai"],
      ["giận", "angry", "生气", "shēngqì", "โกรธ", "krot"],
      ["lo", "worried", "担心", "dānxīn", "กังวล", "kang-won"],
      ["sợ", "afraid", "害怕", "hàipà", "กลัว", "klua"],
      ["bình tĩnh", "calm", "冷静", "lěngjìng", "ใจเย็น", "jai-yen"],
      ["cô đơn", "lonely", "孤单", "gūdān", "เหงา", "ngao"],
      ["hào hứng", "excited", "兴奋", "xīngfèn", "ตื่นเต้น", "tuen-ten"],
      ["chán", "bored", "无聊", "wúliáo", "เบื่อ", "buea"],
      ["ngạc nhiên", "surprised", "惊讶", "jīngyà", "ประหลาดใจ", "pra-lat jai"],
      ["xấu hổ", "embarrassed", "不好意思", "bù hǎoyìsi", "อาย", "ai"],
      ["ổn", "okay", "还好", "hái hǎo", "โอเค", "o-khe"],
      ["không khỏe", "unwell", "不舒服", "bù shūfu", "ไม่สบาย", "mai sa-bai"],
      ["thích", "to like", "喜欢", "xǐhuan", "ชอบ", "chop"],
      ["ghét", "to hate", "讨厌", "tǎoyàn", "ไม่ชอบ", "mai chop"],
      ["cảm thấy", "to feel", "觉得", "juéde", "รู้สึก", "ru-suek"],
      ["hôm nay", "today", "今天", "jīntiān", "วันนี้", "wan-nee"],
      ["vì", "because", "因为", "yīnwèi", "เพราะ", "phro"],
      ["hỏi thăm", "to check in", "问候", "wènhòu", "ทักถาม", "thak-tham"],
    ],
    [
      ["Hôm nay mình vui.", "I am happy today.", "今天我很开心。", "jīntiān wǒ hěn kāixīn.", "วันนี้ฉันดีใจ", "wan-nee chan dee-jai"],
      ["Mình mệt quá.", "I am so tired.", "我太累了。", "wǒ tài lèi le.", "ฉันเหนื่อยมาก", "chan nueai mak"],
      ["Bạn ổn không?", "Are you okay?", "你还好吗？", "nǐ hái hǎo ma?", "คุณโอเคไหม", "khun o-khe mai"],
      ["Mình hơi lo.", "I am a bit worried.", "我有点担心。", "wǒ yǒudiǎn dānxīn.", "ฉันกังวลนิดหน่อย", "chan kang-won nit-noi"],
      ["Đừng sợ.", "Don't be afraid.", "别害怕。", "bié hàipà.", "อย่ากลัว", "ya klua"],
      ["Mình cảm thấy chán.", "I feel bored.", "我觉得无聊。", "wǒ juéde wúliáo.", "ฉันรู้สึกเบื่อ", "chan ru-suek buea"],
      ["Vì trời mưa, mình buồn.", "I am sad because it is raining.", "因为下雨，我有点难过。", "yīnwèi xià yǔ, wǒ yǒudiǎn nánguò.", "เพราะฝนตก ฉันเลยเศร้า", "phro fon tok chan loei sao"],
      ["Mình không khỏe.", "I feel unwell.", "我不太舒服。", "wǒ bú tài shūfu.", "ฉันไม่สบาย", "chan mai sa-bai"],
      ["Bình tĩnh nào.", "Stay calm.", "冷静一点。", "lěngjìng yìdiǎn.", "ใจเย็นๆ", "jai-yen yen"],
      ["Mình ngạc nhiên.", "I am surprised.", "我很惊讶。", "wǒ hěn jīngyà.", "ฉันประหลาดใจ", "chan pra-lat jai"],
      ["Xin lỗi, mình xấu hổ.", "Sorry, I am embarrassed.", "不好意思。", "bù hǎoyìsi.", "ขอโทษ ฉันอาย", "kho-thot chan ai"],
      ["Mình thích hôm nay.", "I like today.", "我喜欢今天。", "wǒ xǐhuan jīntiān.", "ฉันชอบวันนี้", "chan chop wan-nee"],
    ],
  ),
  unit(
    "colors",
    "A1",
    ["Màu sắc", "Colours", "颜色", "yánsè", "สี", "see"],
    ["Nói màu đồ, hỏi màu nào, chọn màu mình thích.", "Name colours, ask which colour, pick one you like.", "说颜色、问哪个颜色、选自己喜欢的。", "", "พูดสี ถามสีไหน เลือกสีที่ชอบ", ""],
    [
      ["màu", "colour", "颜色", "yánsè", "สี", "see"],
      ["đỏ", "red", "红", "hóng", "แดง", "daeng"],
      ["xanh dương", "blue", "蓝", "lán", "น้ำเงิน", "nam-ngoen"],
      ["xanh lá", "green", "绿", "lǜ", "เขียว", "khiao"],
      ["vàng", "yellow", "黄", "huáng", "เหลือง", "lueang"],
      ["đen", "black", "黑", "hēi", "ดำ", "dam"],
      ["trắng", "white", "白", "bái", "ขาว", "khao"],
      ["hồng", "pink", "粉", "fěn", "ชมพู", "chom-phu"],
      ["cam", "orange", "橙", "chéng", "ส้ม", "som"],
      ["nâu", "brown", "棕", "zōng", "น้ำตาล", "nam-tan"],
      ["xám", "grey", "灰", "huī", "เทา", "thao"],
      ["tím", "purple", "紫", "zǐ", "ม่วง", "muang"],
      ["sáng", "light (colour)", "浅", "qiǎn", "อ่อน", "on"],
      ["đậm", "dark", "深", "shēn", "เข้ม", "khem"],
      ["đẹp", "pretty", "好看", "hǎokàn", "สวย", "suai"],
      ["xấu", "ugly", "难看", "nánkàn", "ไม่สวย", "mai suai"],
      ["này", "this", "这个", "zhège", "อันนี้", "an nee"],
      ["kia", "that", "那个", "nàge", "อันนั้น", "an nan"],
      ["thích", "to like", "喜欢", "xǐhuan", "ชอบ", "chop"],
      ["chọn", "to choose", "选", "xuǎn", "เลือก", "lueak"],
    ],
    [
      ["Mình thích màu xanh.", "I like blue.", "我喜欢蓝色。", "wǒ xǐhuan lán sè.", "ฉันชอบสีน้ำเงิน", "chan chop see nam-ngoen"],
      ["Áo này màu đỏ.", "This shirt is red.", "这件衣服是红色的。", "zhè jiàn yīfu shì hóngsè de.", "เสื้อตัวนี้สีแดง", "suea tua nee see daeng"],
      ["Cho mình cái trắng.", "The white one, please.", "请给我白色的。", "qǐng gěi wǒ báisè de.", "ขออันสีขาว", "kho an see khao"],
      ["Màu đậm hơn được không?", "Do you have a darker colour?", "有深一点的吗？", "yǒu shēn yìdiǎn de ma?", "มีสีเข้มกว่าไหม", "mee see khem kwa mai"],
      ["Cái kia vàng.", "That one is yellow.", "那个是黄色的。", "nàge shì huángsè de.", "อันนั้นสีเหลือง", "an nan see lueang"],
      ["Hồng quá sáng.", "The pink is too light.", "粉色太浅了。", "fěnsè tài qiǎn le.", "สีชมพูอ่อนไป", "see chom-phu on pai"],
      ["Đen cũng được.", "Black is fine too.", "黑色也可以。", "hēisè yě kěyǐ.", "สีดำก็ได้", "see dam ko dai"],
      ["Màu này đẹp.", "This colour is pretty.", "这个颜色很好看。", "zhège yánsè hěn hǎokàn.", "สีนี้สวย", "see nee suai"],
      ["Mình chọn xanh lá.", "I will choose green.", "我选绿色。", "wǒ xuǎn lǜsè.", "ฉันเลือกสีเขียว", "chan lueak see khiao"],
      ["Tím hay nâu?", "Purple or brown?", "紫色还是棕色？", "zǐsè háishì zōngsè?", "ม่วงหรือน้ำตาล", "muang rue nam-tan"],
      ["Xám cũng ổn.", "Grey is okay too.", "灰色也还行。", "huīsè yě hái xíng.", "สีเทาก็โอเค", "see thao ko o-khe"],
      ["Không thích cam.", "I don't like orange.", "我不喜欢橙色。", "wǒ bù xǐhuan chéngsè.", "ฉันไม่ชอบสีส้ม", "chan mai chop see som"],
    ],
  ),
  unit(
    "daily",
    "A2",
    ["Ngày thường", "Daily routine", "日常生活", "rìcháng shēnghuó", "ชีวิตประจำวัน", "chee-wit pra-jam wan"],
    ["Nói dậy, ăn, đi làm, về nhà, ngủ.", "Talk about waking, eating, going out, coming home, sleeping.", "说起床、吃饭、出门、回家、睡觉。", "", "พูดเรื่องตื่น กิน ออกไป กลับบ้าน นอน", ""],
    [
      ["dậy", "to get up", "起床", "qǐchuáng", "ตื่น", "tuen"],
      ["đánh răng", "to brush teeth", "刷牙", "shuā yá", "แปรงฟัน", "praeng fan"],
      ["tắm", "to shower", "洗澡", "xǐzǎo", "อาบน้ำ", "ap-nam"],
      ["ăn sáng", "breakfast", "早饭", "zǎofàn", "อาหารเช้า", "a-han chao"],
      ["đi làm", "to go to work", "上班", "shàngbān", "ไปทำงาน", "pai tham-ngan"],
      ["đi học", "to go to school", "上学", "shàngxué", "ไปเรียน", "pai rian"],
      ["ăn trưa", "lunch", "午饭", "wǔfàn", "อาหารกลางวัน", "a-han klang-wan"],
      ["về nhà", "to go home", "回家", "huí jiā", "กลับบ้าน", "klap ban"],
      ["ăn tối", "dinner", "晚饭", "wǎnfàn", "อาหารเย็น", "a-han yen"],
      ["nấu", "to cook", "做饭", "zuò fàn", "ทำอาหาร", "tham a-han"],
      ["rửa chén", "to wash dishes", "洗碗", "xǐ wǎn", "ล้างจาน", "lang jan"],
      ["xem", "to watch", "看", "kàn", "ดู", "du"],
      ["ngủ", "to sleep", "睡觉", "shuìjiào", "นอน", "non"],
      ["thói quen", "habit", "习惯", "xíguàn", "นิสัย", "ni-sai"],
      ["mỗi ngày", "every day", "每天", "měi tiān", "ทุกวัน", "thuk wan"],
      ["trước", "before", "之前", "zhīqián", "ก่อน", "kon"],
      ["sau", "after", "之后", "zhīhòu", "หลัง", "lang"],
      ["bận", "busy", "忙", "máng", "ยุ่ง", "yung"],
      ["rảnh", "free", "有空", "yǒu kòng", "ว่าง", "wang"],
      ["nghỉ", "to rest", "休息", "xiūxi", "พัก", "phak"],
    ],
    [
      ["Mình dậy lúc bảy giờ.", "I get up at seven.", "我七点起床。", "wǒ qī diǎn qǐchuáng.", "ฉันตื่นเจ็ดโมง", "chan tuen jet mong"],
      ["Sau đó mình đánh răng.", "Then I brush my teeth.", "然后我刷牙。", "ránhòu wǒ shuā yá.", "แล้วฉันแปรงฟัน", "laeo chan praeng fan"],
      ["Mình ăn sáng ở nhà.", "I have breakfast at home.", "我在家吃早饭。", "wǒ zài jiā chī zǎofàn.", "ฉันกินข้าวเช้าที่บ้าน", "chan kin khao chao thee ban"],
      ["Mỗi ngày mình đi làm.", "I go to work every day.", "我每天上班。", "wǒ měi tiān shàngbān.", "ฉันไปทำงานทุกวัน", "chan pai tham-ngan thuk wan"],
      ["Ăn trưa nhanh thôi.", "Lunch is quick.", "午饭很快。", "wǔfàn hěn kuài.", "ข้าวกลางวันเร็วๆ", "khao klang-wan reo reo"],
      ["Mình về nhà lúc sáu giờ.", "I go home at six.", "我六点回家。", "wǒ liù diǎn huí jiā.", "ฉันกลับบ้านหกโมง", "chan klap ban hok mong"],
      ["Tối mình nấu ăn.", "In the evening I cook.", "晚上我做饭。", "wǎnshang wǒ zuò fàn.", "เย็นฉันทำอาหาร", "yen chan tham a-han"],
      ["Rửa chén rồi mới xem.", "I wash the dishes, then watch something.", "洗碗后再看。", "xǐ wǎn hòu zài kàn.", "ล้างจานแล้วค่อยดู", "lang jan laeo khoi du"],
      ["Mình ngủ sớm.", "I sleep early.", "我睡得早。", "wǒ shuì de zǎo.", "ฉันนอนเร็ว", "chan non reo"],
      ["Hôm nay hơi bận.", "Today is a bit busy.", "今天有点忙。", "jīntiān yǒudiǎn máng.", "วันนี้ยุ่งนิดหน่อย", "wan-nee yung nit-noi"],
      ["Cuối tuần mình rảnh.", "I am free on the weekend.", "周末我有空。", "zhōumò wǒ yǒu kòng.", "สุดสัปดาห์ฉันว่าง", "sut sap-da chan wang"],
      ["Trước khi ngủ, mình học 15 phút.", "Before sleep, I study for 15 minutes.", "睡觉前我学习十五分钟。", "shuìjiào qián wǒ xuéxí shíwǔ fēnzhōng.", "ก่อนนอนฉันเรียนสิบห้านาที", "kon non chan rian sip-ha na-thee"],
    ],
  ),
  unit(
    "shopping",
    "A2",
    ["Mua sắm", "Shopping", "购物", "gòuwù", "การซื้อของ", "kan sue khong"],
    ["Hỏi còn hàng, đổi size, trả hàng, xin hóa đơn.", "Ask for stock, change size, return an item, ask for a receipt.", "问有没有货、换尺码、退货、要发票。", "", "ถามว่ามีของไหม เปลี่ยนไซซ์ คืนของ ขอใบเสร็จ", ""],
    [
      ["cửa hàng", "shop", "商店", "shāngdiàn", "ร้าน", "ran"],
      ["mua", "to buy", "买", "mǎi", "ซื้อ", "sue"],
      ["bán", "to sell", "卖", "mài", "ขาย", "khai"],
      ["thử", "to try on", "试", "shì", "ลอง", "long"],
      ["đổi", "to exchange", "换", "huàn", "เปลี่ยน", "plian"],
      ["trả lại", "to return", "退", "tuì", "คืน", "khuen"],
      ["hóa đơn", "receipt", "发票", "fāpiào", "ใบเสร็จ", "bai-set"],
      ["giảm giá", "sale", "打折", "dǎzhé", "ลดราคา", "lot ra-kha"],
      ["hàng", "goods", "货", "huò", "สินค้า", "sin-kha"],
      ["còn", "in stock", "有货", "yǒu huò", "มีของ", "mee khong"],
      ["hết", "out of stock", "没货", "méi huò", "หมด", "mot"],
      ["cỡ", "size", "尺码", "chǐmǎ", "ไซซ์", "sai"],
      ["thẻ", "card", "卡", "kǎ", "บัตร", "bat"],
      ["tiền mặt", "cash", "现金", "xiànjīn", "เงินสด", "ngoen sot"],
      ["đắt", "expensive", "贵", "guì", "แพง", "phaeng"],
      ["rẻ", "cheap", "便宜", "piányi", "ถูก", "thuk"],
      ["thích", "to like", "喜欢", "xǐhuan", "ชอบ", "chop"],
      ["cái này", "this one", "这个", "zhège", "อันนี้", "an nee"],
      ["cái kia", "that one", "那个", "nàge", "อันนั้น", "an nan"],
      ["túi", "shopping bag", "袋子", "dàizi", "ถุง", "thung"],
    ],
    [
      ["Còn cỡ này không?", "Do you have this size?", "有这个尺码吗？", "yǒu zhège chǐmǎ ma?", "มีไซซ์นี้ไหม", "mee sai nee mai"],
      ["Mình muốn thử cái này.", "I want to try this on.", "我想试这个。", "wǒ xiǎng shì zhège.", "ฉันอยากลองอันนี้", "chan yak long an nee"],
      ["Đổi sang cỡ nhỏ hơn.", "Please change to a smaller size.", "请换成小一号。", "qǐng huàn chéng xiǎo yí hào.", "ขอเปลี่ยนเป็นไซซ์เล็กกว่า", "kho plian pen sai lek kwa"],
      ["Có thể trả lại không?", "Can I return this?", "可以退吗？", "kěyǐ tuì ma?", "คืนได้ไหม", "khuen dai mai"],
      ["Cho mình hóa đơn.", "The receipt, please.", "请给我发票。", "qǐng gěi wǒ fāpiào.", "ขอใบเสร็จ", "kho bai-set"],
      ["Hôm nay có giảm giá.", "There is a sale today.", "今天打折。", "jīntiān dǎzhé.", "วันนี้ลดราคา", "wan-nee lot ra-kha"],
      ["Cái kia hết rồi.", "That one is out of stock.", "那个没货了。", "nàge méi huò le.", "อันนั้นหมดแล้ว", "an nan mot laeo"],
      ["Mình trả bằng thẻ.", "I will pay by card.", "我用卡付。", "wǒ yòng kǎ fù.", "ฉันจ่ายด้วยบัตร", "chan jai duai bat"],
      ["Hơi đắt.", "A bit expensive.", "有点贵。", "yǒudiǎn guì.", "แพงไปนิด", "phaeng pai nit"],
      ["Mình lấy cái này.", "I'll take this one.", "我要这个。", "wǒ yào zhège.", "ฉันเอาอันนี้", "chan ao an nee"],
      ["Cho mình một túi.", "A bag, please.", "请给我一个袋子。", "qǐng gěi wǒ yí gè dàizi.", "ขอถุงหนึ่งใบ", "kho thung nueng bai"],
      ["Mình không thích cái này.", "I don't like this one.", "我不喜欢这个。", "wǒ bù xǐhuan zhège.", "ฉันไม่ชอบอันนี้", "chan mai chop an nee"],
    ],
  ),
  unit(
    "restaurant",
    "A2",
    ["Nhà hàng", "Restaurant", "餐馆", "cānguǎn", "ร้านอาหาร", "ran a-han"],
    ["Đặt bàn, gọi món, xin không cay, xin hóa đơn.", "Book a table, order, ask for mild spice, ask for the bill.", "订座、点菜、不要辣、买单。", "", "จองโต๊ะ สั่งอาหาร ขอไม่เผ็ด ขอคิดเงิน", ""],
    [
      ["nhà hàng", "restaurant", "餐馆", "cānguǎn", "ร้านอาหาร", "ran a-han"],
      ["đặt bàn", "to book a table", "订座", "dìng zuò", "จองโต๊ะ", "jong to"],
      ["thực đơn", "menu", "菜单", "càidān", "เมนู", "me-nu"],
      ["món", "dish", "菜", "cài", "อาหาร", "a-han"],
      ["khai vị", "starter", "前菜", "qiáncài", "ของทานเล่น", "khong than len"],
      ["món chính", "main course", "主菜", "zhǔcài", "จานหลัก", "jan lak"],
      ["tráng miệng", "dessert", "甜点", "tiándiǎn", "ของหวาน", "khong wan"],
      ["nước sốt", "sauce", "酱", "jiàng", "น้ำซอส", "nam sot"],
      ["cay", "spicy", "辣", "là", "เผ็ด", "phet"],
      ["nhạt", "bland", "淡", "dàn", "จืด", "juet"],
      ["chia", "to share", "分享", "fēnxiǎng", "แบ่ง", "baeng"],
      ["chờ", "to wait", "等", "děng", "รอ", "ro"],
      ["chưa ra", "not served yet", "还没上", "hái méi shàng", "ยังไม่มา", "yang mai ma"],
      ["ngon", "tasty", "好吃", "hǎochī", "อร่อย", "a-roi"],
      ["hóa đơn", "the bill", "账单", "zhàngdān", "บิล", "bin"],
      ["chia tiền", "to split the bill", "AA", "AA", "หารบิล", "han bin"],
      ["đặt", "to book", "预订", "yùdìng", "จอง", "jong"],
      ["chỗ", "place / table", "位子", "wèizi", "ที่นั่ง", "thee-nang"],
      ["ồn", "noisy", "吵", "chǎo", "เสียงดัง", "siang dang"],
      ["yên", "quiet", "安静", "ānjìng", "เงียบ", "ngiap"],
    ],
    [
      ["Mình muốn đặt bàn cho ba người.", "I'd like a table for three.", "我想订三人桌。", "wǒ xiǎng dìng sān rén zhuō.", "ฉันอยากจองโต๊ะสามคน", "chan yak jong to sam khon"],
      ["Cho mình xem thực đơn.", "The menu, please.", "请给我菜单。", "qǐng gěi wǒ càidān.", "ขอเมนูหน่อย", "kho me-nu noi"],
      ["Không cay, làm ơn.", "Not spicy, please.", "请不要辣。", "qǐng bú yào là.", "ไม่เผ็ดนะ", "mai phet na"],
      ["Món này chia được không?", "Can we share this dish?", "这道菜可以分享吗？", "zhè dào cài kěyǐ fēnxiǎng ma?", "จานนี้แบ่งได้ไหม", "jan nee baeng dai mai"],
      ["Mình chờ khá lâu.", "I have waited quite long.", "我等很久了。", "wǒ děng hěn jiǔ le.", "ฉันรอนานแล้ว", "chan ro nan laeo"],
      ["Món chính chưa ra.", "The main course has not come yet.", "主菜还没上。", "zhǔcài hái méi shàng.", "จานหลักยังไม่มา", "jan lak yang mai ma"],
      ["Ngon lắm.", "It is very tasty.", "很好吃。", "hěn hǎochī.", "อร่อยมาก", "a-roi mak"],
      ["Cho mình tráng miệng.", "Dessert, please.", "请给我甜点。", "qǐng gěi wǒ tiándiǎn.", "ขอของหวาน", "kho khong wan"],
      ["Thanh toán giúp mình.", "The bill, please.", "买单。", "mǎidān.", "คิดเงินด้วย", "khit-ngoen duai"],
      ["Mình muốn chia tiền.", "We would like to split the bill.", "我们AA吧。", "wǒmen AA ba.", "เราหารบิลนะ", "rao han bin na"],
      ["Chỗ này hơi ồn.", "This place is a bit noisy.", "这里有点吵。", "zhèlǐ yǒudiǎn chǎo.", "ที่นี่เสียงดังไปนิด", "thee nee siang dang pai nit"],
      ["Có chỗ yên hơn không?", "Is there a quieter table?", "有安静一点的位子吗？", "yǒu ānjìng yìdiǎn de wèizi ma?", "มีที่นั่งเงียบกว่าไหม", "mee thee-nang ngiap kwa mai"],
    ],
  ),
  unit(
    "hotel",
    "A2",
    ["Khách sạn", "Hotel", "酒店", "jiǔdiàn", "โรงแรม", "rohng-raem"],
    ["Nhận phòng, xin thêm khăn, hỏi wifi, trả phòng.", "Check in, ask for towels, ask for wifi, check out.", "入住、要毛巾、问无线网、退房。", "", "เช็กอิน ขอผ้าขนหนู ถามไวไฟ เช็กเอาต์", ""],
    [
      ["khách sạn", "hotel", "酒店", "jiǔdiàn", "โรงแรม", "rohng-raem"],
      ["phòng", "room", "房间", "fángjiān", "ห้อง", "hong"],
      ["đặt phòng", "to book a room", "订房", "dìng fáng", "จองห้อง", "jong hong"],
      ["nhận phòng", "check-in", "入住", "rùzhù", "เช็กอิน", "chek-in"],
      ["trả phòng", "check-out", "退房", "tuì fáng", "เช็กเอาต์", "chek-ao"],
      ["chìa khóa", "key card", "房卡", "fáng kǎ", "คีย์การ์ด", "khi-kat"],
      ["thang máy", "lift", "电梯", "diàntī", "ลิฟต์", "lif"],
      ["tầng", "floor", "楼", "lóu", "ชั้น", "chan"],
      ["khăn", "towel", "毛巾", "máojīn", "ผ้าขนหนู", "pha khon-nu"],
      ["gối", "pillow", "枕头", "zhěntou", "หมอน", "mon"],
      ["wifi", "wifi", "无线网", "wúxiàn wǎng", "ไวไฟ", "wai-fai"],
      ["mật khẩu", "password", "密码", "mìmǎ", "รหัส", "rat"],
      ["ồn", "noisy", "吵", "chǎo", "เสียงดัง", "siang dang"],
      ["sạch", "clean", "干净", "gānjìng", "สะอาด", "sa-at"],
      ["hỏng", "broken", "坏了", "huài le", "พัง", "phang"],
      ["sửa", "to fix", "修", "xiū", "ซ่อม", "som"],
      ["sáng sớm", "early morning", "早上", "zǎoshang", "เช้ามืด", "chao muet"],
      ["hành lý", "luggage", "行李", "xíngli", "กระเป๋าเดินทาง", "kra-pao doen-thang"],
      ["giữ", "to keep", "寄存", "jìcún", "ฝาก", "fak"],
      ["lễ tân", "front desk", "前台", "qiántái", "เคาน์เตอร์", "khao-toe"],
    ],
    [
      ["Mình đã đặt phòng.", "I have a reservation.", "我订了房间。", "wǒ dìng le fángjiān.", "ฉันจองห้องแล้ว", "chan jong hong laeo"],
      ["Nhận phòng giúp mình.", "Check-in, please.", "请帮我办理入住。", "qǐng bāng wǒ bànlǐ rùzhù.", "ขอเช็กอิน", "kho chek-in"],
      ["Phòng ở tầng mấy?", "Which floor is the room on?", "房间在几楼？", "fángjiān zài jǐ lóu?", "ห้องอยู่ชั้นไหน", "hong yu chan nai"],
      ["Wifi mật khẩu là gì?", "What is the wifi password?", "无线网密码是什么？", "wúxiàn wǎng mìmǎ shì shénme?", "รหัสไวไฟคืออะไร", "rat wai-fai khue a-rai"],
      ["Cho mình thêm khăn.", "More towels, please.", "请再给我毛巾。", "qǐng zài gěi wǒ máojīn.", "ขอผ้าขนหนูเพิ่ม", "kho pha khon-nu phoem"],
      ["Điều hòa hỏng.", "The air-con is broken.", "空调坏了。", "kōngtiáo huài le.", "แอร์พัง", "ae phang"],
      ["Phòng hơi ồn.", "The room is a bit noisy.", "房间有点吵。", "fángjiān yǒudiǎn chǎo.", "ห้องเสียงดังไปนิด", "hong siang dang pai nit"],
      ["Phòng sạch, cảm ơn.", "The room is clean, thank you.", "房间很干净，谢谢。", "fángjiān hěn gānjìng, xièxie.", "ห้องสะอาด ขอบคุณ", "hong sa-at khop-khun"],
      ["Mai mình trả phòng sớm.", "I will check out early tomorrow.", "明天我早退房。", "míngtiān wǒ zǎo tuì fáng.", "พรุ่งนี้ฉันเช็กเอาต์เช้า", "phrung-nee chan chek-ao chao"],
      ["Giữ hành lý giúp mình.", "Could you keep my luggage?", "能帮我寄存行李吗？", "néng bāng wǒ jìcún xíngli ma?", "ฝากกระเป๋าให้หน่อยได้ไหม", "fak kra-pao hai noi dai mai"],
      ["Lễ tân ở đâu?", "Where is the front desk?", "前台在哪里？", "qiántái zài nǎlǐ?", "เคาน์เตอร์อยู่ไหน", "khao-toe yu nai"],
      ["Thang máy bên trái.", "The lift is on the left.", "电梯在左边。", "diàntī zài zuǒbiān.", "ลิฟต์อยู่ทางซ้าย", "lif yu thang sai"],
    ],
  ),
  unit(
    "phone",
    "A2",
    ["Điện thoại", "Phone", "手机", "shǒujī", "โทรศัพท์", "tho-ra-sap"],
    ["Gọi, nhắn, hết pin, hỏi wifi, nói máy hỏng.", "Call, text, low battery, ask for wifi, say the phone is broken.", "打电话、发信息、没电、问无线网、说手机坏了。", "", "โทร ส่งข้อความ แบตหมด ถามไวไฟ บอกว่าเครื่องพัง", ""],
    [
      ["điện thoại", "phone", "手机", "shǒujī", "โทรศัพท์", "tho-ra-sap"],
      ["gọi", "to call", "打电话", "dǎ diànhuà", "โทร", "tho"],
      ["nhắn", "to text", "发信息", "fā xìnxī", "ส่งข้อความ", "song kho-khwam"],
      ["pin", "battery", "电", "diàn", "แบต", "baet"],
      ["sạc", "to charge", "充电", "chōngdiàn", "ชาร์จ", "chat"],
      ["mạng", "signal / data", "信号", "xìnhào", "สัญญาณ", "sanyan"],
      ["wifi", "wifi", "无线网", "wúxiàn wǎng", "ไวไฟ", "wai-fai"],
      ["số", "number", "号码", "hàomǎ", "เบอร์", "boe"],
      ["máy", "device", "机器", "jīqì", "เครื่อง", "khrueang"],
      ["hỏng", "broken", "坏了", "huài le", "พัง", "phang"],
      ["màn hình", "screen", "屏幕", "píngmù", "หน้าจอ", "na-jo"],
      ["âm lượng", "volume", "音量", "yīnliàng", "เสียง", "siang"],
      ["im", "silent", "静音", "jìngyīn", "ปิดเสียง", "pit siang"],
      ["chụp", "to take a photo", "拍照", "pāizhào", "ถ่ายรูป", "thai rup"],
      ["gửi", "to send", "发", "fā", "ส่ง", "song"],
      ["nhận", "to receive", "收到", "shōudào", "ได้รับ", "dai rap"],
      ["không nghe", "no answer", "没接", "méi jiē", "ไม่รับสาย", "mai rap sai"],
      ["gọi lại", "to call back", "回电话", "huí diànhuà", "โทรกลับ", "tho klap"],
      ["mất mạng", "no signal", "没信号", "méi xìnhào", "ไม่มีสัญญาณ", "mai mee sanyan"],
      ["ứng dụng", "app", "应用", "yìngyòng", "แอป", "aep"],
    ],
    [
      ["Pin sắp hết.", "The battery is almost empty.", "快没电了。", "kuài méi diàn le.", "แบตใกล้หมด", "baet klai mot"],
      ["Cho mình sạc được không?", "Could I charge my phone?", "可以充电吗？", "kěyǐ chōngdiàn ma?", "ชาร์จแบตได้ไหม", "chat baet dai mai"],
      ["Mạng yếu quá.", "The signal is too weak.", "信号太差了。", "xìnhào tài chà le.", "สัญญาณอ่อนมาก", "sanyan on mak"],
      ["Wifi ở đây được không?", "Does the wifi work here?", "这里有无线网吗？", "zhèlǐ yǒu wúxiàn wǎng ma?", "ที่นี่มีไวไฟไหม", "thee nee mee wai-fai mai"],
      ["Mình gọi mà không nghe.", "I called but there was no answer.", "我打了，没人接。", "wǒ dǎ le, méi rén jiē.", "ฉันโทรแล้ว ไม่มีคนรับ", "chan tho laeo mai mee khon rap"],
      ["Gọi lại giúp mình.", "Please call me back.", "请给我回电话。", "qǐng gěi wǒ huí diànhuà.", "ช่วยโทรกลับฉันหน่อย", "chuai tho klap chan noi"],
      ["Số mình đổi rồi.", "My number has changed.", "我的号码换了。", "wǒ de hàomǎ huàn le.", "เบอร์ฉันเปลี่ยนแล้ว", "boe chan plian laeo"],
      ["Màn hình hỏng.", "The screen is broken.", "屏幕坏了。", "píngmù huài le.", "หน้าจอพัง", "na-jo phang"],
      ["Để máy ở chế độ im.", "Put the phone on silent.", "手机调成静音。", "shǒujī tiáo chéng jìngyīn.", "ตั้งเครื่องเป็นปิดเสียง", "tang khrueang pen pit siang"],
      ["Mình gửi ảnh rồi.", "I have sent the photo.", "我把照片发了。", "wǒ bǎ zhàopiàn fā le.", "ฉันส่งรูปแล้ว", "chan song rup laeo"],
      ["Bạn nhận chưa?", "Have you received it?", "你收到了吗？", "nǐ shōudào le ma?", "คุณได้รับหรือยัง", "khun dai rap rue yang"],
      ["Ứng dụng không mở được.", "The app will not open.", "应用打不开。", "yìngyòng dǎ bù kāi.", "แอปเปิดไม่ได้", "aep poet mai dai"],
    ],
  ),
];
