import { unit } from "./learn-bank-a.mjs";

export const UNITS_C2 = [
  unit(
    "hobbies",
    "A2",
    ["Sở thích", "Hobbies", "爱好", "àihào", "งานอดิเรก", "ngan o-di-rek"],
    ["Nói mình thích làm gì lúc rảnh.", "Say what you like to do in free time.", "说空闲时喜欢做什么。", "", "พูดว่าว่างๆ ชอบทำอะไร", ""],
    [
      ["sở thích", "hobby", "爱好", "àihào", "งานอดิเรก", "ngan o-di-rek"],
      ["thích", "to like", "喜欢", "xǐhuan", "ชอบ", "chop"],
      ["đọc", "to read", "看书", "kàn shū", "อ่านหนังสือ", "an nang-sue"],
      ["nhạc", "music", "音乐", "yīnyuè", "เพลง", "phleng"],
      ["hát", "to sing", "唱歌", "chàng gē", "ร้องเพลง", "rong phleng"],
      ["phim", "film", "电影", "diànyǐng", "หนัง", "nang"],
      ["vẽ", "to draw", "画画", "huà huà", "วาดรูป", "wat rup"],
      ["nấu", "to cook", "做饭", "zuò fàn", "ทำอาหาร", "tham a-han"],
      ["đi bộ", "to walk", "散步", "sànbù", "เดินเล่น", "doen len"],
      ["chụp ảnh", "to take photos", "拍照", "pāizhào", "ถ่ายรูป", "thai rup"],
      ["game", "games", "游戏", "yóuxì", "เกม", "kem"],
      ["du lịch", "travel", "旅行", "lǚxíng", "เที่ยว", "thiao"],
      ["rảnh", "free time", "空闲", "kòngxián", "เวลาว่าง", "we-la wang"],
      ["thường", "often", "常常", "chángcháng", "บ่อย", "boi"],
      ["hiếm", "rarely", "很少", "hěn shǎo", "นานๆ ครั้ง", "nan nan khrang"],
      ["cùng", "together", "一起", "yìqǐ", "ด้วยกัน", "duai kan"],
      ["một mình", "alone", "一个人", "yí gè rén", "คนเดียว", "khon diao"],
      ["thử", "to try", "试试", "shìshi", "ลอง", "long"],
      ["giỏi", "good at", "擅长", "shàncháng", "เก่ง", "keng"],
      ["mới học", "just started", "刚学", "gāng xué", "เพิ่งเริ่ม", "phoeng roem"],
    ],
    [
      ["Lúc rảnh mình đọc sách.", "In free time I read.", "空闲时我看书。", "kòngxián shí wǒ kàn shū.", "เวลาว่างฉันอ่านหนังสือ", "we-la wang chan an nang-sue"],
      ["Mình thích nhạc nhẹ.", "I like quiet music.", "我喜欢轻的音乐。", "wǒ xǐhuan qīng de yīnyuè.", "ฉันชอบเพลงเบา", "chan chop phleng bao"],
      ["Tối nay xem phim được không?", "Shall we watch a film tonight?", "今晚看电影好吗？", "jīn wǎn kàn diànyǐng hǎo ma?", "คืนนี้ดูหนังได้ไหม", "khuen-nee du nang dai mai"],
      ["Mình không giỏi hát.", "I am not good at singing.", "我不擅长唱歌。", "wǒ bù shàncháng chàng gē.", "ฉันร้องเพลงไม่เก่ง", "chan rong phleng mai keng"],
      ["Mình mới học nấu.", "I have just started cooking.", "我刚学做饭。", "wǒ gāng xué zuò fàn.", "ฉันเพิ่งเริ่มทำอาหาร", "chan phoeng roem tham a-han"],
      ["Cuối tuần mình đi bộ.", "At the weekend I go for a walk.", "周末我去散步。", "zhōumò wǒ qù sànbù.", "สุดสัปดาห์ฉันไปเดินเล่น", "sut sap-da chan pai doen len"],
      ["Mình thích chụp ảnh một mình.", "I like taking photos alone.", "我喜欢一个人拍照。", "wǒ xǐhuan yí gè rén pāizhào.", "ฉันชอบถ่ายรูปคนเดียว", "chan chop thai rup khon diao"],
      ["Game thì mình hiếm chơi.", "I rarely play games.", "游戏我很少玩。", "yóuxì wǒ hěn shǎo wán.", "เกมฉันเล่นนานๆ ครั้ง", "kem chan len nan nan khrang"],
      ["Mình thường nghe nhạc khi học.", "I often listen to music when I study.", "学习时我常常听音乐。", "xuéxí shí wǒ chángcháng tīng yīnyuè.", "ตอนเรียนฉันมักฟังเพลง", "ton rian chan mak fang phleng"],
      ["Thử vẽ với mình.", "Try drawing with me.", "和我一起画画吧。", "hé wǒ yìqǐ huà huà ba.", "ลองวาดกับฉันสิ", "long wat kap chan si"],
      ["Mình thích đi du lịch ngắn.", "I like short trips.", "我喜欢短途旅行。", "wǒ xǐhuan duǎn tú lǚxíng.", "ฉันชอบเที่ยวสั้นๆ", "chan chop thiao san san"],
      ["Sở thích này làm mình vui.", "This hobby makes me happy.", "这个爱好让我开心。", "zhège àihào ràng wǒ kāixīn.", "งานอดิเรกนี้ทำให้ฉันดีใจ", "ngan o-di-rek nee tham hai chan dee-jai"],
    ],
  ),
  unit(
    "sports",
    "A2",
    ["Thể thao", "Sports", "运动", "yùndòng", "กีฬา", "ki-la"],
    ["Nói môn mình chơi, tập, và hỏi người khác.", "Name a sport, say you train, and ask what others play.", "说自己打球、锻炼，并问别人。", "", "พูดกีฬาที่เล่น ออกกำลัง และถามคนอื่น", ""],
    [
      ["thể thao", "sport", "运动", "yùndòng", "กีฬา", "ki-la"],
      ["tập", "to train", "锻炼", "duànliàn", "ออกกำลัง", "ok kam-lang"],
      ["chạy", "to run", "跑步", "pǎobù", "วิ่ง", "wing"],
      ["bơi", "to swim", "游泳", "yóuyǒng", "ว่ายน้ำ", "wai nam"],
      ["bóng đá", "football", "足球", "zúqiú", "ฟุตบอล", "fut-bon"],
      ["bóng rổ", "basketball", "篮球", "lánqiú", "บาสเก็ตบอล", "bat-ket-bon"],
      ["cầu lông", "badminton", "羽毛球", "yǔmáoqiú", "แบดมินตัน", "baet-min-tan"],
      ["yoga", "yoga", "瑜伽", "yújiā", "โยคะ", "yo-kha"],
      ["xe đạp", "bike", "自行车", "zìxíngchē", "จักรยาน", "jak-kra-yan"],
      ["đội", "team", "队", "duì", "ทีม", "thim"],
      ["thắng", "to win", "赢", "yíng", "ชนะ", "cha-na"],
      ["thua", "to lose", "输", "shū", "แพ้", "phae"],
      ["trận", "match", "比赛", "bǐsài", "แมตช์", "maet"],
      ["sân", "court / field", "场地", "chǎngdì", "สนาม", "sa-nam"],
      ["mệt", "tired", "累", "lèi", "เหนื่อย", "nueai"],
      ["khỏe", "fit", "健康", "jiànkāng", "แข็งแรง", "khaeng-raeng"],
      ["chậm", "slowly", "慢慢", "mànmàn", "ช้าๆ", "cha cha"],
      ["nhanh", "fast", "快", "kuài", "เร็ว", "reo"],
      ["cùng chơi", "to play together", "一起玩", "yìqǐ wán", "เล่นด้วยกัน", "len duai kan"],
      ["nghỉ một nhịp", "to take a break", "歇一下", "xiē yíxià", "พักแป๊บ", "phak paep"],
    ],
    [
      ["Mình tập ba lần một tuần.", "I train three times a week.", "我一周锻炼三次。", "wǒ yì zhōu duànliàn sān cì.", "ฉันออกกำลังสามครั้งต่อสัปดาห์", "chan ok kam-lang sam khrang tor sap-da"],
      ["Sáng mình chạy bộ.", "I run in the morning.", "早上我跑步。", "zǎoshang wǒ pǎobù.", "เช้าฉันวิ่ง", "chao chan wing"],
      ["Bạn chơi bóng đá không?", "Do you play football?", "你踢足球吗？", "nǐ tī zúqiú ma?", "คุณเล่นฟุตบอลไหม", "khun len fut-bon mai"],
      ["Trận này mình thua.", "We lost this match.", "这场比赛我们输了。", "zhè chǎng bǐsài wǒmen shū le.", "แมตช์นี้เราแพ้", "maet nee rao phae"],
      ["Sân ở gần nhà.", "The court is near home.", "场地离家很近。", "chǎngdì lí jiā hěn jìn.", "สนามอยู่ใกล้บ้าน", "sa-nam yu klai ban"],
      ["Chạy chậm thôi.", "Just run slowly.", "慢慢跑就行。", "mànmàn pǎo jiù xíng.", "วิ่งช้าๆ ก็พอ", "wing cha cha ko pho"],
      ["Mình mệt, nghỉ một nhịp.", "I am tired, let's take a break.", "我累了，歇一下。", "wǒ lèi le, xiē yíxià.", "ฉันเหนื่อย พักแป๊บ", "chan nueai phak paep"],
      ["Cuối tuần bơi được không?", "Shall we swim this weekend?", "这周末去游泳好吗？", "zhè zhōumò qù yóuyǒng hǎo ma?", "สุดสัปดาห์ไปว่ายน้ำได้ไหม", "sut sap-da pai wai nam dai mai"],
      ["Mình mới học yoga.", "I have just started yoga.", "我刚学瑜伽。", "wǒ gāng xué yújiā.", "ฉันเพิ่งเริ่มโยคะ", "chan phoeng roem yo-kha"],
      ["Đội mình thắng.", "Our team won.", "我们队赢了。", "wǒmen duì yíng le.", "ทีมเราชนะ", "thim rao cha-na"],
      ["Đi xe đạp cho khỏe.", "Cycling keeps you fit.", "骑自行车对健康好。", "qí zìxíngchē duì jiànkāng hǎo.", "ขี่จักรยานทำให้แข็งแรง", "khi jak-kra-yan tham hai khaeng-raeng"],
      ["Cùng chơi cầu lông.", "Let's play badminton together.", "一起打羽毛球吧。", "yìqǐ dǎ yǔmáoqiú ba.", "มาเล่นแบดด้วยกัน", "ma len baet duai kan"],
    ],
  ),
  unit(
    "money",
    "B1",
    ["Tiền bạc", "Money", "钱", "qián", "เงิน", "ngoen"],
    ["Nói giá, chuyển khoản, đổi tiền, xin hóa đơn.", "Talk about prices, transfers, changing money, asking for a receipt.", "说价格、转账、换钱、要收据。", "", "พูดราคา โอนเงิน แลกเงิน ขอใบเสร็จ", ""],
    [
      ["tiền", "money", "钱", "qián", "เงิน", "ngoen"],
      ["giá", "price", "价格", "jiàgé", "ราคา", "ra-kha"],
      ["trả", "to pay", "付", "fù", "จ่าย", "jai"],
      ["chuyển", "to transfer", "转账", "zhuǎnzhàng", "โอน", "on"],
      ["đổi tiền", "to exchange money", "换钱", "huàn qián", "แลกเงิน", "laek ngoen"],
      ["tài khoản", "account", "账户", "zhànghù", "บัญชี", "ban-chi"],
      ["ngân hàng", "bank", "银行", "yínháng", "ธนาคาร", "tha-na-khan"],
      ["rút", "to withdraw", "取钱", "qǔ qián", "ถอน", "thon"],
      ["gửi tiết kiệm", "to save", "存钱", "cún qián", "ออม", "om"],
      ["nợ", "debt / to owe", "欠", "qiàn", "หนี้", "ni"],
      ["đủ", "enough", "够", "gòu", "พอ", "pho"],
      ["thiếu", "not enough", "不够", "bú gòu", "ไม่พอ", "mai pho"],
      ["lương", "salary", "工资", "gōngzī", "เงินเดือน", "ngoen duean"],
      ["chi", "to spend", "花", "huā", "ใช้จ่าย", "chai jai"],
      ["tiết kiệm", "to save (spend less)", "节省", "jiéshěng", "ประหยัด", "pra-yat"],
      ["hóa đơn", "bill / receipt", "账单", "zhàngdān", "บิล", "bin"],
      ["phí", "fee", "费用", "fèiyòng", "ค่าธรรมเนียม", "kha tham-niam"],
      ["tỷ giá", "rate", "汇率", "huìlǜ", "อัตราแลกเปลี่ยน", "at-tra laek-plian"],
      ["tiền mặt", "cash", "现金", "xiànjīn", "เงินสด", "ngoen sot"],
      ["thẻ", "card", "卡", "kǎ", "บัตร", "bat"],
    ],
    [
      ["Mình trả bằng thẻ được không?", "Can I pay by card?", "可以刷卡吗？", "kěyǐ shuā kǎ ma?", "จ่ายบัตรได้ไหม", "jai bat dai mai"],
      ["Tiền mặt không đủ.", "I don't have enough cash.", "现金不够。", "xiànjīn bú gòu.", "เงินสดไม่พอ", "ngoen sot mai pho"],
      ["Mình chuyển cho bạn.", "I will transfer it to you.", "我转给你。", "wǒ zhuǎn gěi nǐ.", "ฉันจะโอนให้คุณ", "chan ja on hai khun"],
      ["Tỷ giá hôm nay thế nào?", "What is today's rate?", "今天汇率怎么样？", "jīntiān huìlǜ zěnmeyàng?", "อัตราแลกเปลี่ยนวันนี้เป็นไง", "at-tra laek-plian wan-nee pen ngai"],
      ["Phí này hơi cao.", "This fee is a bit high.", "这个费用有点高。", "zhège fèiyòng yǒudiǎn gāo.", "ค่าธรรมเนียมนี้สูงไปนิด", "kha tham-niam nee sung pai nit"],
      ["Mình muốn rút tiền.", "I want to withdraw money.", "我想取钱。", "wǒ xiǎng qǔ qián.", "ฉันอยากถอนเงิน", "chan yak thon ngoen"],
      ["Lương về cuối tháng.", "The salary comes at the end of the month.", "工资月底到。", "gōngzī yuèdǐ dào.", "เงินเดือนเข้าสิ้นเดือน", "ngoen duean khao sin duean"],
      ["Tháng này mình chi nhiều.", "I spent a lot this month.", "这个月我花很多。", "zhège yuè wǒ huā hěn duō.", "เดือนนี้ฉันใช้จ่ายเยอะ", "duean nee chan chai jai yoe"],
      ["Nên tiết kiệm hơn.", "We should save more.", "应该更节省。", "yīnggāi gèng jiéshěng.", "ควรประหยัดกว่านี้", "khuan pra-yat kwa nee"],
      ["Cho mình hóa đơn.", "The receipt, please.", "请给我账单。", "qǐng gěi wǒ zhàngdān.", "ขอบิลหน่อย", "kho bin noi"],
      ["Mình còn nợ bạn.", "I still owe you.", "我还欠你。", "wǒ hái qiàn nǐ.", "ฉันยังค้างคุณอยู่", "chan yang khang khun yu"],
      ["Ngân hàng đóng lúc năm giờ.", "The bank closes at five.", "银行五点关门。", "yínháng wǔ diǎn guānmén.", "ธนาคารปิดห้าโมง", "tha-na-khan pit ha mong"],
    ],
  ),
  unit(
    "cooking",
    "B1",
    ["Nấu ăn", "Cooking", "做饭", "zuò fàn", "ทำอาหาร", "tham a-han"],
    ["Nói nguyên liệu, cắt, nêm, và mời ăn.", "Name ingredients, cutting, seasoning, and inviting someone to eat.", "说食材、切、调味，并请客吃饭。", "", "พูดวัตถุดิบ หั่น ปรุง และชวนกิน", ""],
    [
      ["nấu", "to cook", "做", "zuò", "ทำ", "tham"],
      ["cắt", "to cut", "切", "qiē", "หั่น", "han"],
      ["rửa", "to wash", "洗", "xǐ", "ล้าง", "lang"],
      ["luộc", "to boil", "煮", "zhǔ", "ต้ม", "tom"],
      ["chiên", "to fry", "煎", "jiān", "ทอด", "thot"],
      ["nướng", "to grill", "烤", "kǎo", "ย่าง", "yang"],
      ["muối", "salt", "盐", "yán", "เกลือ", "kluea"],
      ["tiêu", "pepper", "胡椒", "hújiāo", "พริกไทย", "phrik-thai"],
      ["dầu", "oil", "油", "yóu", "น้ำมัน", "nam-man"],
      ["tỏi", "garlic", "蒜", "suàn", "กระเทียม", "kra-thiam"],
      ["hành", "onion", "洋葱", "yángcōng", "หอมใหญ่", "hom yai"],
      ["gạo", "rice", "米", "mǐ", "ข้าวสาร", "khao-san"],
      ["nêm", "to season", "调味", "tiáowèi", "ปรุง", "prung"],
      ["chín", "cooked / done", "熟了", "shú le", "สุก", "suk"],
      ["sống", "raw", "生的", "shēng de", "ดิบ", "dip"],
      ["nóng", "hot (food)", "烫", "tàng", "ร้อน", "ron"],
      ["mời", "to invite", "请", "qǐng", "เชิญ", "choen"],
      ["công thức", "recipe", "食谱", "shípǔ", "สูตร", "sut"],
      ["nồi", "pot", "锅", "guō", "หม้อ", "mo"],
      ["dao", "knife", "刀", "dāo", "มีด", "miet"],
    ],
    [
      ["Rửa rau trước khi cắt.", "Wash the vegetables before cutting.", "切菜前先洗。", "qiē cài qián xiān xǐ.", "ล้างผักก่อนหั่น", "lang phak kon han"],
      ["Cho một chút muối.", "Add a little salt.", "放一点盐。", "fàng yìdiǎn yán.", "ใส่เกลือนิดหน่อย", "sai kluea nit-noi"],
      ["Cơm chín chưa?", "Is the rice done?", "米饭熟了吗？", "mǐfàn shú le ma?", "ข้าวสุกหรือยัง", "khao suk rue yang"],
      ["Cẩn thận, nóng lắm.", "Careful, it is hot.", "小心，很烫。", "xiǎoxīn, hěn tàng.", "ระวัง ร้อนมาก", "ra-wang ron mak"],
      ["Mình nướng cá tối nay.", "I will grill fish tonight.", "今晚我烤鱼。", "jīn wǎn wǒ kǎo yú.", "คืนนี้ฉันย่างปลา", "khuen-nee chan yang pla"],
      ["Công thức này đơn giản.", "This recipe is simple.", "这个食谱很简单。", "zhège shípǔ hěn jiǎndān.", "สูตรนี้ง่าย", "sut nee ngai"],
      ["Dao sắc, để mình cắt.", "The knife is sharp, let me cut.", "刀很快，我来切。", "dāo hěn kuài, wǒ lái qiē.", "มีดคม ฉันหั่นเอง", "miet khom chan han eng"],
      ["Thịt còn sống.", "The meat is still raw.", "肉还是生的。", "ròu hái shì shēng de.", "เนื้อยังดิบ", "nuea yang dip"],
      ["Mời vào ăn.", "Please come and eat.", "请来吃饭。", "qǐng lái chīfàn.", "เชิญมากินข้าว", "choen ma kin khao"],
      ["Thiếu tỏi rồi.", "We are out of garlic.", "蒜没了。", "suàn méi le.", "กระเทียมหมดแล้ว", "kra-thiam mot laeo"],
      ["Chiên ít dầu thôi.", "Fry with little oil.", "少放油煎。", "shǎo fàng yóu jiān.", "ทอดน้ำมันน้อยๆ", "thot nam-man noi noi"],
      ["Nồi này nhỏ quá.", "This pot is too small.", "这个锅太小了。", "zhège guō tài xiǎo le.", "หม้อใบนี้เล็กไป", "mo bai nee lek pai"],
    ],
  ),
  unit(
    "cleaning",
    "A2",
    ["Dọn nhà", "Cleaning", "打扫", "dǎsǎo", "เก็บบ้าน", "kep ban"],
    ["Nói quét, lau, giặt, và nhà sạch hay bẩn.", "Talk about sweeping, wiping, laundry, and a clean or dirty home.", "说扫地、擦、洗衣服，以及家里干净还是脏。", "", "พูดกวาด เช็ด ซักผ้า และบ้านสะอาดหรือสกปรก", ""],
    [
      ["dọn", "to tidy", "收拾", "shōushi", "เก็บ", "kep"],
      ["quét", "to sweep", "扫地", "sǎo dì", "กวาด", "kwat"],
      ["lau", "to wipe", "擦", "cā", "เช็ด", "chet"],
      ["giặt", "to wash clothes", "洗衣服", "xǐ yīfu", "ซักผ้า", "sak pha"],
      ["phơi", "to hang to dry", "晾", "liàng", "ตาก", "tak"],
      ["rác", "rubbish", "垃圾", "lājī", "ขยะ", "kha-ya"],
      ["thùng", "bin", "垃圾桶", "lājī tǒng", "ถังขยะ", "thang kha-ya"],
      ["sạch", "clean", "干净", "gānjìng", "สะอาด", "sa-at"],
      ["bẩn", "dirty", "脏", "zāng", "สกปรก", "sok-ka-prok"],
      ["bụi", "dust", "灰", "huī", "ฝุ่น", "fun"],
      ["nước lau", "cleaner", "清洁剂", "qīngjiéjì", "น้ำยา", "nam-ya"],
      ["chổi", "broom", "扫帚", "sàozhou", "ไม้กวาด", "mai kwat"],
      ["khăn lau", "cloth", "抹布", "mābù", "ผ้าเช็ด", "pha chet"],
      ["máy giặt", "washing machine", "洗衣机", "xǐyījī", "เครื่องซักผ้า", "khrueang sak pha"],
      ["gấp", "to fold", "叠", "dié", "พับ", "phap"],
      ["cất", "to put away", "放好", "fàng hǎo", "เก็บเข้าที่", "kep khao thee"],
      ["mùi", "smell", "味道", "wèidao", "กลิ่น", "klin"],
      ["thoáng", "fresh air", "通风", "tōngfēng", "โล่ง", "long"],
      ["xong", "done", "好了", "hǎo le", "เสร็จ", "set"],
      ["giúp", "to help", "帮忙", "bāngmáng", "ช่วย", "chuai"],
    ],
    [
      ["Nhà hơi bẩn.", "The house is a bit dirty.", "家里有点脏。", "jiā lǐ yǒudiǎn zāng.", "บ้านสกปรกไปนิด", "ban sok-ka-prok pai nit"],
      ["Mình quét phòng khách.", "I will sweep the living room.", "我扫客厅。", "wǒ sǎo kètīng.", "ฉันจะกวาดห้องนั่งเล่น", "chan ja kwat hong nang-len"],
      ["Lau bàn giúp mình.", "Please wipe the table.", "请擦一下桌子。", "qǐng cā yíxià zhuōzi.", "ช่วยเช็ดโต๊ะหน่อย", "chuai chet to noi"],
      ["Đổ rác đi.", "Take out the rubbish.", "把垃圾倒掉。", "bǎ lājī dào diào.", "เอาขยะไปทิ้ง", "ao kha-ya pai thing"],
      ["Máy giặt đang chạy.", "The washing machine is on.", "洗衣机在转。", "xǐyījī zài zhuàn.", "เครื่องซักผ้ากำลังทำงาน", "khrueang sak pha kam-lang tham-ngan"],
      ["Phơi áo ngoài ban công.", "Hang the shirts on the balcony.", "衣服晾在阳台上。", "yīfu liàng zài yángtái shàng.", "ตากเสื้อที่ระเบียง", "tak suea thee ra-biang"],
      ["Gấp quần áo rồi cất.", "Fold the clothes and put them away.", "衣服叠好放好。", "yīfu dié hǎo fàng hǎo.", "พับผ้าแล้วเก็บเข้าที่", "phap pha laeo kep khao thee"],
      ["Mở cửa cho thoáng.", "Open the door for fresh air.", "开门通通风。", "kāi mén tōng tōng fēng.", "เปิดประตูให้อากาศโล่ง", "poet pra-tu hai a-kat long"],
      ["Có mùi lạ.", "There is a strange smell.", "有奇怪的味道。", "yǒu qíguài de wèidao.", "มีกลิ่นแปลก", "mee klin plaek"],
      ["Xong rồi, sạch hơn.", "Done, it is cleaner now.", "好了，干净多了。", "hǎo le, gānjìng duō le.", "เสร็จแล้ว สะอาดขึ้น", "set laeo sa-at khuen"],
      ["Thiếu nước lau.", "We are out of cleaner.", "清洁剂没了。", "qīngjiéjì méi le.", "น้ำยาหมดแล้ว", "nam-ya mot laeo"],
      ["Giúp mình dọn bếp.", "Help me tidy the kitchen.", "帮我收拾厨房。", "bāng wǒ shōushi chúfáng.", "ช่วยเก็บครัวหน่อย", "chuai kep khrua noi"],
    ],
  ),
  unit(
    "pets",
    "A2",
    ["Thú cưng", "Pets", "宠物", "chǒngwù", "สัตว์เลี้ยง", "sat liang"],
    ["Nói chó mèo, cho ăn, dắt đi, và thú cưng bệnh.", "Talk about dogs and cats, feeding, walking, and a sick pet.", "说猫狗、喂食、遛狗，以及宠物生病。", "", "พูดแมวหมา ให้อาหาร พาเดิน และสัตว์เลี้ยงป่วย", ""],
    [
      ["thú cưng", "pet", "宠物", "chǒngwù", "สัตว์เลี้ยง", "sat liang"],
      ["chó", "dog", "狗", "gǒu", "หมา", "ma"],
      ["mèo", "cat", "猫", "māo", "แมว", "maeo"],
      ["cá", "fish", "鱼", "yú", "ปลา", "pla"],
      ["chim", "bird", "鸟", "niǎo", "นก", "nok"],
      ["cho ăn", "to feed", "喂", "wèi", "ให้อาหาร", "hai a-han"],
      ["dắt", "to walk (a dog)", "遛", "liù", "พาเดิน", "pha doen"],
      ["vuốt", "to stroke", "摸", "mō", "ลูบ", "lup"],
      ["cắn", "to bite", "咬", "yǎo", "กัด", "kat"],
      ["sủa", "to bark", "叫", "jiào", "เห่า", "hao"],
      ["lồng", "cage", "笼子", "lóngzi", "กรง", "krong"],
      ["xích", "leash", "绳子", "shéngzi", "สายจูง", "sai jung"],
      ["thú y", "vet", "兽医", "shòuyī", "หมอสัตว์", "mo sat"],
      ["tiêm", "vaccine / injection", "打针", "dǎ zhēn", "ฉีดยา", "chit ya"],
      ["bệnh", "ill", "生病", "shēngbìng", "ป่วย", "puai"],
      ["nghịch", "playful", "调皮", "tiáopí", "ซน", "son"],
      ["ngoan", "well-behaved", "乖", "guāi", "เรียบร้อย", "riap-roi"],
      ["lông", "fur", "毛", "máo", "ขน", "khon"],
      ["dị ứng", "allergy", "过敏", "guòmǐn", "แพ้", "phae"],
      ["nhà", "home", "家", "jiā", "บ้าน", "ban"],
    ],
    [
      ["Nhà mình nuôi mèo.", "We keep a cat at home.", "家里养猫。", "jiā lǐ yǎng māo.", "บ้านฉันเลี้ยงแมว", "ban chan liang maeo"],
      ["Chó cần dắt mỗi ngày.", "The dog needs a walk every day.", "狗每天要遛。", "gǒu měi tiān yào liù.", "หมาต้องพาเดินทุกวัน", "ma tong pha doen thuk wan"],
      ["Cho ăn chưa?", "Have you fed it yet?", "喂过了吗？", "wèi guò le ma?", "ให้อาหารหรือยัง", "hai a-han rue yang"],
      ["Mèo này ngoan.", "This cat is well-behaved.", "这只猫很乖。", "zhè zhī māo hěn guāi.", "แมวตัวนี้เรียบร้อย", "maeo tua nee riap-roi"],
      ["Nó cắn nhẹ thôi.", "It only nips a little.", "它只是轻轻咬。", "tā zhǐshì qīngqīng yǎo.", "มันกัดนิดเดียว", "man kat nit diao"],
      ["Mình dị ứng lông.", "I am allergic to fur.", "我对毛过敏。", "wǒ duì máo ​​guòmǐn.", "ฉันแพ้ขน", "chan phae khon"],
      ["Phải đưa tới thú y.", "We need to take it to the vet.", "得去看兽医。", "děi qù kàn shòuyī.", "ต้องพาไปหาหมอสัตว์", "tong pha pai ha mo sat"],
      ["Đến lúc tiêm rồi.", "It is time for the vaccine.", "该打针了。", "gāi dǎ zhēn le.", "ถึงเวลาฉีดยาแล้ว", "thueng we-la chit ya laeo"],
      ["Nó đang bệnh.", "It is ill.", "它生病了。", "tā shēngbìng le.", "มันป่วย", "man puai"],
      ["Đừng sủa nữa.", "Stop barking.", "别再叫了。", "bié zài jiào le.", "อย่าเห่าอีก", "ya hao ik"],
      ["Cầm xích chắc tay.", "Hold the leash firmly.", "绳子拿好。", "shéngzi ná hǎo.", "จับสายจูงให้แน่น", "jap sai jung hai naen"],
      ["Cá cần nước sạch.", "The fish need clean water.", "鱼需要干净的水。", "yú xūyào gānjìng de shuǐ.", "ปลาต้องการน้ำสะอาด", "pla tong-kan nam sa-at"],
    ],
  ),
  unit(
    "holidays",
    "B1",
    ["Ngày lễ", "Holidays", "节日", "jiérì", "วันหยุด", "wan yut"],
    ["Nói nghỉ lễ, tặng quà, chúc mừng, và kế hoạch.", "Talk about days off, gifts, wishes, and plans.", "说放假、送礼、祝福和计划。", "", "พูดวันหยุด ของขวัญ คำอวยพร และแผน", ""],
    [
      ["ngày lễ", "holiday", "节日", "jiérì", "วันหยุด", "wan yut"],
      ["nghỉ", "day off", "放假", "fàngjià", "หยุด", "yut"],
      ["quà", "gift", "礼物", "lǐwù", "ของขวัญ", "khong-khwan"],
      ["tặng", "to give (a gift)", "送", "sòng", "ให้", "hai"],
      ["chúc", "to wish", "祝", "zhù", "อวยพร", "uai-phon"],
      ["sinh nhật", "birthday", "生日", "shēngrì", "วันเกิด", "wan koet"],
      ["năm mới", "new year", "新年", "xīnnián", "ปีใหม่", "pee mai"],
      ["Tết", "Lunar New Year", "春节", "chūnjié", "ตรุษจีน", "trut jin"],
      ["tiệc", "party", "聚会", "jùhuì", "ปาร์ตี้", "pa-tee"],
      ["bắn pháo", "fireworks", "烟花", "yānhuā", "ดอกไม้ไฟ", "dok-mai fai"],
      ["về quê", "to go home (hometown)", "回老家", "huí lǎojiā", "กลับบ้านเกิด", "klap ban koet"],
      ["đông", "crowded", "热闹", "rènao", "คนเยอะ", "khon yoe"],
      ["đỏ", "red", "红", "hóng", "แดง", "daeng"],
      ["may mắn", "lucky", "幸运", "xìngyùn", "โชคดี", "chok-dee"],
      ["hạnh phúc", "happy (wish)", "幸福", "xìngfú", "มีความสุข", "mee khwam suk"],
      ["kế hoạch", "plan", "计划", "jìhuà", "แผน", "phaen"],
      ["nghỉ dài", "long break", "长假", "cháng jià", "หยุดยาว", "yut yao"],
      ["kẹt", "stuck / booked out", "订满", "dìng mǎn", "เต็ม", "tem"],
      ["vé", "ticket", "票", "piào", "ตั๋ว", "tua"],
      ["cùng", "together", "一起", "yìqǐ", "ด้วยกัน", "duai kan"],
    ],
    [
      ["Tuần sau mình nghỉ lễ.", "I have a holiday next week.", "下周我放假。", "xià zhōu wǒ fàngjià.", "สัปดาห์หน้าฉันหยุด", "sap-da na chan yut"],
      ["Chúc bạn sinh nhật vui.", "Happy birthday.", "祝你生日快乐。", "zhù nǐ shēngrì kuàilè.", "สุขสันต์วันเกิด", "suk-san wan koet"],
      ["Mình tặng bạn một món nhỏ.", "I have a small gift for you.", "我送你一个小礼物。", "wǒ sòng nǐ yí gè xiǎo lǐwù.", "ฉันมีของขวัญเล็กๆ ให้คุณ", "chan mee khong-khwan lek lek hai khun"],
      ["Tết mình về quê.", "At New Year I go back to my hometown.", "春节我回老家。", "chūnjié wǒ huí lǎojiā.", "ช่วงตรุษฉันกลับบ้านเกิด", "chuang trut chan klap ban koet"],
      ["Năm mới hạnh phúc.", "Happy new year.", "新年快乐。", "xīnnián kuàilè.", "สวัสดีปีใหม่", "sa-wat-dee pee mai"],
      ["Tối nay có tiệc nhỏ.", "There is a small party tonight.", "今晚有个小聚会。", "jīn wǎn yǒu gè xiǎo jùhuì.", "คืนนี้มีปาร์ตี้เล็กๆ", "khuen-nee mee pa-tee lek lek"],
      ["Vé tàu đã kẹt.", "Train tickets are sold out.", "火车票订满了。", "huǒchē piào dìng mǎn le.", "ตั๋วรถไฟเต็มแล้ว", "tua rot-fai tem laeo"],
      ["Đường đông lắm.", "The streets are packed.", "路上很热闹。", "lù shàng hěn rènao.", "ถนนคนเยอะมาก", "tha-non khon yoe mak"],
      ["Kế hoạch nghỉ dài chưa xong.", "The long-break plan is not ready yet.", "长假计划还没定。", "cháng jià jìhuà hái méi dìng.", "แผนหยุดยายังไม่เสร็จ", "phaen yut yao yang mai set"],
      ["Cùng đón năm mới.", "Let's see the new year in together.", "一起跨年吧。", "yìqǐ kuà nián ba.", "มาฉลองปีใหม่ด้วยกัน", "ma cha-long pee mai duai kan"],
      ["Chúc may mắn.", "Good luck.", "祝你好运。", "zhù nǐ hǎo yùn.", "โชคดีนะ", "chok-dee na"],
      ["Pháo hoa đẹp quá.", "The fireworks are beautiful.", "烟花真好看。", "yānhuā zhēn hǎokàn.", "ดอกไม้ไฟสวยมาก", "dok-mai fai suai mak"],
    ],
  ),
  unit(
    "neighbors",
    "B1",
    ["Hàng xóm", "Neighbours", "邻居", "línjū", "เพื่อนบ้าน", "phuean ban"],
    ["Chào hàng xóm, xin lỗi vì ồn, nhờ giữ đồ.", "Greet neighbours, apologise for noise, ask them to keep a parcel.", "打招呼、为噪音道歉、请帮忙收快递。", "", "ทักเพื่อนบ้าน ขอโทษที่เสียงดัง ฝากพัสดุ", ""],
    [
      ["hàng xóm", "neighbour", "邻居", "línjū", "เพื่อนบ้าน", "phuean ban"],
      ["tầng", "floor", "楼层", "lóucéng", "ชั้น", "chan"],
      ["cửa", "door", "门", "mén", "ประตู", "pra-tu"],
      ["ồn", "noise", "噪音", "zàoyīn", "เสียงดัง", "siang dang"],
      ["xin lỗi", "sorry", "对不起", "duìbuqǐ", "ขอโทษ", "kho-thot"],
      ["nhờ", "to ask a favour", "拜托", "bàituō", "ฝาก", "fak"],
      ["giữ", "to keep", "帮收", "bāng shōu", "รับไว้", "rap wai"],
      ["bưu kiện", "parcel", "快递", "kuàidì", "พัสดุ", "phat-sadu"],
      ["chìa", "key", "钥匙", "yàoshi", "กุญแจ", "kun-jae"],
      ["thang", "stairs", "楼梯", "lóutī", "บันได", "ban-dai"],
      ["thang máy", "lift", "电梯", "diàntī", "ลิฟต์", "lif"],
      ["chó", "dog", "狗", "gǒu", "หมา", "ma"],
      ["trẻ", "children", "孩子", "háizi", "เด็ก", "dek"],
      ["muộn", "late", "晚", "wǎn", "ดึก", "duek"],
      ["sớm", "early", "早", "zǎo", "เช้า", "chao"],
      ["yên", "quiet", "安静", "ānjìng", "เงียบ", "ngiap"],
      ["giúp", "to help", "帮忙", "bāngmáng", "ช่วย", "chuai"],
      ["cảm ơn", "thank you", "谢谢", "xièxie", "ขอบคุณ", "khop-khun"],
      ["gặp", "to meet", "见面", "jiànmiàn", "เจอ", "joe"],
      ["chung cư", "apartment building", "小区", "xiǎoqū", "คอนโด", "khon-do"],
    ],
    [
      ["Xin chào, mình ở tầng trên.", "Hello, I live on the floor above.", "你好，我住楼上。", "nǐ hǎo, wǒ zhù lóu shàng.", "สวัสดี ฉันอยู่ชั้นบน", "sa-wat-dee chan yu chan bon"],
      ["Xin lỗi vì ồn tối qua.", "Sorry about the noise last night.", "抱歉昨晚太吵。", "bàoqiàn zuó wǎn tài chǎo.", "ขอโทษที่เมื่อคืนเสียงดัง", "kho-thot thee muea-khuen siang dang"],
      ["Nhờ bạn giữ bưu kiện giúp.", "Could you keep a parcel for me?", "能帮我收个快递吗？", "néng bāng wǒ shōu gè kuàidì ma?", "ฝากรับพัสดุให้หน่อยได้ไหม", "fak rap phat-sadu hai noi dai mai"],
      ["Thang máy hỏng.", "The lift is broken.", "电梯坏了。", "diàntī huài le.", "ลิฟต์พัง", "lif phang"],
      ["Đi thang bộ nhé.", "Let's take the stairs.", "走楼梯吧。", "zǒu lóutī ba.", "ขึ้นบันไดกัน", "khuen ban-dai kan"],
      ["Chó nhà mình sủa muộn.", "Our dog barked late.", "我家狗叫得晚。", "wǒ jiā gǒu jiào de wǎn.", "หมาบ้านฉันเห่าดึก", "ma ban chan hao duek"],
      ["Mình sẽ yên hơn.", "I will keep it quieter.", "我会安静些。", "wǒ huì ānjìng xiē.", "ฉันจะเงียบกว่านี้", "chan ja ngiap kwa nee"],
      ["Cảm ơn vì đã giúp.", "Thank you for helping.", "谢谢你帮忙。", "xièxie nǐ bāngmáng.", "ขอบคุณที่ช่วย", "khop-khun thee chuai"],
      ["Gặp nhau ở cửa.", "We met at the door.", "我们在门口见面。", "wǒmen zài ménkǒu jiànmiàn.", "เราเจอกันที่ประตู", "rao joe kan thee pra-tu"],
      ["Chung cư này yên.", "This building is quiet.", "这个小区很安静。", "zhège xiǎoqū hěn ānjìng.", "คอนโดนี้เงียบ", "khon-do nee ngiap"],
      ["Trẻ nhà bên cười vui.", "The children next door sound happy.", "隔壁孩子笑得很开心。", "gébì háizi xiào de hěn kāixīn.", "เด็กบ้านข้างๆ หัวเราะสนุก", "dek ban khang khang hua-ro sa-nuk"],
      ["Mình quên chìa ở nhà bạn.", "I left my key at yours.", "钥匙忘在你家了。", "yàoshi wàng zài nǐ jiā le.", "ฉันลืมกุญแจไว้บ้านคุณ", "chan luem kun-jae wai ban khun"],
    ],
  ),
  unit(
    "internet",
    "B1",
    ["Mạng và máy", "Internet and devices", "网络和设备", "wǎngluò hé shèbèi", "เน็ตและเครื่อง", "net lae khrueang"],
    ["Nói wifi chậm, tải tệp, họp online, và bảo mật đơn giản.", "Talk about slow wifi, downloads, online meetings, and simple privacy.", "说网慢、下载、线上开会，以及简单隐私。", "", "พูดเน็ตช้า ดาวน์โหลด ประชุมออนไลน์ และความเป็นส่วนตัวแบบง่าย", ""],
    [
      ["mạng", "internet", "网络", "wǎngluò", "เน็ต", "net"],
      ["wifi", "wifi", "无线网", "wúxiàn wǎng", "ไวไฟ", "wai-fai"],
      ["chậm", "slow", "慢", "màn", "ช้า", "cha"],
      ["nhanh", "fast", "快", "kuài", "เร็ว", "reo"],
      ["tải", "to download", "下载", "xiàzài", "ดาวน์โหลด", "daon-lot"],
      ["gửi tệp", "to send a file", "发文件", "fā wénjiàn", "ส่งไฟล์", "song fai"],
      ["mật khẩu", "password", "密码", "mìmǎ", "รหัส", "rat"],
      ["đăng nhập", "to log in", "登录", "dēnglù", "เข้าสู่ระบบ", "khao su ra-bop"],
      ["lỗi", "error", "出错", "chū cuò", "error", "i-roe"],
      ["cập nhật", "to update", "更新", "gēngxīn", "อัปเดต", "ap-det"],
      ["họp online", "online meeting", "线上会议", "xiànshàng huìyì", "ประชุมออนไลน์", "pra-chum on-lai"],
      ["camera", "camera", "摄像头", "shèxiàngtóu", "กล้อง", "klong"],
      ["mic", "microphone", "麦克风", "màikèfēng", "ไมค์", "mai"],
      ["tắt", "to turn off", "关", "guān", "ปิด", "pit"],
      ["bật", "to turn on", "开", "kāi", "เปิด", "poet"],
      ["riêng tư", "private", "隐私", "yǐnsī", "ส่วนตัว", "suan-tua"],
      ["chia sẻ", "to share", "分享", "fēnxiǎng", "แชร์", "chae"],
      ["link", "link", "链接", "liànjiē", "ลิงก์", "ling"],
      ["màn hình", "screen", "屏幕", "píngmù", "หน้าจอ", "na-jo"],
      ["máy tính", "computer", "电脑", "diànnǎo", "คอมพิวเตอร์", "khom-phu-toe"],
    ],
    [
      ["Wifi chậm quá.", "The wifi is too slow.", "无线网太慢了。", "wúxiàn wǎng tài màn le.", "ไวไฟช้ามาก", "wai-fai cha mak"],
      ["Mình không đăng nhập được.", "I cannot log in.", "我登录不了。", "wǒ dēnglù bù liǎo.", "ฉันเข้าสู่ระบบไม่ได้", "chan khao su ra-bop mai dai"],
      ["Gửi tệp giúp mình.", "Please send the file.", "请把文件发给我。", "qǐng bǎ wénjiàn fā gěi wǒ.", "ส่งไฟล์ให้ฉันหน่อย", "song fai hai chan noi"],
      ["Link không mở.", "The link will not open.", "链接打不开。", "liànjiē dǎ bù kāi.", "ลิงก์เปิดไม่ได้", "ling poet mai dai"],
      ["Họp online lúc hai giờ.", "The online meeting is at two.", "线上会议两点开始。", "xiànshàng huìyì liǎng diǎn kāishǐ.", "ประชุมออนไลน์สองโมง", "pra-chum on-lai song mong"],
      ["Tắt mic giúp mình.", "Please mute the mic.", "请把麦克风关掉。", "qǐng bǎ màikèfēng guān diào.", "ช่วยปิดไมค์หน่อย", "chuai pit mai noi"],
      ["Camera không lên.", "The camera is not on.", "摄像头没开。", "shèxiàngtóu méi kāi.", "กล้องไม่ขึ้น", "klong mai khuen"],
      ["Cập nhật máy đi.", "Please update the computer.", "把电脑更新一下。", "bǎ diànnǎo gēngxīn yíxià.", "อัปเดตเครื่องหน่อย", "ap-det khrueang noi"],
      ["Đừng chia sẻ mật khẩu.", "Don't share the password.", "不要分享密码。", "bú yào fēnxiǎng mìmǎ.", "อย่าแชร์รหัส", "ya chae rat"],
      ["Cái này là riêng tư.", "This is private.", "这是隐私。", "zhè shì yǐnsī.", "นี่เป็นเรื่องส่วนตัว", "nee pen rueang suan-tua"],
      ["Tải xong chưa?", "Has it finished downloading?", "下载好了吗？", "xiàzài hǎo le ma?", "ดาวน์โหลดเสร็จหรือยัง", "daon-lot set rue yang"],
      ["Màn hình bị lỗi.", "The screen has an error.", "屏幕出错了。", "píngmù chū cuò le.", "หน้าจอมี error", "na-jo mee i-roe"],
    ],
  ),
  unit(
    "school",
    "B1",
    ["Trường lớp", "School", "学校", "xuéxiào", "โรงเรียน", "rohng-rian"],
    ["Nói lớp, bài tập, giáo viên, và xin nghỉ.", "Talk about class, homework, teachers, and asking for a day off.", "说课、作业、老师，以及请假。", "", "พูดห้องเรียน การบ้าน ครู และขอลา", ""],
    [
      ["trường", "school", "学校", "xuéxiào", "โรงเรียน", "rohng-rian"],
      ["lớp", "class", "课 / 班", "kè / bān", "ห้องเรียน", "hong-rian"],
      ["giáo viên", "teacher", "老师", "lǎoshī", "ครู", "khru"],
      ["học sinh", "student", "学生", "xuéshēng", "นักเรียน", "nak-rian"],
      ["bài tập", "homework", "作业", "zuòyè", "การบ้าน", "kan-ban"],
      ["thi", "test", "考试", "kǎoshì", "สอบ", "sop"],
      ["điểm", "grade / score", "分数", "fēnshù", "คะแนน", "kha-naen"],
      ["vở", "notebook", "本子", "běnzi", "สมุด", "sa-mut"],
      ["bút", "pen", "笔", "bǐ", "ปากกา", "pak-ka"],
      ["bảng", "board", "黑板", "hēibǎn", "กระดาน", "kra-dan"],
      ["giờ ra chơi", "break", "课间", "kèjiān", "พัก", "phak"],
      ["xin nghỉ", "to ask for leave", "请假", "qǐngjià", "ขอลา", "kho la"],
      ["đi trễ", "to be late", "迟到", "chídào", "มาสาย", "ma sai"],
      ["vắng", "absent", "缺席", "quēxí", "ขาด", "khat"],
      ["hiểu", "to understand", "懂", "dǒng", "เข้าใจ", "khao-jai"],
      ["hỏi", "to ask", "问", "wèn", "ถาม", "tham"],
      ["nhóm", "group", "小组", "xiǎozǔ", "กลุ่ม", "klum"],
      ["thuyết trình", "to present", "汇报", "huìbào", "พรีเซนต์", "pri-sen"],
      ["thư viện", "library", "图书馆", "túshūguǎn", "ห้องสมุด", "hong sa-mut"],
      ["kỷ luật", "rules", "纪律", "jìlǜ", "กฎ", "kot"],
    ],
    [
      ["Mai có bài kiểm tra.", "There is a test tomorrow.", "明天有考试。", "míngtiān yǒu kǎoshì.", "พรุ่งนี้มีสอบ", "phrung-nee mee sop"],
      ["Bài tập hơi nhiều.", "There is quite a lot of homework.", "作业有点多。", "zuòyè yǒudiǎn duō.", "การบ้านเยอะไปนิด", "kan-ban yoe pai nit"],
      ["Mình chưa hiểu câu này.", "I don't understand this sentence yet.", "这句我还没懂。", "zhè jù wǒ hái méi dǒng.", "ประโยคนี้ฉันยังไม่เข้าใจ", "pra-yok nee chan yang mai khao-jai"],
      ["Xin hỏi giáo viên được không?", "May I ask the teacher?", "可以问老师吗？", "kěyǐ wèn lǎoshī ma?", "ถามครูได้ไหม", "tham khru dai mai"],
      ["Mình xin nghỉ một ngày.", "I need one day off.", "我请一天假。", "wǒ qǐng yì tiān jià.", "ฉันขอลาหนึ่งวัน", "chan kho la nueng wan"],
      ["Xin lỗi mình đi trễ.", "Sorry I am late.", "抱歉我迟到了。", "bàoqiàn wǒ chídào le.", "ขอโทษที่มาสาย", "kho-thot thee ma sai"],
      ["Nhóm mình thuyết trình thứ Năm.", "Our group presents on Thursday.", "我们小组周四汇报。", "wǒmen xiǎozǔ zhōu sì huìbào.", "กลุ่มเราพรีเซนต์วันพฤหัส", "klum rao pri-sen wan phru-hat"],
      ["Gặp ở thư viện.", "Meet at the library.", "在图书馆见。", "zài túshūguǎn jiàn.", "เจอกันที่ห้องสมุด", "joe kan thee hong sa-mut"],
      ["Điểm lần này ổn.", "This score is okay.", "这次分数还行。", "zhè cì fēnshù hái xíng.", "คะแนนครั้งนี้อยู่ได้", "kha-naen khrang nee yu dai"],
      ["Giờ ra chơi ngắn.", "The break is short.", "课间很短。", "kèjiān hěn duǎn.", "พักสั้น", "phak san"],
      ["Mang vở và bút.", "Bring a notebook and a pen.", "带本子和笔。", "dài běnzi hé bǐ.", "เอาสมุดกับปากกา", "ao sa-mut kap pak-ka"],
      ["Lớp hôm nay vắng vài bạn.", "A few students are absent today.", "今天班上缺了几个人。", "jīntiān bān shàng quē le jǐ gè rén.", "วันนี้ห้องขาดไปหลายคน", "wan-nee hong khat pai lai khon"],
    ],
  ),
];
