import { unit } from "./learn-bank-a.mjs";

/** B2 everyday — original Linlin path for every track, not exam papers. */

export const UNITS_D = [
  unit(
    "complaints",
    "B2",
    ["Phàn nàn nhẹ", "Gentle complaints", "委婉投诉", "wěiwǎn tóusù", "การร้องเรียนอย่างสุภาพ", "kan rong-rian yang su-phap"],
    ["Nói sự cố, xin đổi, giữ giọng lịch sự.", "Name the problem, ask for a change, stay polite.", "说明问题、请求更换，并保持礼貌。", "", "บอกปัญหา ขอเปลี่ยน และรักษาน้ำเสียงสุภาพ", ""],
    [
      ["phàn nàn", "complaint", "投诉", "tóusù", "ร้องเรียน", "rong-rian"],
      ["sự cố", "problem", "问题", "wèntí", "ปัญหา", "pan-ha"],
      ["hỏng", "broken", "坏了", "huài le", "พัง", "phang"],
      ["sai", "wrong", "错了", "cuò le", "ผิด", "phit"],
      ["muộn", "late", "晚了", "wǎn le", "สาย", "sai"],
      ["đổi", "to replace", "换", "huàn", "เปลี่ยน", "plian"],
      ["hoàn", "to refund", "退款", "tuìkuǎn", "คืนเงิน", "khuen ngoen"],
      ["lịch sự", "polite", "礼貌", "lǐmào", "สุภาพ", "su-phap"],
      ["thất vọng", "disappointed", "失望", "shīwàng", "ผิดหวัง", "phit-wang"],
      ["chờ", "to wait", "等待", "děngdài", "รอ", "ro"],
      ["giải thích", "to explain", "解释", "jiěshì", "อธิบาย", "a-thi-bai"],
      ["giải quyết", "to resolve", "解决", "jiějué", "แก้", "kae"],
      ["quản lý", "manager", "经理", "jīnglǐ", "ผู้จัดการ", "phu jat-kan"],
      ["hóa đơn", "bill", "账单", "zhàngdān", "บิล", "bin"],
      ["không đúng", "not correct", "不对", "bú duì", "ไม่ถูก", "mai thuk"],
      ["lần này", "this time", "这次", "zhè cì", "ครั้งนี้", "khrang nee"],
      ["lần sau", "next time", "下次", "xià cì", "ครั้งหน้า", "khrang na"],
      ["mong", "to hope", "希望", "xīwàng", "หวัง", "wang"],
      ["hiểu", "to understand", "理解", "lǐjiě", "เข้าใจ", "khao-jai"],
      ["cảm ơn", "thank you", "谢谢", "xièxie", "ขอบคุณ", "khop-khun"],
    ],
    [
      ["Xin lỗi, món này không đúng.", "Sorry, this dish is not right.", "不好意思，这道菜不对。", "bù hǎoyìsi, zhè dào cài bú duì.", "ขอโทษ อาหารจานนี้ไม่ถูก", "kho-thot a-han jan nee mai thuk"],
      ["Mình đã chờ khá lâu.", "I have waited quite a long time.", "我等了很久。", "wǒ děng le hěn jiǔ.", "ฉันรอนานแล้ว", "chan ro nan laeo"],
      ["Có thể đổi giúp mình không?", "Could you replace this for me?", "可以帮我换一下吗？", "kěyǐ bāng wǒ huàn yíxià ma?", "ช่วยเปลี่ยนให้ได้ไหม", "chuai plian hai dai mai"],
      ["Mình hơi thất vọng lần này.", "I am a bit disappointed this time.", "这次我有点失望。", "zhè cì wǒ yǒudiǎn shīwàng.", "ครั้งนี้ฉันผิดหวังนิดหน่อย", "khrang nee chan phit-wang nit-noi"],
      ["Làm ơn giải thích giúp.", "Please explain it to me.", "请解释一下。", "qǐng jiěshì yíxià.", "ช่วยอธิบายหน่อย", "chuai a-thi-bai noi"],
      ["Mình muốn gặp quản lý.", "I would like to see the manager.", "我想见经理。", "wǒ xiǎng jiàn jīnglǐ.", "ฉันอยากพบผู้จัดการ", "chan yak phop phu jat-kan"],
      ["Hóa đơn hình như sai.", "The bill seems wrong.", "账单好像错了。", "zhàngdān hǎoxiàng cuò le.", "บิลดูเหมือนผิด", "bin du muean phit"],
      ["Mình hiểu các bạn đang bận.", "I understand you are busy.", "我理解你们很忙。", "wǒ lǐjiě nǐmen hěn máng.", "ฉันเข้าใจว่าพวกคุณยุ่ง", "chan khao-jai wa phuak khun yung"],
      ["Mong lần sau nhanh hơn.", "I hope next time it will be quicker.", "希望下次能快一点。", "xīwàng xià cì néng kuài yìdiǎn.", "หวังว่าครั้งหน้าจะเร็วกว่านี้", "wang wa khrang na ja reo kwa nee"],
      ["Nếu được, mình xin hoàn một phần.", "If possible, I would like a partial refund.", "如果可以，我想退一部分。", "rúguǒ kěyǐ, wǒ xiǎng tuì yí bùfen.", "ถ้าได้ ฉันขอคืนเงินบางส่วน", "tha dai chan kho khuen ngoen bang suan"],
      ["Cảm ơn vì đã giải quyết.", "Thank you for resolving this.", "谢谢你解决。", "xièxie nǐ jiějué.", "ขอบคุณที่ช่วยแก้", "khop-khun thee chuai kae"],
      ["Giọng mình vẫn lịch sự.", "I am still keeping a polite tone.", "我还是很礼貌。", "wǒ háishì hěn lǐmào.", "น้ำเสียงฉันยังสุภาพ", "nam-siang chan yang su-phap"],
    ],
  ),
  unit(
    "advice",
    "B2",
    ["Khuyên nhẹ", "Giving advice", "给建议", "gěi jiànyì", "การให้คำแนะนำ", "kan hai kham nae-nam"],
    ["Đưa ý kiến nhẹ, nêu lý do, không ra lệnh.", "Give soft advice, add a reason, avoid orders.", "给温和建议、说明理由，不要下命令。", "", "ให้คำแนะนำเบาๆ บอกเหตุผล ไม่สั่ง", ""],
    [
      ["khuyên", "to advise", "建议", "jiànyì", "แนะนำ", "nae-nam"],
      ["nên", "should", "应该", "yīnggāi", "ควร", "khuan"],
      ["có lẽ", "perhaps", "也许", "yěxǔ", "บางที", "bang-thee"],
      ["nếu", "if", "如果", "rúguǒ", "ถ้า", "tha"],
      ["thì", "then", "就", "jiù", "ก็", "ko"],
      ["thử", "to try", "试试", "shìshi", "ลอง", "long"],
      ["tránh", "to avoid", "避免", "bìmiǎn", "เลี่ยง", "liang"],
      ["lý do", "reason", "理由", "lǐyóu", "เหตุผล", "het-phon"],
      ["tốt hơn", "better", "更好", "gèng hǎo", "ดีกว่า", "dee kwa"],
      ["nguy", "risky", "有风险", "yǒu fēngxiǎn", "เสี่ยง", "siang"],
      ["an toàn", "safe", "安全", "ānquán", "ปลอดภัย", "plot phai"],
      ["từ từ", "slowly", "慢慢", "mànmàn", "ค่อยๆ", "khoi khoi"],
      ["đừng", "don't", "不要", "bú yào", "อย่า", "ya"],
      ["cân nhắc", "to consider", "考虑", "kǎolǜ", "คิดให้ดี", "khit hai dee"],
      ["kinh nghiệm", "experience", "经验", "jīngyàn", "ประสบการณ์", "pra-sop-kan"],
      ["theo mình", "in my view", "在我看来", "zài wǒ kàn lái", "ในความเห็นฉัน", "nai khwam-hen chan"],
      ["tùy", "up to you", "随你", "suí nǐ", "แล้วแต่คุณ", "laeo tae khun"],
      ["hữu ích", "useful", "有用", "yǒuyòng", "มีประโยชน์", "mee pra-yot"],
      ["áp lực", "pressure", "压力", "yālì", "ความกดดัน", "khwam kot-dan"],
      ["nghỉ", "to rest", "休息", "xiūxi", "พัก", "phak"],
    ],
    [
      ["Theo mình, nên học chậm hơn.", "In my view, you should study more slowly.", "在我看来，你应该学得慢一点。", "zài wǒ kàn lái, nǐ yīnggāi xué de màn yìdiǎn.", "ในความเห็นฉัน ควรเรียนช้ากว่านี้", "nai khwam-hen chan khuan rian cha kwa nee"],
      ["Có lẽ thử 15 phút mỗi ngày.", "Perhaps try 15 minutes a day.", "也许每天试十五分钟。", "yěxǔ měi tiān shì shíwǔ fēnzhōng.", "บางทีลองวันละสิบห้านาที", "bang-thee long wan la sip-ha na-thee"],
      ["Nếu mệt thì nghỉ.", "If you are tired, then rest.", "如果累了就休息。", "rúguǒ lèi le jiù xiūxi.", "ถ้าเหนื่อยก็พัก", "tha nueai ko phak"],
      ["Đừng nhồi quá nhiều từ một lúc.", "Don't cram too many words at once.", "不要一次塞太多词。", "bú yào yí cì sāi tài duō cí.", "อย่ายัดคำเยอะในครั้งเดียว", "ya yat kham yoe nai khrang diao"],
      ["Tránh học khi đang giận.", "Avoid studying when you are angry.", "生气时避免学习。", "shēngqì shí bìmiǎn xuéxí.", "เลี่ยงเรียนตอนกำลังโกรธ", "liang rian ton kam-lang krot"],
      ["Tốt hơn là nói thành câu.", "It is better to speak in sentences.", "说成句子更好。", "shuō chéng jùzi gèng hǎo.", "พูดเป็นประโยคดีกว่า", "phut pen pra-yok dee kwa"],
      ["Cân nhắc lịch của bạn.", "Consider your own schedule.", "考虑一下你的时间。", "kǎolǜ yíxià nǐ de shíjiān.", "คิดตารางของคุณให้ดี", "khit ta-rang khong khun hai dee"],
      ["Áp lực lớn không hữu ích.", "Heavy pressure is not useful.", "压力太大没有用。", "yālì tài dà méi yǒu yòng.", "ความกดดันมากไม่มีประโยชน์", "khwam kot-dan mak mai mee pra-yot"],
      ["Từ từ, bạn sẽ nhớ.", "Go slowly, you will remember.", "慢慢来，你会记得。", "mànmàn lái, nǐ huì jìde.", "ค่อยๆ ไป คุณจะจำได้", "khoi khoi pai khun ja jam dai"],
      ["Tùy bạn, đây chỉ là gợi ý.", "It is up to you; this is only a suggestion.", "随你，这只是建议。", "suí nǐ, zhè zhǐ shì jiànyì.", "แล้วแต่คุณ นี่แค่คำแนะนำ", "laeo tae khun nee khae kham nae-nam"],
      ["Kinh nghiệm mình: ngủ đủ rồi mới học.", "My experience: sleep enough, then study.", "我的经验是先睡够再学。", "wǒ de jīngyàn shì xiān shuì gòu zài xué.", "ประสบการณ์ฉัน: นอนพอแล้วค่อยเรียน", "pra-sop-kan chan non pho laeo khoi rian"],
      ["Cách này an toàn hơn.", "This way is safer.", "这样更安全。", "zhèyàng gèng ānquán.", "แบบนี้ปลอดภัยกว่า", "baep nee plot phai kwa"],
    ],
  ),
  unit(
    "plans",
    "B2",
    ["Kế hoạch", "Plans", "计划", "jìhuà", "แผน", "phaen"],
    ["Nói ý định, điều kiện, đổi lịch, và phương án B.", "Talk about intentions, conditions, changing plans, and a backup.", "说打算、条件、改期，以及备选方案。", "", "พูดความตั้งใจ เงื่อนไข เลื่อนนัด และแผนสำรอง", ""],
    [
      ["kế hoạch", "plan", "计划", "jìhuà", "แผน", "phaen"],
      ["dự định", "to intend", "打算", "dǎsuàn", "ตั้งใจจะ", "tang-jai ja"],
      ["sẽ", "will", "会", "huì", "จะ", "ja"],
      ["có thể", "might", "可能", "kěnéng", "อาจ", "at"],
      ["nếu", "if", "如果", "rúguǒ", "ถ้า", "tha"],
      ["trừ khi", "unless", "除非", "chúfēi", "เว้นแต่", "wen tae"],
      ["đổi lịch", "to reschedule", "改期", "gǎi qī", "เลื่อน", "luean"],
      ["hủy", "to cancel", "取消", "qǔxiāo", "ยกเลิก", "yok-loek"],
      ["chắc", "certain", "确定", "quèdìng", "แน่นอน", "nae-non"],
      ["linh hoạt", "flexible", "灵活", "línghuó", "ยืดหยุ่น", "yuet-yun"],
      ["phương án B", "plan B", "备选", "bèixuǎn", "แผนสำรอง", "phaen sam-rong"],
      ["trước mắt", "for now", "眼下", "yǎnxià", "ตอนนี้", "ton-nee"],
      ["về lâu dài", "in the long run", "长远", "chángyuǎn", "ระยะยาว", "ra-ya yao"],
      ["ưu tiên", "priority", "优先", "yōuxiān", "สิ่งสำคัญก่อน", "sing sam-khan kon"],
      ["thời hạn", "deadline", "期限", "qīxiàn", "กำหนด", "kam-not"],
      ["sắp xếp", "to arrange", "安排", "ānpái", "จัด", "jat"],
      ["còn tùy", "it depends", "看情况", "kàn qíngkuàng", "แล้วแต่สถานการณ์", "laeo tae sa-tha-na-kan"],
      ["sớm", "soon", "很快", "hěn kuài", "เร็วๆ นี้", "reo reo nee"],
      ["sau này", "later", "以后", "yǐhòu", "ทีหลัง", "thee lang"],
      ["cam kết", "to commit", "承诺", "chéngnuò", "สัญญา", "san-ya"],
    ],
    [
      ["Mình dự định đi tháng sau.", "I intend to go next month.", "我打算下个月去。", "wǒ dǎsuàn xià gè yuè qù.", "ฉันตั้งใจจะไปเดือนหน้า", "chan tang-jai ja pai duean na"],
      ["Nếu mưa thì mình đổi lịch.", "If it rains, I will reschedule.", "如果下雨，我就改期。", "rúguǒ xià yǔ, wǒ jiù gǎi qī.", "ถ้าฝนตก ฉันจะเลื่อน", "tha fon tok chan ja luean"],
      ["Chưa chắc, còn tùy việc.", "It is not certain; it depends on work.", "还不确定，看工作。", "hái bù quèdìng, kàn gōngzuò.", "ยังไม่แน่นอน แล้วแต่งาน", "yang mai nae-non laeo tae ngan"],
      ["Mình linh hoạt về giờ.", "I am flexible about the time.", "时间上我很灵活。", "shíjiān shàng wǒ hěn línghuó.", "เรื่องเวลาฉันยืดหยุ่น", "rueang we-la chan yuet-yun"],
      ["Cần một phương án B.", "We need a plan B.", "需要一个备选。", "xūyào yí gè bèixuǎn.", "ต้องมีแผนสำรอง", "tong mee phaen sam-rong"],
      ["Trước mắt học đều đã đủ.", "For now, studying steadily is enough.", "眼下先学得稳就够。", "yǎnxià xiān xué de wěn jiù gòu.", "ตอนนี้เรียนให้สม่ำเสมอก็พอ", "ton-nee rian hai sa-mam-sa-moe ko pho"],
      ["Về lâu dài mình muốn nói được.", "In the long run I want to be able to speak.", "长远我想能说出来。", "chángyuǎn wǒ xiǎng néng shuō chūlái.", "ระยะยาวฉันอยากพูดได้", "ra-ya yao chan yak phut dai"],
      ["Ưu tiên tuần này là ngủ đủ.", "This week's priority is enough sleep.", "这周优先把觉睡够。", "zhè zhōu yōuxiān bǎ jiào shuì gòu.", "สิ่งสำคัญสัปดาห์นี้คือนอนพอ", "sing sam-khan sap-da nee khue non pho"],
      ["Thời hạn là thứ Sáu.", "The deadline is Friday.", "期限是周五。", "qīxiàn shì zhōu wǔ.", "กำหนดคือวันศุกร์", "kam-not khue wan suk"],
      ["Mình sẽ sắp xếp lại.", "I will rearrange it.", "我会重新安排。", "wǒ huì chóngxīn ānpái.", "ฉันจะจัดใหม่", "chan ja jat mai"],
      ["Trừ khi bận gấp, mình không hủy.", "Unless something urgent comes up, I will not cancel.", "除非有急事，否则不取消。", "chúfēi yǒu jíshì, fǒuzé bù qǔxiāo.", "เว้นแต่เรื่องด่วน ฉันจะไม่ยกเลิก", "wen tae rueang duan chan ja mai yok-loek"],
      ["Sau này mình cam kết rõ hơn.", "Later I will commit more clearly.", "以后我会承诺得更清楚。", "yǐhòu wǒ huì chéngnuò de gèng qīngchǔ.", "ทีหลังฉันจะสัญญากับตัวเองให้ชัดกว่านี้", "thee lang chan ja san-ya kap tua-eng hai chat kwa nee"],
    ],
  ),
  unit(
    "relationships",
    "B2",
    ["Quan hệ", "Relationships", "人际关系", "rénjì guānxì", "ความสัมพันธ์", "khwam sam-phan"],
    ["Nói bạn bè, ranh giới, xin lỗi, và giữ hòa khí.", "Talk about friends, boundaries, apologies, and keeping the peace.", "说朋友、界限、道歉，以及维持和气。", "", "พูดเรื่องเพื่อน เส้นแบ่ง ขอโทษ และรักษาบรรยากาศ", ""],
    [
      ["bạn", "friend", "朋友", "péngyou", "เพื่อน", "phuean"],
      ["tin", "to trust", "信任", "xìnrèn", "ไว้ใจ", "wai-jai"],
      ["ranh giới", "boundary", "界限", "jièxiàn", "เส้นแบ่ง", "sen baeng"],
      ["tôn trọng", "to respect", "尊重", "zūnzhòng", "เคารพ", "khao-rop"],
      ["lắng nghe", "to listen", "倾听", "qīngtīng", "รับฟัง", "rap fang"],
      ["hiểu lầm", "misunderstanding", "误会", "wùhuì", "เข้าใจผิด", "khao-jai phit"],
      ["xin lỗi", "to apologise", "道歉", "dàoqiàn", "ขอโทษ", "kho-thot"],
      ["tha", "to forgive", "原谅", "yuánliàng", "ให้อภัย", "hai a-phai"],
      ["giận", "angry", "生气", "shēngqì", "โกรธ", "krot"],
      ["hòa", "peace", "和气", "héqì", "บรรยากาศดี", "ban-ya-kat dee"],
      ["giúp", "to help", "帮助", "bāngzhù", "ช่วย", "chuai"],
      ["khoảng cách", "distance", "距离", "jùlí", "ระยะห่าง", "ra-ya hang"],
      ["gần", "close", "亲近", "qīnjìn", "สนิท", "sa-nit"],
      ["cần thời gian", "need time", "需要时间", "xūyào shíjiān", "ต้องการเวลา", "tong-kan we-la"],
      ["nói thật", "to be honest", "说实话", "shuō shíhuà", "พูดจริง", "phut jing"],
      ["không tiện", "not convenient", "不方便", "bù fāngbiàn", "ไม่สะดวก", "mai sa-duak"],
      ["đừng ép", "don't push", "别勉强", "bié miǎnqiǎng", "อย่าบังคับ", "ya bang-khap"],
      ["cảm ơn", "thank you", "谢谢", "xièxie", "ขอบคุณ", "khop-khun"],
      ["quan tâm", "to care", "关心", "guānxīn", "ห่วงใย", "huang-yai"],
      ["im", "quiet / silent", "沉默", "chénmò", "เงียบ", "ngiap"],
    ],
    [
      ["Mình tin bạn.", "I trust you.", "我信任你。", "wǒ xìnrèn nǐ.", "ฉันไว้ใจคุณ", "chan wai-jai khun"],
      ["Có lẽ đây là hiểu lầm.", "This might be a misunderstanding.", "这也许是误会。", "zhè yěxǔ shì wùhuì.", "นี่อาจเป็นความเข้าใจผิด", "nee at pen khwam khao-jai phit"],
      ["Mình xin lỗi vì đã nói gấp.", "I am sorry I spoke too fast.", "抱歉我说得太急。", "bàoqiàn wǒ shuō de tài jí.", "ขอโทษที่พูดเร็วไป", "kho-thot thee phut reo pai"],
      ["Mình cần thời gian.", "I need some time.", "我需要一点时间。", "wǒ xūyào yìdiǎn shíjiān.", "ฉันต้องการเวลาสักหน่อย", "chan tong-kan we-la sak noi"],
      ["Ranh giới này quan trọng với mình.", "This boundary matters to me.", "这个界限对我很重要。", "zhège jièxiàn duì wǒ hěn zhòngyào.", "เส้นแบ่งนี้สำคัญกับฉัน", "sen baeng nee sam-khan kap chan"],
      ["Đừng ép mình trả lời ngay.", "Don't push me to answer at once.", "别勉强我马上回答。", "bié miǎnqiǎng wǒ mǎshàng huídá.", "อย่าบังคับให้ฉันตอบทันที", "ya bang-khap hai chan top than-thee"],
      ["Hôm nay mình không tiện nói.", "It is not convenient to talk today.", "今天不方便说。", "jīntiān bù fāngbiàn shuō.", "วันนี้พูดไม่สะดวก", "wan-nee phut mai sa-duak"],
      ["Mình vẫn quan tâm.", "I still care.", "我还是关心你。", "wǒ háishì ​guānxīn nǐ.", "ฉันยังห่วงใยอยู่", "chan yang huang-yai yu"],
      ["Lắng nghe đã, rồi hãy giận.", "Listen first, then be angry.", "先倾听，再生气。", "xiān qīngtīng, zài shēngqì.", "รับฟังก่อน แล้วค่อยโกรธ", "rap fang kon laeo khoi krot"],
      ["Khoảng cách một chút cũng được.", "A little distance is okay.", "有一点距离也可以。", "yǒu yìdiǎn jùlí yě kěyǐ.", "มีระยะห่างนิดหน่อยก็ได้", "mee ra-ya hang nit-noi ko dai"],
      ["Giữ hòa thì dễ thở hơn.", "Keeping the peace makes it easier to breathe.", "保持和气会好过一些。", "bǎochí héqì huì hǎoguò yìxiē.", "รักษาบรรยากาศดีจะหายใจง่ายกว่า", "rak-sa ban-ya-kat dee ja hai-jai ngai kwa"],
      ["Cảm ơn vì đã tha.", "Thank you for forgiving me.", "谢谢你原谅我。", "xièxie nǐ yuánliàng wǒ.", "ขอบคุณที่ให้อภัย", "khop-khun thee hai a-phai"],
    ],
  ),
  unit(
    "news",
    "B2",
    ["Tin tức đời sống", "Everyday news", "生活新闻", "shēnghuó xīnwén", "ข่าวในชีวิต", "khao nai chee-wit"],
    ["Nói tin ngắn, nguồn, nghi ngờ, và ý kiến nhẹ.", "Talk about a short news item, the source, doubt, and a mild view.", "说一则短新闻、来源、怀疑，以及温和看法。", "", "พูดข่าวสั้น แหล่งที่มา ความสงสัย และความเห็นเบาๆ", ""],
    [
      ["tin", "news", "新闻", "xīnwén", "ข่าว", "khao"],
      ["nguồn", "source", "来源", "láiyuán", "แหล่ง", "laeng"],
      ["đọc", "to read", "读到", "dú dào", "ได้อ่าน", "dai an"],
      ["nghe", "to hear", "听说", "tīngshuō", "ได้ยิน", "dai yin"],
      ["chia sẻ", "to share", "转发", "zhuǎnfā", "แชร์", "chae"],
      ["kiểm", "to check", "核实", "héshí", "ตรวจสอบ", "truat-sop"],
      ["nghi", "to doubt", "怀疑", "huáiyí", "สงสัย", "song-sai"],
      ["thật", "true", "真的", "zhēn de", "จริง", "jing"],
      ["sai lệch", "misleading", "不准确", "bù zhǔnquè", "คลาดเคลื่อน", "khlat-khluean"],
      ["ý kiến", "view", "看法", "kànfǎ", "ความเห็น", "khwam-hen"],
      ["ảnh hưởng", "to affect", "影响", "yǐngxiǎng", "ส่งผล", "song phon"],
      ["cộng đồng", "community", "社区", "shèqū", "ชุมชน", "chum-chon"],
      ["chính sách", "policy", "政策", "zhèngcè", "นโยบาย", "na-yo-bai"],
      ["giá", "prices", "物价", "wùjià", "ราคาสินค้า", "ra-kha sin-kha"],
      ["giao thông", "traffic", "交通", "jiāotōng", "จราจร", "ja-ra-jon"],
      ["thời tiết", "weather", "天气", "tiānqì", "อากาศ", "a-kat"],
      ["cập nhật", "update", "最新", "zuìxīn", "อัปเดต", "ap-det"],
      ["bình tĩnh", "calm", "冷静", "lěngjìng", "ใจเย็น", "jai-yen"],
      ["nói quá", "to exaggerate", "夸张", "kuāzhāng", "พูดเกิน", "phut koen"],
      ["cần thêm", "need more", "还需要", "hái xūyào", "ยังต้อง", "yang tong"],
    ],
    [
      ["Mình đọc một tin ngắn.", "I read a short news item.", "我读到一则短新闻。", "wǒ dú dào yì zé duǎn xīnwén.", "ฉันได้อ่านข่าวสั้น", "chan dai an khao san"],
      ["Nguồn chưa rõ.", "The source is not clear yet.", "来源还不清楚。", "láiyuán hái bù qīngchǔ.", "แหล่งที่มายังไม่ชัด", "laeng thee-ma yang mai chat"],
      ["Đừng chia sẻ khi chưa kiểm.", "Don't share before you check.", "没核实前不要转发。", "méi héshí qián bú yào zhuǎnfā.", "อย่าแชร์ก่อนตรวจสอบ", "ya chae kon truat-sop"],
      ["Mình hơi nghi.", "I rather doubt it.", "我有点怀疑。", "wǒ yǒudiǎn huáiyí.", "ฉันสงสัยนิดหน่อย", "chan song-sai nit-noi"],
      ["Có thể tin đang nói quá.", "The news might be exaggerating.", "这则新闻可能夸张了。", "zhè zé xīnwén kěnéng kuāzhāng le.", "ข่าวนี้อาจพูดเกิน", "khao nee at phut koen"],
      ["Giá đang ảnh hưởng tới chợ.", "Prices are affecting the market.", "物价在影响市场。", "wùjià zài yǐngxiǎng shìchǎng.", "ราคาส่งผลต่อตลาด", "ra-kha song phon tor ta-lat"],
      ["Giao thông hôm nay chậm.", "Traffic is slow today.", "今天交通很慢。", "jīntiān jiāotōng hěn màn.", "จราจรวันนี้ช้า", "ja-ra-jon wan-nee cha"],
      ["Cộng đồng cần thêm thông tin.", "The community needs more information.", "社区还需要更多信息。", "shèqū hái xūyào gèng duō xìnxī.", "ชุมชนยังต้องมีข้อมูลเพิ่ม", "chum-chon yang tong mee kho-mun phoem"],
      ["Chính sách này còn mới.", "This policy is still new.", "这个政策还新。", "zhège zhèngcè hái xīn.", "นโยบายนี้ยังใหม่", "na-yo-bai nee yang mai"],
      ["Mình giữ ý kiến nhẹ.", "I am keeping a mild view.", "我保持温和的看法。", "wǒ bǎochí wēnhé de kànfǎ.", "ฉันมีความเห็นแบบเบาๆ", "chan mee khwam-hen baep bao bao"],
      ["Hãy bình tĩnh đã.", "Stay calm first.", "先冷静。", "xiān lěngjìng.", "ใจเย็นก่อน", "jai-yen kon"],
      ["Cập nhật mới hơn chưa có.", "A newer update is not here yet.", "还没有更新的消息。", "hái méi yǒu gēngxīn de xiāoxi.", "ยังไม่มีอัปเดตใหม่กว่านี้", "yang mai mee ap-det mai kwa nee"],
    ],
  ),
  unit(
    "invitations",
    "A2",
    ["Mời và từ chối", "Invitations", "邀请和拒绝", "yāoqǐng hé jùjué", "การชวนและการปฏิเสธ", "kan chuan lae kan pa-ti-set"],
    ["Mời ai đó, nhận lời, hoặc từ chối nhẹ.", "Invite someone, accept, or decline gently.", "邀请、接受，或温和拒绝。", "", "ชวนคน รับคำ หรือปฏิเสธอย่างสุภาพ", ""],
    [
      ["mời", "to invite", "邀请", "yāoqǐng", "ชวน", "chuan"],
      ["đến", "to come", "来", "lái", "มา", "ma"],
      ["cùng", "together", "一起", "yìqǐ", "ด้วยกัน", "duai kan"],
      ["nhận lời", "to accept", "接受", "jiēshòu", "รับคำ", "rap kham"],
      ["từ chối", "to decline", "拒绝", "jùjué", "ปฏิเสธ", "pa-ti-set"],
      ["tiếc", "pity / unfortunately", "可惜", "kěxī", "น่าเสียดาย", "na sia-dai"],
      ["bận", "busy", "忙", "máng", "ไม่ว่าง", "mai wang"],
      ["lần sau", "next time", "下次", "xià cì", "ครั้งหน้า", "khrang na"],
      ["giờ", "time", "时间", "shíjiān", "เวลา", "we-la"],
      ["chỗ", "place", "地方", "dìfang", "ที่", "thee"],
      ["bao nhiêu người", "how many people", "几个人", "jǐ gè rén", "กี่คน", "kee khon"],
      ["mang gì", "what to bring", "带什么", "dài shénme", "เอาอะไรไป", "ao a-rai pai"],
      ["đúng giờ", "on time", "准时", "zhǔnshí", "ตรงเวลา", "trong we-la"],
      ["trễ", "late", "迟到", "chídào", "สาย", "sai"],
      ["vui", "fun", "开心", "kāixīn", "สนุก", "sa-nuk"],
      ["cảm ơn", "thank you", "谢谢", "xièxie", "ขอบคุณ", "khop-khun"],
      ["rất muốn", "would love to", "很想", "hěn xiǎng", "อยากมาก", "yak mak"],
      ["không được", "cannot", "去不了", "qù bù liǎo", "ไปไม่ได้", "pai mai dai"],
      ["hẹn", "to arrange", "约", "yuē", "นัด", "nat"],
      ["nhắn", "to message", "发信息", "fā xìnxī", "ส่งข้อความ", "song kho-khwam"],
    ],
    [
      ["Tối nay đến nhà mình nhé?", "Come to my place tonight?", "今晚来我家好吗？", "jīn wǎn lái wǒ jiā hǎo ma?", "คืนนี้มาบ้านฉันไหม", "khuen-nee ma ban chan mai"],
      ["Mình nhận lời.", "I accept.", "我接受。", "wǒ jiēshòu.", "ฉันรับคำ", "chan rap kham"],
      ["Tiếc quá, mình bận.", "What a pity, I am busy.", "可惜，我有事。", "kěxī, wǒ yǒu shì.", "น่าเสียดาย ฉันไม่ว่าง", "na sia-dai chan mai wang"],
      ["Lần sau mình đi.", "I will come next time.", "下次我去。", "xià cì wǒ qù.", "ครั้งหน้าฉันไป", "khrang na chan pai"],
      ["Bao nhiêu người vậy?", "How many people?", "几个人？", "jǐ gè rén?", "กี่คน", "kee khon"],
      ["Mang gì theo?", "What should I bring?", "要带什么？", "yào dài shénme?", "ต้องเอาอะไรไป", "tong ao a-rai pai"],
      ["Mình sẽ đúng giờ.", "I will be on time.", "我会准时。", "wǒ huì zhǔnshí.", "ฉันจะตรงเวลา", "chan ja trong we-la"],
      ["Nếu trễ mình nhắn.", "If I am late I will message.", "如果迟到我会发信息。", "rúguǒ chídào wǒ huì fā xìnxī.", "ถ้าสายฉันจะส่งข้อความ", "tha sai chan ja song kho-khwam"],
      ["Cảm ơn vì đã mời.", "Thank you for inviting me.", "谢谢你邀请我。", "xièxie nǐ yāoqǐng wǒ.", "ขอบคุณที่ชวน", "khop-khun thee chuan"],
      ["Mình rất muốn đi nhưng không được.", "I would love to go but I cannot.", "我很想去，但去不了。", "wǒ hěn xiǎng qù, dàn qù bù liǎo.", "ฉันอยากไปมากแต่ไปไม่ได้", "chan yak pai mak tae pai mai dai"],
      ["Hẹn chỗ yên một chút.", "Let's meet somewhere a bit quiet.", "约一个安静点的地方。", "yuē yí gè ānjìng diǎn de dìfang.", "นัดที่เงียบกว่านี้หน่อย", "nat thee ngiap kwa nee noi"],
      ["Sẽ vui lắm.", "It will be fun.", "会很开心。", "huì hěn kāixīn.", "จะสนุกมาก", "ja sa-nuk mak"],
    ],
  ),
];
