/** Linguistic bank for Linlin lessons. Original study material, not exam papers. */

export function row(vi, en, zh, py, th, rt) {
  return { vi, en, zh, py, th, rt };
}

export function unit(id, level, title, goal, vocab, sentences) {
  return {
    id,
    level,
    title: Array.isArray(title) ? row(...title) : title,
    goal: Array.isArray(goal) ? row(...goal) : goal,
    vocab: vocab.map((item) => (Array.isArray(item) ? row(...item) : item)),
    sentences: sentences.map((item) => (Array.isArray(item) ? row(...item) : item)),
  };
}

export const UNITS = [
  {
    id: "greet",
    level: "A1",
    title: row("Chào hỏi", "Greetings", "问候", "wènhòu", "ทักทาย", "thak-thai"),
    goal: row(
      "Chào, xưng tên, nói cảm ơn và xin lỗi.",
      "Greet, say your name, thank and apologise.",
      "打招呼、报名字、说谢谢和对不起。",
      "",
      "ทักทาย บอกชื่อ ขอบคุณ และขอโทษ",
      "",
    ),
    vocab: [
      row("xin chào", "hello", "你好", "nǐ hǎo", "สวัสดี", "sa-wat-dee"),
      row("tạm biệt", "goodbye", "再见", "zàijiàn", "ลาก่อน", "la-gon"),
      row("cảm ơn", "thank you", "谢谢", "xièxie", "ขอบคุณ", "khop-khun"),
      row("xin lỗi", "sorry", "对不起", "duìbuqǐ", "ขอโทษ", "kho-thot"),
      row("tôi", "I", "我", "wǒ", "ฉัน", "chan"),
      row("bạn", "you", "你", "nǐ", "คุณ", "khun"),
      row("tên", "name", "名字", "míngzi", "ชื่อ", "chue"),
      row("rất vui", "nice to meet you", "很高兴认识你", "hěn gāoxìng rènshi nǐ", "ยินดีที่ได้รู้จัก", "yin-dee thee dai ru-jak"),
      row("vâng", "yes", "是", "shì", "ครับ / ค่ะ", "khrap / kha"),
      row("không", "no", "不", "bù", "ไม่", "mai"),
      row("làm ơn", "please", "请", "qǐng", "ได้โปรด", "dai-prot"),
      row("không sao", "it's okay", "没关系", "méi guānxi", "ไม่เป็นไร", "mai-pen-rai"),
      row("bạn khỏe không", "how are you", "你好吗", "nǐ hǎo ma", "สบายดีไหม", "sa-bai-dee-mai"),
      row("khỏe", "fine", "很好", "hěn hǎo", "สบายดี", "sa-bai-dee"),
      row("tôi là", "I am", "我是", "wǒ shì", "ฉันคือ", "chan khue"),
      row("cô", "Ms", "女士", "nǚshì", "คุณผู้หญิง", "khun phu-ying"),
      row("anh", "Mr", "先生", "xiānsheng", "คุณผู้ชาย", "khun phu-chai"),
      row("người mới", "beginner", "初学者", "chūxuézhě", "มือใหม่", "mue-mai"),
      row("gặp lại", "see you", "回头见", "huí tóu jiàn", "แล้วพบกัน", "laeo phop kan"),
      row("chào buổi sáng", "good morning", "早上好", "zǎoshang hǎo", "อรุณสวัสดิ์", "a-run sa-wat"),
    ],
    sentences: [
      row("Xin chào, tôi là Lan.", "Hello, I am Lan.", "你好，我是兰。", "nǐ hǎo, wǒ shì Lán.", "สวัสดี ฉันคือลาน", "sa-wat-dee chan khue Lan"),
      row("Tên bạn là gì?", "What is your name?", "你叫什么名字？", "nǐ jiào shénme míngzi?", "คุณชื่ออะไร", "khun chue a-rai"),
      row("Rất vui được gặp bạn.", "Nice to meet you.", "很高兴认识你。", "hěn gāoxìng rènshi nǐ.", "ยินดีที่ได้รู้จัก", "yin-dee thee dai ru-jak"),
      row("Cảm ơn bạn nhiều.", "Thank you so much.", "非常感谢你。", "fēicháng gǎnxiè nǐ.", "ขอบคุณมาก", "khop-khun mak"),
      row("Xin lỗi, mình đến trễ.", "Sorry, I am late.", "对不起，我迟到了。", "duìbuqǐ, wǒ chídào le.", "ขอโทษ ฉันมาสาย", "kho-thot chan ma sai"),
      row("Không sao.", "It's okay.", "没关系。", "méi guānxi.", "ไม่เป็นไร", "mai-pen-rai"),
      row("Bạn khỏe không?", "How are you?", "你好吗？", "nǐ hǎo ma?", "สบายดีไหม", "sa-bai-dee-mai"),
      row("Mình khỏe, cảm ơn.", "I am fine, thank you.", "我很好，谢谢。", "wǒ hěn hǎo, xièxie.", "ฉันสบายดี ขอบคุณ", "chan sa-bai-dee khop-khun"),
      row("Chào buổi sáng.", "Good morning.", "早上好。", "zǎoshang hǎo.", "อรุณสวัสดิ์", "a-run sa-wat"),
      row("Tạm biệt, gặp lại mai.", "Goodbye, see you tomorrow.", "再见，明天见。", "zàijiàn, míngtiān jiàn.", "ลาก่อน พรุ่งนี้เจอกัน", "la-gon phrung-nee joe kan"),
      row("Làm ơn nói chậm.", "Please speak slowly.", "请说慢一点。", "qǐng shuō màn yìdiǎn.", "ได้โปรดพูดช้าๆ", "dai-prot phut cha-cha"),
      row("Mình là người mới.", "I am a beginner.", "我是初学者。", "wǒ shì chūxuézhě.", "ฉันเป็นมือใหม่", "chan pen mue-mai"),
    ],
  },
  {
    id: "numbers",
    level: "A1",
    title: row("Số đếm", "Numbers", "数字", "shùzì", "ตัวเลข", "tua-lek"),
    goal: row("Đếm, hỏi số lượng, nói giá đơn giản.", "Count, ask how many, say a simple price.", "数数、问数量、说简单价格。", "", "นับ ถามจำนวน พูดราคาแบบง่าย", ""),
    vocab: [
      row("một", "one", "一", "yī", "หนึ่ง", "nueng"),
      row("hai", "two", "二", "èr", "สอง", "song"),
      row("ba", "three", "三", "sān", "สาม", "sam"),
      row("bốn", "four", "四", "sì", "สี่", "see"),
      row("năm", "five", "五", "wǔ", "ห้า", "ha"),
      row("sáu", "six", "六", "liù", "หก", "hok"),
      row("bảy", "seven", "七", "qī", "เจ็ด", "jet"),
      row("tám", "eight", "八", "bā", "แปด", "paet"),
      row("chín", "nine", "九", "jiǔ", "เก้า", "kao"),
      row("mười", "ten", "十", "shí", "สิบ", "sip"),
      row("không", "zero", "零", "líng", "ศูนย์", "sun"),
      row("bao nhiêu", "how many", "多少", "duōshǎo", "เท่าไหร่", "thao-rai"),
      row("số", "number", "号码", "hàomǎ", "หมายเลข", "mai-lek"),
      row("giá", "price", "价格", "jiàgé", "ราคา", "ra-kha"),
      row("tiền", "money", "钱", "qián", "เงิน", "ngoen"),
      row("rẻ", "cheap", "便宜", "piányi", "ถูก", "thuk"),
      row("đắt", "expensive", "贵", "guì", "แพง", "phaeng"),
      row("nửa", "half", "半", "bàn", "ครึ่ง", "khrueng"),
      row("ít", "a little", "一点", "yìdiǎn", "นิดหน่อย", "nit-noi"),
      row("nhiều", "a lot", "很多", "hěn duō", "เยอะ", "yoe"),
    ],
    sentences: [
      row("Cho mình hai cái.", "Two, please.", "请给我两个。", "qǐng gěi wǒ liǎng gè.", "ขอสองอัน", "kho song an"),
      row("Bao nhiêu tiền?", "How much is it?", "多少钱？", "duōshǎo qián?", "เท่าไหร่", "thao-rai"),
      row("Mười nghìn.", "Ten thousand.", "一万。", "yí wàn.", "หนึ่งหมื่น", "nueng muen"),
      row("Hơi đắt.", "A bit expensive.", "有点贵。", "yǒudiǎn guì.", "แพงไปนิด", "phaeng pai nit"),
      row("Rẻ hơn được không?", "Can it be cheaper?", "能便宜一点吗？", "néng piányi yìdiǎn ma?", "ลดได้ไหม", "lot dai mai"),
      row("Mình lấy ba.", "I'll take three.", "我要三个。", "wǒ yào sān gè.", "ฉันเอาสาม", "chan ao sam"),
      row("Số điện thoại của bạn?", "What is your number?", "你的电话号码是多少？", "nǐ de diànhuà hàomǎ shì duōshǎo?", "เบอร์คุณคืออะไร", "boe khun khue a-rai"),
      row("Một nửa thôi.", "Just half.", "只要一半。", "zhǐ yào yí bàn.", "แค่ครึ่งเดียว", "khae khrueng diao"),
      row("Ít thôi, cảm ơn.", "Just a little, thanks.", "只要一点，谢谢。", "zhǐ yào yìdiǎn, xièxie.", "นิดหน่อยพอ ขอบคุณ", "nit-noi pho khop-khun"),
      row("Có nhiều không?", "Are there many?", "有很多吗？", "yǒu hěn duō ma?", "มีเยอะไหม", "mee yoe mai"),
      row("Năm người.", "Five people.", "五个人。", "wǔ gè rén.", "ห้าคน", "ha khon"),
      row("Số mười.", "Number ten.", "十号。", "shí hào.", "หมายเลขสิบ", "mai-lek sip"),
    ],
  },
  {
    id: "time",
    level: "A1",
    title: row("Giờ và ngày", "Time and days", "时间和日子", "shíjiān hé rìzi", "เวลาและวัน", "we-la lae wan"),
    goal: row("Nói giờ, hôm nay, ngày mai, và hẹn giờ.", "Say the time, today, tomorrow, and make a time.", "说时间、今天、明天，并约定时间。", "", "พูดเวลา วันนี้ พรุ่งนี้ และนัดเวลา", ""),
    vocab: [
      row("giờ", "hour", "点", "diǎn", "โมง", "mong"),
      row("phút", "minute", "分", "fēn", "นาที", "na-thee"),
      row("bây giờ", "now", "现在", "xiànzài", "ตอนนี้", "ton-nee"),
      row("hôm nay", "today", "今天", "jīntiān", "วันนี้", "wan-nee"),
      row("ngày mai", "tomorrow", "明天", "míngtiān", "พรุ่งนี้", "phrung-nee"),
      row("hôm qua", "yesterday", "昨天", "zuótiān", "เมื่อวาน", "muea-wan"),
      row("sáng", "morning", "早上", "zǎoshang", "เช้า", "chao"),
      row("chiều", "afternoon", "下午", "xiàwǔ", "บ่าย", "bai"),
      row("tối", "evening", "晚上", "wǎnshang", "เย็น", "yen"),
      row("đêm", "night", "夜里", "yèli", "กลางคืน", "klang-khuen"),
      row("tuần", "week", "星期", "xīngqī", "สัปดาห์", "sap-da"),
      row("tháng", "month", "月", "yuè", "เดือน", "duean"),
      row("năm", "year", "年", "nián", "ปี", "pee"),
      row("muộn", "late", "晚", "wǎn", "สาย", "sai"),
      row("sớm", "early", "早", "zǎo", "เช้า / เร็ว", "chao / reo"),
      row("hẹn", "appointment", "约会", "yuēhuì", "นัด", "nat"),
      row("mấy giờ", "what time", "几点", "jǐ diǎn", "กี่โมง", "kee-mong"),
      row("cuối tuần", "weekend", "周末", "zhōumò", "สุดสัปดาห์", "sut sap-da"),
      row("đợi", "wait", "等", "děng", "รอ", "ro"),
      row("xong", "done", "完了", "wán le", "เสร็จ", "set"),
    ],
    sentences: [
      row("Bây giờ mấy giờ?", "What time is it now?", "现在几点？", "xiànzài jǐ diǎn?", "ตอนนี้กี่โมง", "ton-nee kee-mong"),
      row("Bảy giờ sáng.", "Seven in the morning.", "早上七点。", "zǎoshang qī diǎn.", "เจ็ดโมงเช้า", "jet mong chao"),
      row("Hẹn bảy giờ được không?", "Is seven okay?", "七点可以吗？", "qī diǎn kěyǐ ma?", "เจ็ดโมงได้ไหม", "jet mong dai mai"),
      row("Hôm nay mình bận.", "I am busy today.", "今天我很忙。", "jīntiān wǒ hěn máng.", "วันนี้ฉันไม่ว่าง", "wan-nee chan mai wang"),
      row("Mai gặp lại.", "See you tomorrow.", "明天见。", "míngtiān jiàn.", "พรุ่งนี้เจอกัน", "phrung-nee joe kan"),
      row("Mình đến trễ một chút.", "I will be a little late.", "我会晚一点。", "wǒ huì wǎn yìdiǎn.", "ฉันจะสายนิดหน่อย", "chan ja sai nit-noi"),
      row("Cuối tuần rảnh không?", "Are you free this weekend?", "这个周末有空吗？", "zhège zhōumò yǒu kòng ma?", "สุดสัปดาห์ว่างไหม", "sut sap-da wang mai"),
      row("Đợi mình năm phút.", "Wait five minutes.", "等我五分钟。", "děng wǒ wǔ fēnzhōng.", "รอฉันห้านาที", "ro chan ha na-thee"),
      row("Sáng nay mình dậy sớm.", "I got up early this morning.", "今天早上我起得很早。", "jīntiān zǎoshang wǒ qǐ de hěn zǎo.", "เช้านี้ฉันตื่นเร็ว", "chao-nee chan tuen reo"),
      row("Tối nay học 15 phút.", "Tonight, study 15 minutes.", "今晚学习十五分钟。", "jīn wǎn xuéxí shíwǔ fēnzhōng.", "คืนนี้เรียนสิบห้านาที", "khuen-nee rian sip-ha na-thee"),
      row("Hôm qua mình quên.", "I forgot yesterday.", "昨天我忘了。", "zuótiān wǒ wàng le.", "เมื่อวานฉันลืม", "muea-wan chan luem"),
      row("Xong rồi.", "It's done.", "做完了。", "zuò wán le.", "เสร็จแล้ว", "set laeo"),
    ],
  },
  {
    id: "cafe",
    level: "A1",
    title: row("Quán cà phê", "Café", "咖啡馆", "kāfēiguǎn", "คาเฟ่", "ka-fe"),
    goal: row("Xin bàn, gọi đồ uống, thêm đường.", "Ask for a table, order a drink, extra sugar.", "要桌子、点饮料、加糖。", "", "ขอโต๊ะ สั่งเครื่องดื่ม ขอน้ำตาล", ""),
    vocab: [
      row("quán", "café", "咖啡馆", "kāfēiguǎn", "ร้านกาแฟ", "ran ka-fae"),
      row("bàn", "table", "桌子", "zhuōzi", "โต๊ะ", "to"),
      row("ghế", "chair", "椅子", "yǐzi", "เก้าอี้", "kao-ee"),
      row("cà phê", "coffee", "咖啡", "kāfēi", "กาแฟ", "ka-fae"),
      row("trà", "tea", "茶", "chá", "ชา", "cha"),
      row("nước", "water", "水", "shuǐ", "น้ำ", "nam"),
      row("sữa", "milk", "牛奶", "niúnǎi", "นม", "nom"),
      row("đường", "sugar", "糖", "táng", "น้ำตาล", "nam-tan"),
      row("ly", "cup", "杯", "bēi", "แก้ว", "kaew"),
      row("menu", "menu", "菜单", "càidān", "เมนู", "me-nu"),
      row("gọi", "to order", "点", "diǎn", "สั่ง", "sang"),
      row("thêm", "extra", "加", "jiā", "เพิ่ม", "phoem"),
      row("nóng", "hot", "热", "rè", "ร้อน", "ron"),
      row("đá", "ice", "冰", "bīng", "เย็น", "yen"),
      row("ngon", "delicious", "好吃", "hǎochī", "อร่อย", "a-roi"),
      row("thanh toán", "to pay", "买单", "mǎidān", "คิดเงิน", "khit-ngoen"),
      row("tiền tip", "tip", "小费", "xiǎofèi", "ทิป", "thip"),
      row("chỗ ngồi", "seat", "座位", "zuòwèi", "ที่นั่ง", "thee-nang"),
      row("cửa sổ", "window", "窗户", "chuānghu", "หน้าต่าง", "na-tang"),
      row("mang đi", "takeaway", "外带", "wàidài", "ใส่ถุงกลับ", "sai thung klap"),
    ],
    sentences: [
      row("Xin một bàn cho hai người.", "A table for two, please.", "请给我一张两人桌。", "qǐng gěi wǒ yì zhāng liǎng rén zhuō.", "ขอโต๊ะสำหรับสองคน", "kho to sam-rap song khon"),
      row("Cho mình một ly trà.", "A tea, please.", "请给我一杯茶。", "qǐng gěi wǒ yì bēi chá.", "ขอชาหนึ่งแก้ว", "kho cha nueng kaew"),
      row("Cà phê đá, ít đường.", "Iced coffee, little sugar.", "冰咖啡，少糖。", "bīng kāfēi, shǎo táng.", "กาแฟเย็น น้ำตาลน้อย", "ka-fae yen nam-tan noi"),
      row("Thêm sữa được không?", "Can I have milk?", "可以加牛奶吗？", "kěyǐ jiā niúnǎi ma?", "ใส่นมได้ไหม", "sai nom dai mai"),
      row("Cho mình xem menu.", "The menu, please.", "请给我菜单。", "qǐng gěi wǒ càidān.", "ขอเมนูหน่อย", "kho me-nu noi"),
      row("Ngồi cạnh cửa sổ được không?", "A window seat, please?", "可以坐靠窗吗？", "kěyǐ zuò kào chuāng ma?", "ขอที่นั่งริมหน้าต่างได้ไหม", "kho thee-nang rim na-tang dai mai"),
      row("Mang đi, cảm ơn.", "Takeaway, please.", "外带，谢谢。", "wàidài, xièxie.", "ใส่ถุงกลับ ขอบคุณ", "sai thung klap khop-khun"),
      row("Thanh toán giúp mình.", "The bill, please.", "买单。", "mǎidān.", "คิดเงินด้วย", "khit-ngoen duai"),
      row("Ngon lắm.", "It's delicious.", "很好喝。", "hěn hǎo hē.", "อร่อยมาก", "a-roi mak"),
      row("Cho mình ly nước.", "A glass of water, please.", "请给我一杯水。", "qǐng gěi wǒ yì bēi shuǐ.", "ขอน้ำหนึ่งแก้ว", "kho nam nueng kaew"),
      row("Nóng hay đá?", "Hot or iced?", "热的还是冰的？", "rè de háishì bīng de?", "ร้อนหรือเย็น", "ron rue yen"),
      row("Mình ngồi đây được không?", "Can I sit here?", "我可以坐这里吗？", "wǒ kěyǐ zuò zhèlǐ ma?", "ฉันนั่งตรงนี้ได้ไหม", "chan nang trong nee dai mai"),
    ],
  },
  {
    id: "food",
    level: "A2",
    title: row("Ăn uống", "Food", "饮食", "yǐnshí", "อาหาร", "a-han"),
    goal: row("Gọi món, nói khẩu vị, xin thêm.", "Order food, say taste, ask for more.", "点菜、说口味、再要一份。", "", "สั่งอาหาร บอกรส ขอเพิ่ม", ""),
    vocab: [
      row("cơm", "rice", "米饭", "mǐfàn", "ข้าว", "khao"),
      row("phở", "noodle soup", "河粉", "héfěn", "ก๋วยเตี๋ยว", "kuai-tiao"),
      row("bánh", "bread / cake", "面包", "miànbāo", "ขนมปัง", "khanom-pang"),
      row("rau", "vegetables", "蔬菜", "shūcài", "ผัก", "phak"),
      row("thịt", "meat", "肉", "ròu", "เนื้อ", "nuea"),
      row("cá", "fish", "鱼", "yú", "ปลา", "pla"),
      row("trứng", "egg", "鸡蛋", "jīdàn", "ไข่", "khai"),
      row("cay", "spicy", "辣", "là", "เผ็ด", "phet"),
      row("ngọt", "sweet", "甜", "tián", "หวาน", "wan"),
      row("mặn", "salty", "咸", "xián", "เค็ม", "khem"),
      row("chua", "sour", "酸", "suān", "เปรี้ยว", "priao"),
      row("đói", "hungry", "饿", "è", "หิว", "hiu"),
      row("khát", "thirsty", "渴", "kě", "กระหาย", "kra-hai"),
      row("ăn", "to eat", "吃", "chī", "กิน", "kin"),
      row("uống", "to drink", "喝", "hē", "ดื่ม", "duem"),
      row("no", "full", "饱", "bǎo", "อิ่ม", "im"),
      row("chay", "vegetarian", "素", "sù", "มังสวิรัติ", "mang-sa-wi-rat"),
      row("dị ứng", "allergy", "过敏", "guòmǐn", "แพ้", "phae"),
      row("ngon miệng", "enjoy your meal", "请慢用", "qǐng màn yòng", "ทานให้อร่อย", "than hai a-roi"),
      row("thêm một phần", "one more", "再来一份", "zài lái yí fèn", "ขออีกจาน", "kho ik jan"),
    ],
    sentences: [
      row("Mình đói rồi.", "I am hungry.", "我饿了。", "wǒ è le.", "ฉันหิวแล้ว", "chan hiu laeo"),
      row("Cho mình một tô phở.", "A bowl of pho, please.", "请给我一碗河粉。", "qǐng gěi wǒ yì wǎn héfěn.", "ขอก๋วยเตี๋ยวหนึ่งชาม", "kho kuai-tiao nueng cham"),
      row("Không cay.", "Not spicy.", "不要辣。", "bú yào là.", "ไม่เผ็ด", "mai phet"),
      row("Hơi ngọt.", "A bit sweet.", "有点甜。", "yǒudiǎn tián.", "หวานไปนิด", "wan pai nit"),
      row("Mình ăn chay.", "I am vegetarian.", "我吃素。", "wǒ chī sù.", "ฉันกินมังสวิรัติ", "chan kin mang-sa-wi-rat"),
      row("Mình dị ứng hải sản.", "I am allergic to seafood.", "我对海鲜过敏。", "wǒ duì hǎixiān guòmǐn.", "ฉันแพ้อาหารทะเล", "chan phae a-han tha-le"),
      row("Thêm cơm được không?", "More rice, please?", "可以再来米饭吗？", "kěyǐ zài lái mǐfàn ma?", "ขอข้าวเพิ่มได้ไหม", "kho khao phoem dai mai"),
      row("Mình no rồi, cảm ơn.", "I am full, thank you.", "我吃饱了，谢谢。", "wǒ chī bǎo le, xièxie.", "ฉันอิ่มแล้ว ขอบคุณ", "chan im laeo khop-khun"),
      row("Cho mình cá và rau.", "Fish and vegetables, please.", "请给我鱼和蔬菜。", "qǐng gěi wǒ yú hé shūcài.", "ขอปลากับผัก", "kho pla kap phak"),
      row("Uống gì?", "What would you like to drink?", "喝什么？", "hē shénme?", "ดื่มอะไร", "duem a-rai"),
      row("Ngon miệng.", "Enjoy the meal.", "请慢用。", "qǐng màn yòng.", "ทานให้อร่อย", "than hai a-roi"),
      row("Thêm một phần.", "One more portion.", "再来一份。", "zài lái yí fèn.", "ขออีกจาน", "kho ik jan"),
    ],
  },
  {
    id: "market",
    level: "A2",
    title: row("Chợ", "Market", "市场", "shìchǎng", "ตลาด", "ta-lat"),
    goal: row("Hỏi còn hàng, hỏi giá, xin túi.", "Ask if it is left, ask the price, take a bag.", "问还有没有、问价、拿袋子。", "", "ถามว่ายังมีไหม ถามราคา รับถุง", ""),
    vocab: [
      row("chợ", "market", "市场", "shìchǎng", "ตลาด", "ta-lat"),
      row("còn", "still have", "还有", "hái yǒu", "ยังมี", "yang mee"),
      row("hết", "sold out", "卖完了", "mài wán le", "หมด", "mot"),
      row("túi", "bag", "袋子", "dàizi", "ถุง", "thung"),
      row("cân", "kilo", "公斤", "gōngjīn", "กิโล", "ki-lo"),
      row("trái", "fruit", "水果", "shuǐguǒ", "ผลไม้", "phon-la-mai"),
      row("cam", "orange", "橙子", "chéngzi", "ส้ม", "som"),
      row("táo", "apple", "苹果", "píngguǒ", "แอปเปิล", "aep-poen"),
      row("chuối", "banana", "香蕉", "xiāngjiāo", "กล้วย", "kluai"),
      row("gạo", "rice grain", "大米", "dàmǐ", "ข้าวสาร", "khao-san"),
      row("bớt", "discount", "便宜点", "piányi diǎn", "ลด", "lot"),
      row("lấy", "I'll take", "要", "yào", "เอา", "ao"),
      row("thử", "to try", "试试", "shìshi", "ลอง", "long"),
      row("tươi", "fresh", "新鲜", "xīnxiān", "สด", "sot"),
      row("gian hàng", "stall", "摊位", "tānwèi", "แผง", "phaeng"),
      row("đổi", "change (money)", "找钱", "zhǎo qián", "เงินทอน", "ngoen thon"),
      row("tiền lẻ", "small change", "零钱", "língqián", "เงินย่อย", "ngoen yoi"),
      row("nặng", "heavy", "重", "zhòng", "หนัก", "nak"),
      row("nhẹ", "light", "轻", "qīng", "เบา", "bao"),
      row("chín", "ripe", "熟", "shú", "สุก", "suk"),
    ],
    sentences: [
      row("Còn cam không?", "Do you still have oranges?", "还有橙子吗？", "hái yǒu chéngzi ma?", "ยังมีส้มไหม", "yang mee som mai"),
      row("Hết rồi.", "Sold out.", "卖完了。", "mài wán le.", "หมดแล้ว", "mot laeo"),
      row("Một cân bao nhiêu?", "How much for a kilo?", "一公斤多少钱？", "yì gōngjīn duōshǎo qián?", "กิโลละเท่าไหร่", "ki-lo la thao-rai"),
      row("Bớt một chút được không?", "A little cheaper?", "能便宜一点吗？", "néng piányi yìdiǎn ma?", "ลดหน่อยได้ไหม", "lot noi dai mai"),
      row("Mình lấy hai cân.", "I'll take two kilos.", "我要两公斤。", "wǒ yào liǎng gōngjīn.", "ฉันเอาสองกิโล", "chan ao song ki-lo"),
      row("Cho mình một túi.", "A bag, please.", "请给我一个袋子。", "qǐng gěi wǒ yí gè dàizi.", "ขอถุงหนึ่งใบ", "kho thung nueng bai"),
      row("Tươi không?", "Is it fresh?", "新鲜吗？", "xīnxiān ma?", "สดไหม", "sot mai"),
      row("Thử một miếng được không?", "Can I try a piece?", "可以尝一块吗？", "kěyǐ cháng yí kuài ma?", "ลองคำได้ไหม", "long kham dai mai"),
      row("Tiền lẻ đây.", "Here's the change.", "这是零钱。", "zhè shì língqián.", "นี่เงินทอน", "nee ngoen thon"),
      row("Nặng quá.", "Too heavy.", "太重了。", "tài zhòng le.", "หนักเกินไป", "nak goin pai"),
      row("Chín rồi.", "It's ripe.", "熟了。", "shú le.", "สุกแล้ว", "suk laeo"),
      row("Cảm ơn, mình lấy cái này.", "Thanks, I'll take this.", "谢谢，我要这个。", "xièxie, wǒ yào zhège.", "ขอบคุณ ฉันเอาอันนี้", "khop-khun chan ao an nee"),
    ],
  },
  {
    id: "home",
    level: "A2",
    title: row("Nhà cửa", "Home", "家", "jiā", "บ้าน", "ban"),
    goal: row("Tên phòng, đồ trong nhà, lời mời vào.", "Name rooms, things at home, invite someone in.", "房间、家里的东西、请进。", "", "ชื่อห้อง ของในบ้าน เชิญเข้ามา", ""),
    vocab: [
      row("nhà", "house", "家", "jiā", "บ้าน", "ban"),
      row("cửa", "door", "门", "mén", "ประตู", "pra-tu"),
      row("phòng", "room", "房间", "fángjiān", "ห้อง", "hong"),
      row("bếp", "kitchen", "厨房", "chúfáng", "ครัว", "khrua"),
      row("phòng ngủ", "bedroom", "卧室", "wòshì", "ห้องนอน", "hong-non"),
      row("nhà tắm", "bathroom", "卫生间", "wèishēngjiān", "ห้องน้ำ", "hong-nam"),
      row("giường", "bed", "床", "chuáng", "เตียง", "tiang"),
      row("bàn", "desk", "桌子", "zhuōzi", "โต๊ะ", "to"),
      row("đèn", "lamp", "灯", "dēng", "ไฟ", "fai"),
      row("chìa khóa", "key", "钥匙", "yàoshi", "กุญแจ", "kun-jae"),
      row("nước", "water", "水", "shuǐ", "น้ำ", "nam"),
      row("điện", "electricity", "电", "diàn", "ไฟฟ้า", "fai-fa"),
      row("sạch", "clean", "干净", "gānjìng", "สะอาด", "sa-at"),
      row("bẩn", "dirty", "脏", "zāng", "สกปรก", "sok-ka-prok"),
      row("mở", "open", "开", "kāi", "เปิด", "poet"),
      row("đóng", "close", "关", "guān", "ปิด", "pit"),
      row("ngồi", "sit", "坐", "zuò", "นั่ง", "nang"),
      row("vào", "come in", "进来", "jìnlái", "เข้ามา", "khao ma"),
      row("ở", "to live", "住", "zhù", "อยู่", "yu"),
      row("thuê", "to rent", "租", "zū", "เช่า", "chao"),
    ],
    sentences: [
      row("Mời vào nhà.", "Please come in.", "请进。", "qǐng jìn.", "เชิญเข้ามา", "choen khao ma"),
      row("Nhà tắm ở bên phải.", "The bathroom is on the right.", "卫生间在右边。", "wèishēngjiān zài yòubiān.", "ห้องน้ำอยู่ทางขวา", "hong-nam yu thang khwa"),
      row("Đóng cửa giúp mình.", "Please close the door.", "请关门。", "qǐng guān mén.", "ช่วยปิดประตูหน่อย", "chuai pit pra-tu noi"),
      row("Mình quên chìa khóa.", "I forgot the key.", "我忘了钥匙。", "wǒ wàng le yàoshi.", "ฉันลืมกุญแจ", "chan luem kun-jae"),
      row("Bật đèn được không?", "Can you turn on the light?", "能开灯吗？", "néng kāi dēng ma?", "เปิดไฟได้ไหม", "poet fai dai mai"),
      row("Phòng này sạch.", "This room is clean.", "这个房间很干净。", "zhège fángjiān hěn gānjìng.", "ห้องนี้สะอาด", "hong nee sa-at"),
      row("Mình ở đây.", "I live here.", "我住在这里。", "wǒ zhù zài zhèlǐ.", "ฉันอยู่ที่นี่", "chan yu thee nee"),
      row("Bếp nhỏ nhưng đủ.", "The kitchen is small but enough.", "厨房小，但够用。", "chúfáng xiǎo, dàn gòu yòng.", "ครัวเล็กแต่พอใช้", "khrua lek tae pho chai"),
      row("Ngồi đi.", "Have a seat.", "请坐。", "qǐng zuò.", "นั่งสิ", "nang si"),
      row("Nhà đang thuê.", "The house is rented.", "房子是租的。", "fángzi shì zū de.", "บ้านเช่าอยู่", "ban chao yu"),
      row("Mở cửa sổ.", "Open the window.", "打开窗户。", "dǎkāi chuānghu.", "เปิดหน้าต่าง", "poet na-tang"),
      row("Điện cắt rồi.", "The power is out.", "停电了。", "tíngdiàn le.", "ไฟดับ", "fai dap"),
    ],
  },
  {
    id: "messages",
    level: "A2",
    title: row("Tin nhắn", "Messages", "短信", "duǎnxìn", "ข้อความ", "kho-khwam"),
    goal: row("Xin lỗi vì trễ, hẹn giờ, gửi vị trí.", "Apologise for being late, set a time, send a pin.", "为迟到道歉、约时间、发定位。", "", "ขอโทษที่สาย นัดเวลา ส่งพิกัด", ""),
    vocab: [
      row("tin nhắn", "message", "短信", "duǎnxìn", "ข้อความ", "kho-khwam"),
      row("gửi", "to send", "发", "fā", "ส่ง", "song"),
      row("nhận", "to receive", "收到", "shōudào", "ได้รับ", "dai rap"),
      row("gọi điện", "to call", "打电话", "dǎ diànhuà", "โทร", "tho"),
      row("mạng", "network / wifi", "网络", "wǎngluò", "เน็ต", "net"),
      row("vị trí", "location", "位置", "wèizhì", "พิกัด", "phi-kat"),
      row("ảnh", "photo", "照片", "zhàopiàn", "รูป", "rup"),
      row("chờ", "wait", "等", "děng", "รอ", "ro"),
      row("ok", "okay", "好的", "hǎo de", "โอเค", "o-khe"),
      row("mai", "tomorrow", "明天", "míngtiān", "พรุ่งนี้", "phrung-nee"),
      row("trễ", "late", "迟到", "chídào", "สาย", "sai"),
      row("hẹn", "to meet", "见面", "jiànmiàn", "นัดเจอ", "nat joe"),
      row("đến", "to arrive", "到", "dào", "ถึง", "thueng"),
      row("đi", "to go", "去", "qù", "ไป", "pai"),
      row("ở đâu", "where", "在哪里", "zài nǎlǐ", "อยู่ไหน", "yu nai"),
      row("nhìn thấy", "see (got it)", "看到了", "kàndào le", "เห็นแล้ว", "hen laeo"),
      row("bận", "busy", "忙", "máng", "ไม่ว่าง", "mai wang"),
      row("rảnh", "free", "有空", "yǒu kòng", "ว่าง", "wang"),
      row("nhắc", "to remind", "提醒", "tíxǐng", "เตือน", "tuean"),
      row("xong chưa", "done yet?", "好了吗", "hǎo le ma", "เสร็จหรือยัง", "set rue yang"),
    ],
    sentences: [
      row("Xin lỗi mình trễ.", "Sorry I am late.", "抱歉我迟到了。", "bàoqiàn wǒ chídào le.", "ขอโทษที่สาย", "kho-thot thee sai"),
      row("Hẹn bảy giờ được không?", "Is seven okay?", "七点可以吗？", "qī diǎn kěyǐ ma?", "นัดเจ็ดโมงได้ไหม", "nat jet mong dai mai"),
      row("Mình gửi vị trí.", "I will send the pin.", "我发定位。", "wǒ fā dìngwèi.", "ฉันส่งพิกัด", "chan song phi-kat"),
      row("Bạn ở đâu?", "Where are you?", "你在哪里？", "nǐ zài nǎlǐ?", "คุณอยู่ไหน", "khun yu nai"),
      row("Mình đến rồi.", "I have arrived.", "我到了。", "wǒ dào le.", "ฉันถึงแล้ว", "chan thueng laeo"),
      row("Mai rảnh không?", "Are you free tomorrow?", "明天有空吗？", "míngtiān yǒu kòng ma?", "พรุ่งนี้ว่างไหม", "phrung-nee wang mai"),
      row("Mình bận một chút.", "I am a bit busy.", "我有点忙。", "wǒ yǒudiǎn máng.", "ฉันไม่ว่างนิดหน่อย", "chan mai wang nit-noi"),
      row("Nhìn thấy rồi.", "Got it.", "看到了。", "kàndào le.", "เห็นแล้ว", "hen laeo"),
      row("Nhắc mình với.", "Remind me, please.", "提醒我一下。", "tíxǐng wǒ yíxià.", "ช่วยเตือนฉันหน่อย", "chuai tuean chan noi"),
      row("Xong chưa?", "Done yet?", "好了吗？", "hǎo le ma?", "เสร็จหรือยัง", "set rue yang"),
      row("Mạng yếu.", "The network is weak.", "网不好。", "wǎng bù hǎo.", "เน็ตไม่ดี", "net mai dee"),
      row("Gọi mình khi đến.", "Call me when you arrive.", "到了给我打电话。", "dào le gěi wǒ dǎ diànhuà.", "ถึงแล้วโทรหาฉัน", "thueng laeo tho ha chan"),
    ],
  },
];
