import { unit } from "./learn-bank-a.mjs";

/** More everyday-life domains — not one industry. */

export const UNITS_E = [
  unit(
    "appearance",
    "A1",
    ["Ngoại hình", "Appearance", "外貌", "wàimào", "รูปร่างหน้าตา", "rup-rang na-ta"],
    ["Tả tóc, cao thấp, và người đang mặc gì.", "Describe hair, height, and what someone is wearing.", "说头发、高矮、以及穿着。", "", "บรรยายผม ส่วนสูง และว่าใครใส่อะไร", ""],
    [
      ["tóc", "hair", "头发", "tóufa", "ผม", "phom"],
      ["cao", "tall", "高", "gāo", "สูง", "sung"],
      ["thấp", "short (height)", "矮", "ǎi", "เตี้ย", "tia"],
      ["gầy", "thin", "瘦", "shòu", "ผอม", "phom"],
      ["mập", "overweight", "胖", "pàng", "อ้วน", "uan"],
      ["trẻ", "young", "年轻", "niánqīng", "สาว / หนุ่ม", "sao / num"],
      ["già", "old", "老", "lǎo", "แก่", "kae"],
      ["mắt kính", "glasses", "眼镜", "yǎnjìng", "แว่น", "waen"],
      ["râu", "beard", "胡子", "húzi", "เครา", "khrao"],
      ["xinh", "pretty", "好看", "hǎokàn", "สวย", "suai"],
      ["đẹp trai", "handsome", "帅", "shuài", "หล่อ", "lo"],
      ["ngắn", "short (hair/length)", "短", "duǎn", "สั้น", "san"],
      ["dài", "long", "长", "cháng", "ยาว", "yao"],
      ["uốn", "curly", "卷", "juǎn", "ดัด", "dat"],
      ["thẳng", "straight (hair)", "直", "zhí", "ตรง", "trong"],
      ["da", "skin", "皮肤", "pífū", "ผิว", "phiu"],
      ["giống", "to look like", "像", "xiàng", "เหมือน", "muean"],
      ["khác", "different", "不一样", "bù yíyàng", "ต่าง", "tang"],
      ["nhìn", "to look", "看", "kàn", "ดู", "du"],
      ["áo xanh", "blue shirt", "蓝衣服", "lán yīfu", "เสื้อน้ำเงิน", "suea nam-ngoen"],
    ],
    [
      ["Tóc cô ấy dài.", "Her hair is long.", "她头发很长。", "tā tóufa hěn cháng.", "ผมเธอยาว", "phom thoe yao"],
      ["Anh ấy cao.", "He is tall.", "他很高。", "tā hěn gāo.", "เขาสูง", "khao sung"],
      ["Người kia đeo kính.", "That person wears glasses.", "那个人戴眼镜。", "nàge rén dài yǎnjìng.", "คนนั้นใส่แว่น", "khon nan sai waen"],
      ["Mình thấp hơn bạn.", "I am shorter than you.", "我比你矮。", "wǒ bǐ nǐ ǎi.", "ฉันเตี้ยกว่าคุณ", "chan tia kwa khun"],
      ["Áo xanh kia là anh ấy.", "The one in the blue shirt is him.", "穿蓝衣服的是他。", "chuān lán yīfu de shì tā.", "คนเสื้อน้ำเงินคือเขา", "khon suea nam-ngoen khue khao"],
      ["Trông cô ấy trẻ.", "She looks young.", "她看起来很年轻。", "tā kàn qǐlái hěn niánqīng.", "เธอดูยังสาว", "thoe du yang sao"],
      ["Tóc mình thẳng.", "My hair is straight.", "我的头发是直的。", "wǒ de tóufa shì zhí de.", "ผมฉันตรง", "phom chan trong"],
      ["Không giống ảnh.", "It does not look like the photo.", "跟照片不像。", "gēn zhàopiàn bú xiàng.", "ไม่เหมือนรูป", "mai muean rup"],
      ["Anh ấy có râu.", "He has a beard.", "他有胡子。", "tā yǒu húzi.", "เขามีเครา", "khao mee khrao"],
      ["Nhìn kĩ giúp mình.", "Please look carefully.", "请看仔细。", "qǐng kàn zǐxì.", "ช่วยดูให้ดี", "chuai du hai dee"],
      ["Hai người khác nhau.", "The two people look different.", "两个人不一样。", "liǎng gè rén bù yíyàng.", "สองคนต่างกัน", "song khon tang kan"],
      ["Bạn xinh quá.", "You look lovely.", "你很好看。", "nǐ hěn hǎokàn.", "คุณสวยจัง", "khun suai jang"],
    ],
  ),
  unit(
    "forms",
    "A2",
    ["Giấy tờ và form", "Forms and papers", "表格证件", "biǎogé zhèngjiàn", "แบบฟอร์มและเอกสาร", "baep-fom lae ek-ka-san"],
    ["Điền tên, ngày sinh, địa chỉ, số giấy tờ.", "Fill in name, date of birth, address, ID number.", "填姓名、生日、地址、证件号。", "", "กรอกชื่อ วันเกิด ที่อยู่ เลขเอกสาร", ""],
    [
      ["họ tên", "full name", "姓名", "xìngmíng", "ชื่อ-นามสกุล", "chue nam-sa-kun"],
      ["ngày sinh", "date of birth", "生日", "shēngrì", "วันเกิด", "wan koet"],
      ["địa chỉ", "address", "地址", "dìzhǐ", "ที่อยู่", "thee-yu"],
      ["quốc tịch", "nationality", "国籍", "guójí", "สัญชาติ", "san-chat"],
      ["giấy tờ", "ID / papers", "证件", "zhèngjiàn", "เอกสาร", "ek-ka-san"],
      ["hộ chiếu", "passport", "护照", "hùzhào", "พาสปอร์ต", "phat-sa-pot"],
      ["chữ ký", "signature", "签名", "qiānmíng", "ลายเซ็น", "lai-sen"],
      ["điền", "to fill in", "填", "tián", "กรอก", "krok"],
      ["nam", "male", "男", "nán", "ชาย", "chai"],
      ["nữ", "female", "女", "nǚ", "หญิง", "ying"],
      ["độc thân", "single", "单身", "dānshēn", "โสด", "sot"],
      ["đã kết hôn", "married", "已婚", "yǐ hūn", "แต่งงานแล้ว", "taeng-ngan laeo"],
      ["nghề", "occupation", "职业", "zhíyè", "อาชีพ", "a-cheep"],
      ["số", "number", "号码", "hàomǎ", "หมายเลข", "mai-lek"],
      ["bắt buộc", "required", "必填", "bì tián", "จำเป็น", "jam-pen"],
      ["tùy chọn", "optional", "选填", "xuǎn tián", "ไม่บังคับ", "mai bang-khap"],
      ["sai", "incorrect", "填错", "tián cuò", "กรอกผิด", "krok phit"],
      ["sửa", "to correct", "改", "gǎi", "แก้", "kae"],
      ["bản sao", "copy", "复印件", "fùyìnjiàn", "สำเนา", "sam-nao"],
      ["đóng dấu", "stamp", "盖章", "gàizhāng", "ประทับตรา", "pra-thap tra"],
    ],
    [
      ["Họ tên mình viết ở đây.", "I write my full name here.", "姓名写在这里。", "xìngmíng xiě zài zhèlǐ.", "ชื่อ-นามสกุลเขียนตรงนี้", "chue nam-sa-kun khian trong nee"],
      ["Ngày sinh là ngày mười.", "The date of birth is the tenth.", "生日是十号。", "shēngrì shì shí hào.", "วันเกิดคือวันที่สิบ", "wan koet khue wan thee sip"],
      ["Địa chỉ này sai.", "This address is wrong.", "这个地址填错了。", "zhège dìzhǐ tián cuò le.", "ที่อยู่นี้ผิด", "thee-yu nee phit"],
      ["Cần hộ chiếu không?", "Do you need a passport?", "需要护照吗？", "xūyào hùzhào ma?", "ต้องใช้พาสปอร์ตไหม", "tong chai phat-sa-pot mai"],
      ["Chỗ này bắt buộc.", "This field is required.", "这一栏必填。", "zhè yì lán bì tián.", "ช่องนี้จำเป็น", "chong nee jam-pen"],
      ["Mình ký ở đây được không?", "Can I sign here?", "可以在这里签名吗？", "kěyǐ zài zhèlǐ qiānmíng ma?", "เซ็นตรงนี้ได้ไหม", "sen trong nee dai mai"],
      ["Cho mình một bản sao.", "A copy, please.", "请给我复印件。", "qǐng gěi wǒ fùyìnjiàn.", "ขอสำเนาหนึ่งใบ", "kho sam-nao nueng bai"],
      ["Nghề mình điền là giáo viên.", "I put teacher as my job.", "职业我填老师。", "zhíyè wǒ tián lǎoshī.", "อาชีพฉันกรอกว่าครู", "a-cheep chan krok wa khru"],
      ["Sửa giúp mình dòng này.", "Please correct this line.", "请改这一行。", "qǐng gǎi zhè yì háng.", "ช่วยแก้บรรทัดนี้", "chuai kae ban-that nee"],
      ["Quốc tịch: Việt Nam.", "Nationality: Vietnamese.", "国籍：越南。", "guójí: Yuènán.", "สัญชาติ: เวียดนาม", "san-chat wiat-nam"],
      ["Mình độc thân.", "I am single.", "我单身。", "wǒ dānshēn.", "ฉันโสด", "chan sot"],
      ["Cần đóng dấu không?", "Do you need a stamp?", "要盖章吗？", "yào gàizhāng ma?", "ต้องประทับตราไหม", "tong pra-thap tra mai"],
    ],
  ),
  unit(
    "taxi",
    "A2",
    ["Taxi và xe ôm", "Taxi and rides", "出租车", "chūzūchē", "แท็กซี่", "thaek-si"],
    ["Gọi xe, nói điểm đến, xin đi meter, xuống xe.", "Call a car, say the destination, ask for the meter, get out.", "叫车、说目的地、打表、下车。", "", "เรียกรถ บอกที่หมาย ขอมิเตอร์ ลงรถ", ""],
    [
      ["taxi", "taxi", "出租车", "chūzūchē", "แท็กซี่", "thaek-si"],
      ["xe ôm", "motorbike taxi", "摩托", "mótuō", "วินมอไซค์", "win mo-sai"],
      ["tài xế", "driver", "司机", "sījī", "คนขับ", "khon khap"],
      ["đón", "to pick up", "接", "jiē", "รับ", "rap"],
      ["điểm đến", "destination", "目的地", "mùdìdì", "ที่หมาย", "thee-mai"],
      ["meter", "meter", "计价表", "jìjiàbiǎo", "มิเตอร์", "mi-toe"],
      ["ngã", "intersection", "路口", "lùkǒu", "แยก", "yaek"],
      ["kẹt", "stuck in traffic", "堵车", "dǔchē", "รถติด", "rot tit"],
      ["dừng", "to stop", "停", "tíng", "จอด", "jot"],
      ["xuống", "to get out", "下车", "xià chē", "ลง", "long"],
      ["lên", "to get in", "上车", "shàng chē", "ขึ้น", "khuen"],
      ["app", "app", "软件", "ruǎnjiàn", "แอป", "aep"],
      ["biển số", "plate number", "车牌", "chēpái", "ทะเบียน", "tha-bian"],
      ["cửa", "door", "门", "mén", "ประตู", "pra-tu"],
      ["thắt dây", "seatbelt", "安全带", "ānquándài", "เข็มขัดนิรภัย", "khem-khat ni-ra-phai"],
      ["nhanh", "hurry", "快点", "kuài diǎn", "เร็ว", "reo"],
      ["chậm", "slow down", "慢点", "màn diǎn", "ช้าลง", "cha long"],
      ["rẽ", "to turn", "转", "zhuǎn", "เลี้ยว", "liao"],
      ["phụ phí", "surcharge", "加价", "jiājià", "ค่าเพิ่ม", "kha phoem"],
      ["tiền mặt", "cash", "现金", "xiànjīn", "เงินสด", "ngoen sot"],
    ],
    [
      ["Đón mình ở cổng.", "Pick me up at the gate.", "在门口接我。", "zài ménkǒu jiē wǒ.", "มารับฉันที่ประตู", "ma rap chan thee pra-tu"],
      ["Đi trung tâm, làm ơn.", "To the centre, please.", "去市中心。", "qù shì zhōngxīn.", "ไปใจกลางเมือง", "pai jai-klang mueang"],
      ["Bật meter giúp mình.", "Please put the meter on.", "请打表。", "qǐng dǎ biǎo.", "เปิดมิเตอร์ให้หน่อย", "poet mi-toe hai noi"],
      ["Dừng ở ngã tư.", "Stop at the intersection.", "在路口停。", "zài lùkǒu tíng.", "จอดที่แยก", "jot thee yaek"],
      ["Đường kẹt quá.", "The traffic is bad.", "太堵了。", "tài dǔ le.", "รถติดมาก", "rot tit mak"],
      ["Chậm thôi.", "Slow down, please.", "慢一点。", "màn yìdiǎn.", "ช้าลงหน่อย", "cha long noi"],
      ["Mình xuống đây.", "I'll get out here.", "我在这里下车。", "wǒ zài zhèlǐ xià chē.", "ฉันลงตรงนี้", "chan long trong nee"],
      ["Biển số đúng không?", "Is this the plate number?", "车牌对吗？", "chēpái duì ma?", "ทะเบียนถูกไหม", "tha-bian thuk mai"],
      ["Thắt dây vào.", "Put the seatbelt on.", "系好安全带。", "jì hǎo ānquándài.", "คาดเข็มขัด", "khat khem-khat"],
      ["Có phụ phí không?", "Is there a surcharge?", "要加价吗？", "yào jiājià ma?", "มีค่าเพิ่มไหม", "mee kha phoem mai"],
      ["Mình đặt bằng app.", "I booked it in the app.", "我用软件叫的。", "wǒ yòng ruǎnjiàn jiào de.", "ฉันเรียกจากแอป", "chan riak jak aep"],
      ["Rẽ phải sau đèn đỏ.", "Turn right after the lights.", "红灯后右转。", "hóngdēng hòu yòu zhuǎn.", "เลี้ยวขวาหลังไฟแดง", "liao khwa lang fai daeng"],
    ],
  ),
  unit(
    "airport",
    "B1",
    ["Sân bay", "Airport", "机场", "jīchǎng", "สนามบิน", "sa-nam-bin"],
    ["Check-in, hành lý, cửa bay, hộ chiếu, chậm chuyến.", "Check in, luggage, gate, passport, a delay.", "值机、行李、登机口、护照、晚点。", "", "เช็กอิน กระเป๋า ประตูขึ้นเครื่อง พาสปอร์ต ไฟลต์ดีเลย์", ""],
    [
      ["sân bay", "airport", "机场", "jīchǎng", "สนามบิน", "sa-nam-bin"],
      ["chuyến bay", "flight", "航班", "hángbān", "ไฟลต์", "fai"],
      ["check-in", "check-in", "值机", "zhíjī", "เช็กอิน", "chek-in"],
      ["hành lý", "luggage", "行李", "xíngli", "กระเป๋า", "kra-pao"],
      ["xách tay", "hand luggage", "手提", "shǒutí", "กระเป๋าถือ", "kra-pao thue"],
      ["cửa bay", "gate", "登机口", "dēngjīkǒu", "เกต", "ket"],
      ["hộ chiếu", "passport", "护照", "hùzhào", "พาสปอร์ต", "phat-sa-pot"],
      ["thẻ lên máy bay", "boarding pass", "登机牌", "dēngjīpái", "บอร์ดิงพาส", "bo-ding phat"],
      ["an ninh", "security", "安检", "ānjiǎn", "จุดตรวจ", "jut truat"],
      ["hải quan", "customs", "海关", "hǎiguān", "ศุลกากร", "sun-la-ka-kon"],
      ["chậm", "delayed", "晚点", "wǎndiǎn", "ดีเลย์", "dee-le"],
      ["hủy chuyến", "cancelled", "取消", "qǔxiāo", "ยกเลิก", "yok-loek"],
      ["quá cảnh", "transit", "转机", "zhuǎnjī", "แวะต่อ", "wae tor"],
      ["ghế", "seat", "座位", "zuòwèi", "ที่นั่ง", "thee-nang"],
      ["cửa sổ", "window", "靠窗", "kào chuāng", "ริมหน้าต่าง", "rim na-tang"],
      ["lối đi", "aisle", "过道", "guòdào", "ทางเดิน", "thang doen"],
      ["nặng quá", "overweight", "超重", "chāozhòng", "เกินน้ำหนัก", "koen nam-nak"],
      ["lấy hành lý", "baggage claim", "取行李", "qǔ xíngli", "รับกระเป๋า", "rap kra-pao"],
      ["ga đến", "arrivals", "到达", "dàodá", "ขาเข้า", "kha khao"],
      ["ga đi", "departures", "出发", "chūfā", "ขาออก", "kha ok"],
    ],
    [
      ["Check-in ở đâu?", "Where is check-in?", "值机在哪里？", "zhíjī zài nǎlǐ?", "เช็กอินอยู่ไหน", "chek-in yu nai"],
      ["Hành lý xách tay được không?", "Is this okay as hand luggage?", "这个可以手提吗？", "zhège kěyǐ shǒutí ma?", "กระเป๋านี้ถือขึ้นได้ไหม", "kra-pao nee thue khuen dai mai"],
      ["Cửa bay bao nhiêu?", "What is the gate number?", "登机口是几号？", "dēngjīkǒu shì jǐ hào?", "เกตหมายเลขอะไร", "ket mai-lek a-rai"],
      ["Chuyến bay bị chậm.", "The flight is delayed.", "航班晚点了。", "hángbān wǎndiǎn le.", "ไฟลต์ดีเลย์", "fai dee-le"],
      ["Cho mình ghế cửa sổ.", "A window seat, please.", "请给我靠窗的座位。", "qǐng gěi wǒ kào chuāng de zuòwèi.", "ขอที่นั่งริมหน้าต่าง", "kho thee-nang rim na-tang"],
      ["Hộ chiếu đây.", "Here is my passport.", "这是护照。", "zhè shì hùzhào.", "นี่พาสปอร์ต", "nee phat-sa-pot"],
      ["Hành lý nặng quá.", "The luggage is overweight.", "行李超重了。", "xíngli chāozhòng le.", "กระเป๋าเกินน้ำหนัก", "kra-pao koen nam-nak"],
      ["Lấy hành lý ở băng nào?", "Which belt is baggage claim?", "取行李在几号转盘？", "qǔ xíngli zài jǐ hào zhuànpán?", "รับกระเป๋าสายพานไหน", "rap kra-pao sai-phan nai"],
      ["Mình quá cảnh ở đây.", "I am in transit here.", "我在这里转机。", "wǒ zài zhèlǐ zhuǎnjī.", "ฉันแวะต่อที่นี่", "chan wae tor thee nee"],
      ["An ninh ở bên phải.", "Security is on the right.", "安检在右边。", "ānjiǎn zài yòubiān.", "ตรวจอยู่ทางขวา", "truat yu thang khwa"],
      ["Chuyến bị hủy.", "The flight was cancelled.", "航班取消了。", "hángbān qǔxiāo le.", "ไฟลต์ถูกยกเลิก", "fai thuk yok-loek"],
      ["Ga đến tầng một.", "Arrivals are on floor one.", "到达在一楼。", "dàodá zài yì lóu.", "ขาเข้าอยู่ชั้นหนึ่ง", "kha khao yu chan nueng"],
    ],
  ),
  unit(
    "emergency",
    "B1",
    ["Khẩn cấp", "Emergencies", "紧急情况", "jǐnjí qíngkuàng", "เหตุฉุกเฉิน", "het chuk-chen"],
    ["Gọi giúp, nói chỗ, mất đồ, tai nạn nhỏ.", "Call for help, say the place, lost item, a small accident.", "求救、说地点、丢东西、小事故。", "", "เรียกช่วย บอกที่ ของหาย อุบัติเหตุเล็ก", ""],
    [
      ["cứu", "help (emergency)", "救命", "jiùmìng", "ช่วยด้วย", "chuai duai"],
      ["cảnh sát", "police", "警察", "jǐngchá", "ตำรวจ", "tam-ruat"],
      ["cấp cứu", "ambulance", "急救", "jíjiù", "รถพยาบาล", "rot pha-ya-ban"],
      ["cháy", "fire", "着火", "zháohuǒ", "ไฟไหม้", "fai mai"],
      ["mất", "lost / stolen", "丢了", "diū le", "หาย", "hai"],
      ["ví", "wallet", "钱包", "qiánbāo", "กระเป๋าสตางค์", "kra-pao sa-tang"],
      ["điện thoại", "phone", "手机", "shǒujī", "มือถือ", "mue-thue"],
      ["tai nạn", "accident", "事故", "shìgù", "อุบัติเหตุ", "u-bat-ti-het"],
      ["ngã", "to fall", "摔倒", "shuāidǎo", "ล้ม", "lom"],
      ["máu", "blood", "血", "xiě", "เลือด", "lueat"],
      ["gãy", "broken (bone)", "骨折", "gǔzhé", "หัก", "hak"],
      ["chỗ", "location", "地点", "dìdiǎn", "ที่", "thee"],
      ["ngay", "now / immediately", "马上", "mǎshàng", "ทันที", "than-thee"],
      ["an toàn", "safe", "安全", "ānquán", "ปลอดภัย", "plot phai"],
      ["đừng lại", "stay", "别走", "bié zǒu", "อย่าไป", "ya pai"],
      ["gọi", "to call", "打电话", "dǎ diànhuà", "โทร", "tho"],
      ["số khẩn", "emergency number", "急救电话", "jíjiù diànhuà", "เบอร์ฉุกเฉิน", "boe chuk-chen"],
      ["kẹt", "trapped", "出不去", "chū bú qù", "ติดอยู่", "tit yu"],
      ["trẻ lạc", "lost child", "走丢的孩子", "zǒu diū de háizi", "เด็กหลง", "dek long"],
      ["bình tĩnh", "stay calm", "冷静", "lěngjìng", "ใจเย็น", "jai-yen"],
    ],
    [
      ["Cứu với!", "Help!", "救命！", "jiùmìng!", "ช่วยด้วย", "chuai duai"],
      ["Gọi cảnh sát giúp mình.", "Please call the police.", "请帮我叫警察。", "qǐng bāng wǒ jiào jǐngchá.", "ช่วยโทรตำรวจให้หน่อย", "chuai tho tam-ruat hai noi"],
      ["Mình mất ví.", "I lost my wallet.", "我钱包丢了。", "wǒ qiánbāo diū le.", "ฉันกระเป๋าสตางค์หาย", "chan kra-pao sa-tang hai"],
      ["Có tai nạn ở ngã tư.", "There is an accident at the junction.", "路口有事故。", "lùkǒu yǒu shìgù.", "มีอุบัติเหตุที่แยก", "mee u-bat-ti-het thee yaek"],
      ["Người này ngã.", "This person has fallen.", "这个人摔倒了。", "zhège rén shuāidǎo le.", "คนนี้ล้ม", "khon nee lom"],
      ["Cần cấp cứu ngay.", "We need an ambulance now.", "马上要急救。", "mǎshàng yào jíjiù.", "ต้องได้รถพยาบาลทันที", "tong dai rot pha-ya-ban than-thee"],
      ["Chỗ này là trước siêu thị.", "This place is in front of the supermarket.", "就在超市前面。", "jiù zài chāoshì qiánmiàn.", "ที่นี่หน้าซูเปอร์", "thee nee na su-poe"],
      ["Bình tĩnh nào.", "Stay calm.", "冷静一点。", "lěngjìng yìdiǎn.", "ใจเย็นๆ", "jai-yen yen"],
      ["Trẻ lạc, giúp mình.", "A child is lost, please help.", "孩子走丢了，帮帮我。", "háizi zǒu diū le, bāng bāng wǒ.", "เด็กหลง ช่วยด้วย", "dek long chuai duai"],
      ["Đừng lại đây.", "Stay here.", "别走，待在这儿。", "bié zǒu, dāi zài zhèr.", "อย่าไป อยู่ตรงนี้", "ya pai yu trong nee"],
      ["Mình vẫn an toàn.", "I am still safe.", "我还安全。", "wǒ hái ānquán.", "ฉันยังปลอดภัย", "chan yang plot phai"],
      ["Số khẩn là bao nhiêu?", "What is the emergency number?", "急救电话是多少？", "jíjiù diànhuà shì duōshǎo?", "เบอร์ฉุกเฉินคืออะไร", "boe chuk-chen khue a-rai"],
    ],
  ),
  unit(
    "rent",
    "B1",
    ["Thuê nhà", "Renting", "租房", "zū fáng", "เช่าบ้าน", "chao ban"],
    ["Hỏi giá thuê, cọc, hóa đơn điện nước, hợp đồng.", "Ask rent, deposit, utility bills, the contract.", "问租金、押金、水电、合同。", "", "ถามค่าเช่า ค่ามัดจำ ค่าน้ำไฟ สัญญา", ""],
    [
      ["thuê", "to rent", "租", "zū", "เช่า", "chao"],
      ["giá thuê", "rent", "租金", "zūjīn", "ค่าเช่า", "kha chao"],
      ["cọc", "deposit", "押金", "yājīn", "มัดจำ", "mat-jam"],
      ["hợp đồng", "contract", "合同", "hétong", "สัญญา", "san-ya"],
      ["chủ nhà", "landlord", "房东", "fángdōng", "เจ้าของบ้าน", "jao khong ban"],
      ["phòng trống", "vacant room", "空房", "kōng fáng", "ห้องว่าง", "hong wang"],
      ["điện nước", "utilities", "水电", "shuǐdiàn", "ค่าน้ำค่าไฟ", "kha nam kha fai"],
      ["internet", "internet", "网费", "wǎng fèi", "เน็ต", "net"],
      ["nội thất", "furniture", "家具", "jiājù", "เฟอร์นิเจอร์", "foe-ni-choe"],
      ["không nội thất", "unfurnished", "空房无家具", "kōng fáng wú jiājù", "ไม่มีเฟอร์", "mai mee foe"],
      ["ở cùng", "to share", "合租", "hézū", "อยู่ด้วยกัน", "yu duai kan"],
      ["tháng", "per month", "每个月", "měi gè yuè", "ต่อเดือน", "tor duean"],
      ["ký", "to sign", "签", "qiān", "เซ็น", "sen"],
      ["xem nhà", "to view", "看房", "kàn fáng", "ดูบ้าน", "du ban"],
      ["ồn", "noisy", "吵", "chǎo", "เสียงดัง", "siang dang"],
      ["ẩm", "damp", "潮湿", "cháoshī", "ชื้น", "chuen"],
      ["sửa", "to repair", "修", "xiū", "ซ่อม", "som"],
      ["chuyển đi", "to move out", "搬走", "bān zǒu", "ย้ายออก", "yai ok"],
      ["gia hạn", "to renew", "续租", "xù zū", "ต่อสัญญา", "tor san-ya"],
      ["bao gồm", "included", "包括", "bāokuò", "รวม", "ruam"],
    ],
    [
      ["Phòng này thuê bao nhiêu một tháng?", "How much is the rent per month?", "这间一个月租金多少？", "zhè jiān yí gè yuè zūjīn duōshǎo?", "ห้องนี้เช่าเดือนละเท่าไหร่", "hong nee chao duean la thao-rai"],
      ["Cọc bao nhiêu?", "How much is the deposit?", "押金多少？", "yājīn duōshǎo?", "มัดจำเท่าไหร่", "mat-jam thao-rai"],
      ["Điện nước có gồm không?", "Are utilities included?", "水电包括吗？", "shuǐdiàn bāokuò ma?", "ค่าน้ำไฟรวมไหม", "kha nam fai ruam mai"],
      ["Mình muốn xem nhà chiều nay.", "I want to view it this afternoon.", "今天下午想看房。", "jīntiān xiàwǔ xiǎng kàn fáng.", "ฉันอยากดูบ้านบ่ายนี้", "chan yak du ban bai nee"],
      ["Có nội thất không?", "Is it furnished?", "有家具吗？", "yǒu jiājù ma?", "มีเฟอร์นิเจอร์ไหม", "mee foe-ni-choe mai"],
      ["Phòng hơi ẩm.", "The room is a bit damp.", "房间有点潮湿。", "fángjiān yǒudiǎn cháoshī.", "ห้องชื้นไปนิด", "hong chuen pai nit"],
      ["Ai sửa khi hỏng?", "Who repairs things when they break?", "坏了谁修？", "huài le shéi xiū?", "พังแล้วใครซ่อม", "phang laeo khrai som"],
      ["Mình ký hợp đồng được không?", "Can I sign the contract?", "可以签合同吗？", "kěyǐ qiān hétong ma?", "เซ็นสัญญาได้ไหม", "sen san-ya dai mai"],
      ["Ở cùng hai người.", "I would share with two people.", "和两个人合租。", "hé liǎng gè rén hézū.", "อยู่ด้วยกันสองคน", "yu duai kan song khon"],
      ["Muốn gia hạn thêm sáu tháng.", "I want to renew for six months.", "想续租六个月。", "xiǎng xù zū liù gè yuè.", "อยากต่อสัญญาอีกหกเดือน", "yak tor san-ya ik hok duean"],
      ["Tháng sau mình chuyển đi.", "I will move out next month.", "下个月搬走。", "xià gè yuè bān zǒu.", "เดือนหน้าฉันย้ายออก", "duean na chan yai ok"],
      ["Chủ nhà dễ nói chuyện.", "The landlord is easy to talk to.", "房东很好说话。", "fángdōng hěn hǎo shuōhuà.", "เจ้าของบ้านคุยง่าย", "jao khong ban khui ngai"],
    ],
  ),
  unit(
    "cinema",
    "A2",
    ["Phim và giải trí", "Cinema and going out", "电影和出门", "diànyǐng hé chūmén", "หนังและการออกไป", "nang lae kan ok pai"],
    ["Mua vé phim, chọn giờ, nói thể loại, hẹn đi chơi.", "Buy a ticket, pick a time, name a genre, arrange a night out.", "买票、选场次、说类型、约出门。", "", "ซื้อตั๋วหนัง เลือกเวลา บอกแนว นัดออกไป", ""],
    [
      ["phim", "film", "电影", "diànyǐng", "หนัง", "nang"],
      ["vé", "ticket", "票", "piào", "ตั๋ว", "tua"],
      ["suất", "showing", "场次", "chǎngcì", "รอบ", "rop"],
      ["hài", "comedy", "喜剧", "xǐjù", "ตลก", "ta-lok"],
      ["kinh dị", "horror", "恐怖", "kǒngbù", "สยอง", "sa-yong"],
      ["tình cảm", "romance", "爱情", "àiqíng", "โรแมนติก", "ro-maen-tik"],
      ["chỗ ngồi", "seat", "座位", "zuòwèi", "ที่นั่ง", "thee-nang"],
      ["bắp", "popcorn", "爆米花", "bàomǐhuā", "ป๊อปคอร์น", "pop-khon"],
      ["phụ đề", "subtitles", "字幕", "zìmù", "ซับไตเติ้ล", "sap-tai-toen"],
      ["lồng tiếng", "dubbed", "配音", "pèiyīn", "พากย์", "phak"],
      ["hay", "good (a film)", "好看", "hǎokàn", "สนุก", "sa-nuk"],
      ["dở", "bad / boring", "不好看", "bù hǎokàn", "น่าเบื่อ", "na buea"],
      ["hẹn", "to meet up", "约", "yuē", "นัด", "nat"],
      ["bar", "bar", "酒吧", "jiǔbā", "บาร์", "ba"],
      ["nhạc sống", "live music", "现场音乐", "xiànchǎng yīnyuè", "ดนตรีสด", "don-tri sot"],
      ["đông", "packed", "爆满", "bàomǎn", "คนเต็ม", "khon tem"],
      ["hết vé", "sold out", "售罄", "shòu qìng", "หมดตั๋ว", "mot tua"],
      ["trễ", "late", "迟到", "chídào", "สาย", "sai"],
      ["hàng ghế", "row", "排", "pái", "แถว", "thaeo"],
      ["im", "quiet / silent", "安静", "ānjìng", "เงียบ", "ngiap"],
    ],
    [
      ["Tối nay đi xem phim không?", "Shall we watch a film tonight?", "今晚看电影吗？", "jīn wǎn kàn diànyǐng ma?", "คืนนี้ไปดูหนังไหม", "khuen-nee pai du nang mai"],
      ["Suất chín giờ còn vé không?", "Are there tickets for the nine o'clock showing?", "九点那场还有票吗？", "jiǔ diǎn nà chǎng hái yǒu piào ma?", "รอบเก้าโมงยังมีตั๋วไหม", "rop kao mong yang mee tua mai"],
      ["Mình muốn phụ đề.", "I want subtitles.", "我要字幕。", "wǒ yào zìmù.", "ฉันเอาซับ", "chan ao sap"],
      ["Hết vé rồi.", "Sold out.", "售罄了。", "shòu qìng le.", "หมดตั๋วแล้ว", "mot tua laeo"],
      ["Phim này hài.", "This film is a comedy.", "这是喜剧。", "zhè shì xǐjù.", "หนังเรื่องนี้ตลก", "nang rueang nee ta-lok"],
      ["Ngồi hàng giữa.", "Sit in the middle row.", "坐中间那排。", "zuò zhōngjiān nà pái.", "นั่งแถวกลาง", "nang thaeo klang"],
      ["Cho mình bắp.", "Popcorn, please.", "请给我爆米花。", "qǐng gěi wǒ bàomǐhuā.", "ขอป๊อปคอร์น", "kho pop-khon"],
      ["Đừng nói trong phim.", "Don't talk during the film.", "看电影时别说话。", "kàn diànyǐng shí bié shuōhuà.", "อย่าพูดตอนหนัง", "ya phut ton nang"],
      ["Phim hơi dở.", "The film was a bit dull.", "电影有点不好看。", "diànyǐng yǒudiǎn bù hǎokàn.", "หนังน่าเบื่อไปนิด", "nang na buea pai nit"],
      ["Hay lắm.", "It was great.", "很好看。", "hěn hǎokàn.", "สนุกมาก", "sa-nuk mak"],
      ["Đi bar sau phim được không?", "Shall we go to a bar after the film?", "看完去酒吧吗？", "kàn wán qù jiǔbā ma?", "ดูจบไปบาร์ได้ไหม", "du jop pai ba dai mai"],
      ["Mình đến trễ năm phút.", "I will be five minutes late.", "我会晚五分钟。", "wǒ huì wǎn wǔ fēnzhōng.", "ฉันจะสายห้านาที", "chan ja sai ha na-thee"],
    ],
  ),
  unit(
    "seasons",
    "A1",
    ["Mùa và khí hậu", "Seasons and climate", "季节气候", "jìjié qìhòu", "ฤดูและอากาศ", "ri-du lae a-kat"],
    ["Nói bốn mùa, mưa nắng, và mặc gì theo mùa.", "Name seasons, rain and sun, and what to wear.", "说四季、晴雨，以及按季节穿什么。", "", "พูดสี่ฤดู ฝนแดด และว่าฤดูไหนใส่อะไร", ""],
    [
      ["mùa", "season", "季节", "jìjié", "ฤดู", "ri-du"],
      ["xuân", "spring", "春天", "chūntiān", "ฤดูใบไม้ผลิ", "ri-du bai-mai phon"],
      ["hạ", "summer", "夏天", "xiàtiān", "ฤดูร้อน", "ri-du ron"],
      ["thu", "autumn", "秋天", "qiūtiān", "ฤดูใบไม้ร่วง", "ri-du bai-mai ruang"],
      ["đông", "winter", "冬天", "dōngtiān", "ฤดูหนาว", "ri-du nao"],
      ["mưa", "rainy", "雨季", "yǔjì", "ฝน", "fon"],
      ["khô", "dry", "旱季", "hànjì", "แล้ง", "laeng"],
      ["nóng", "hot", "热", "rè", "ร้อน", "ron"],
      ["lạnh", "cold", "冷", "lěng", "หนาว", "nao"],
      ["ẩm", "humid", "潮湿", "cháoshī", "ชื้น", "chuen"],
      ["mát", "cool", "凉快", "liángkuai", "เย็น", "yen"],
      ["hoa", "flowers", "花", "huā", "ดอกไม้", "dok-mai"],
      ["lá", "leaves", "叶子", "yèzi", "ใบไม้", "bai-mai"],
      ["áo ấm", "warm coat", "外套", "wàitào", "เสื้อกันหนาว", "suea kan nao"],
      ["kem chống nắng", "sunscreen", "防晒", "fángshài", "ครีมกันแดด", "khrim kan daet"],
      ["ô", "umbrella", "伞", "sǎn", "ร่ม", "rom"],
      ["năm nay", "this year", "今年", "jīnnián", "ปีนี้", "pee nee"],
      ["thích", "to like", "喜欢", "xǐhuan", "ชอบ", "chop"],
      ["thay", "to change", "换", "huàn", "เปลี่ยน", "plian"],
      ["dễ chịu", "comfortable", "舒服", "shūfu", "สบาย", "sa-bai"],
    ],
    [
      ["Mùa hạ nóng.", "Summer is hot.", "夏天很热。", "xiàtiān hěn rè.", "ฤดูร้อนร้อน", "ri-du ron ron"],
      ["Mùa đông cần áo ấm.", "Winter needs a warm coat.", "冬天要穿外套。", "dōngtiān yào chuān wàitào.", "ฤดูหนาวต้องใส่เสื้อกันหนาว", "ri-du nao tong sai suea kan nao"],
      ["Mùa mưa mang ô.", "Bring an umbrella in the rainy season.", "雨季要带伞。", "yǔjì yào dài sǎn.", "ฤดูฝนพกร่ม", "ri-du fon phok rom"],
      ["Mình thích mùa xuân.", "I like spring.", "我喜欢春天。", "wǒ xǐhuan chūntiān.", "ฉันชอบฤดูใบไม้ผลิ", "chan chop ri-du bai-mai phon"],
      ["Năm nay ẩm hơn.", "This year is more humid.", "今年更潮湿。", "jīnnián gèng cháoshī.", "ปีนี้ชื้นกว่า", "pee nee chuen kwa"],
      ["Bôi kem chống nắng.", "Put on sunscreen.", "要擦防晒。", "yào cā fángshài.", "ทาครีมกันแดด", "tha khrim kan daet"],
      ["Lá đang thay màu.", "The leaves are changing.", "叶子在变色。", "yèzi zài biànsè.", "ใบไม้กำลังเปลี่ยนสี", "bai-mai kam-lang plian see"],
      ["Đêm đông lạnh.", "Winter nights are cold.", "冬天晚上冷。", "dōngtiān wǎnshang lěng.", "คืนฤดูหนาวหนาว", "khuen ri-du nao nao"],
      ["Mùa khô dễ chịu.", "The dry season is comfortable.", "旱季很舒服。", "hànjì hěn shūfu.", "ฤดูแล้งสบาย", "ri-du laeng sa-bai"],
      ["Hoa nở mùa xuân.", "Flowers open in spring.", "春天开花。", "chūntiān kāi huā.", "ดอกไม้บานฤดูใบไม้ผลิ", "dok-mai ban ri-du bai-mai phon"],
      ["Thu mát.", "Autumn is cool.", "秋天很凉快。", "qiūtiān hěn liángkuai.", "ฤดูใบไม้ร่วงเย็นสบาย", "ri-du bai-mai ruang yen sa-bai"],
      ["Khí hậu đang thay.", "The climate is changing.", "气候在变。", "qìhòu zài biàn.", "อากาศกำลังเปลี่ยน", "a-kat kam-lang plian"],
    ],
  ),
  unit(
    "lost",
    "A2",
    ["Mất đồ", "Lost and found", "寻物", "xún wù", "ของหาย", "khong hai"],
    ["Tả đồ mất, hỏi phòng thất lạc, để lại số điện thoại.", "Describe a lost item, ask at lost and found, leave a number.", "描述丢失物、问失物处、留电话。", "", "บรรยายของหาย ถามจุดรับของหาย ฝากเบอร์", ""],
    [
      ["mất", "lost", "丢了", "diū le", "หาย", "hai"],
      ["tìm", "to look for", "找", "zhǎo", "หา", "ha"],
      ["thấy", "to find", "找到", "zhǎodào", "เจอ", "joe"],
      ["ví", "wallet", "钱包", "qiánbāo", "กระเป๋าสตางค์", "kra-pao sa-tang"],
      ["chìa", "keys", "钥匙", "yàoshi", "กุญแจ", "kun-jae"],
      ["túi", "bag", "包", "bāo", "กระเป๋า", "kra-pao"],
      ["màu", "colour", "颜色", "yánsè", "สี", "see"],
      ["lúc", "when / at the time", "当时", "dāngshí", "ตอนนั้น", "ton nan"],
      ["ở đâu", "where", "在哪里", "zài nǎlǐ", "ที่ไหน", "thee nai"],
      ["phòng thất lạc", "lost and found", "失物处", "shīwù chù", "จุดรับของหาย", "jut rap khong hai"],
      ["để lại", "to leave (a number)", "留下", "liúxià", "ฝากไว้", "fak wai"],
      ["số", "number", "号码", "hàomǎ", "เบอร์", "boe"],
      ["bên trong", "inside", "里面", "lǐmiàn", "ข้างใน", "khang nai"],
      ["thẻ", "cards", "卡", "kǎ", "บัตร", "bat"],
      ["tiền", "cash", "现金", "xiànjīn", "เงินสด", "ngoen sot"],
      ["đen", "black", "黑", "hēi", "ดำ", "dam"],
      ["nhỏ", "small", "小", "xiǎo", "เล็ก", "lek"],
      ["lớn", "big", "大", "dà", "ใหญ่", "yai"],
      ["vừa thấy", "just now", "刚才", "gāngcái", "เมื่อกี้", "muea-ki"],
      ["giúp", "to help", "帮忙", "bāngmáng", "ช่วย", "chuai"],
    ],
    [
      ["Mình mất ví.", "I lost my wallet.", "我钱包丢了。", "wǒ qiánbāo diū le.", "ฉันกระเป๋าสตางค์หาย", "chan kra-pao sa-tang hai"],
      ["Phòng thất lạc ở đâu?", "Where is lost and found?", "失物处在哪里？", "shīwù chù zài nǎlǐ?", "จุดรับของหายอยู่ไหน", "jut rap khong hai yu nai"],
      ["Túi màu đen, nhỏ.", "A small black bag.", "一个黑色的小包。", "yí gè hēisè de xiǎo bāo.", "กระเป๋าสีดำใบเล็ก", "kra-pao see dam bai lek"],
      ["Bên trong có thẻ.", "There are cards inside.", "里面有卡。", "lǐmiàn yǒu kǎ.", "ข้างในมีบัตร", "khang nai mee bat"],
      ["Mất lúc ở quán.", "I lost it at the café.", "在店里丢的。", "zài diàn lǐ diū de.", "หายตอนอยู่ร้าน", "hai ton yu ran"],
      ["Vừa thấy cách đây mười phút.", "I saw it ten minutes ago.", "十分钟前还看到。", "shí fēnzhōng qián hái kàndào.", "เมื่อสิบนาทีก่อนยังเห็น", "muea sip na-thee kon yang hen"],
      ["Giúp mình tìm với.", "Please help me look.", "请帮我找。", "qǐng bāng wǒ zhǎo.", "ช่วยหาให้หน่อย", "chuai ha hai noi"],
      ["Mình để lại số này.", "I will leave this number.", "我留这个号码。", "wǒ liú zhège hàomǎ.", "ฉันฝากเบอร์นี้", "chan fak boe nee"],
      ["Có ai nhặt chìa không?", "Has anyone handed in keys?", "有人捡到钥匙吗？", "yǒu rén jiǎn dào yàoshi ma?", "มีคนเก็บกุญแจไหม", "mee khon kep kun-jae mai"],
      ["Thấy rồi, cảm ơn.", "Found it, thank you.", "找到了，谢谢。", "zhǎodào le, xièxie.", "เจอแล้ว ขอบคุณ", "joe laeo khop-khun"],
      ["Không có tiền nhiều.", "There was not much cash.", "现金不多。", "xiànjīn bù duō.", "เงินสดไม่มีเยอะ", "ngoen sot mai mee yoe"],
      ["Nếu thấy, gọi mình.", "If you find it, call me.", "找到就给我打电话。", "zhǎodào jiù gěi wǒ dǎ diànhuà.", "ถ้าเจอ โทรหาฉัน", "tha joe tho ha chan"],
    ],
  ),
];
