import { row } from "./learn-bank-a.mjs";

export const UNITS_B = [
  {
    id: "travel",
    level: "B1",
    title: row("Đi lại", "Getting around", "出行", "chūxíng", "การเดินทาง", "kan doen thang"),
    goal: row("Hỏi đường, mua vé, nói mình trễ.", "Ask the way, buy a ticket, say you are late.", "问路、买票、说自己晚了。", "", "ถามทาง ซื้อตั๋ว บอกว่าสาย", ""),
    vocab: [
      row("đường", "road", "路", "lù", "ถนน", "tha-non"),
      row("xe buýt", "bus", "公交车", "gōngjiāo chē", "รถเมล์", "rot-me"),
      row("tàu", "train", "火车", "huǒchē", "รถไฟ", "rot-fai"),
      row("vé", "ticket", "票", "piào", "ตั๋ว", "tua"),
      row("ga", "station", "车站", "chēzhàn", "สถานี", "sa-tha-nee"),
      row("sân bay", "airport", "机场", "jīchǎng", "สนามบิน", "sa-nam-bin"),
      row("trái", "left", "左", "zuǒ", "ซ้าย", "sai"),
      row("phải", "right", "右", "yòu", "ขวา", "khwa"),
      row("thẳng", "straight", "直走", "zhí zǒu", "ตรงไป", "trong pai"),
      row("gần", "near", "近", "jìn", "ใกล้", "klai"),
      row("xa", "far", "远", "yuǎn", "ไกล", "klai"),
      row("bản đồ", "map", "地图", "dìtú", "แผนที่", "phaen-thee"),
      row("lạc", "lost", "迷路", "mílù", "หลงทาง", "long thang"),
      row("trễ", "delayed", "晚点", "wǎndiǎn", "ดีเลย์", "dee-le"),
      row("chỗ ngồi", "seat", "座位", "zuòwèi", "ที่นั่ง", "thee-nang"),
      row("lên xe", "get on", "上车", "shàng chē", "ขึ้นรถ", "khuen rot"),
      row("xuống xe", "get off", "下车", "xià chē", "ลงรถ", "long rot"),
      row("bao lâu", "how long", "多久", "duō jiǔ", "นานแค่ไหน", "nan khae nai"),
      row("đến nơi", "arrive", "到达", "dàodá", "ถึงที่", "thueng thee"),
      row("đi bộ", "walk", "走路", "zǒulù", "เดิน", "doen"),
    ],
    sentences: [
      row("Nhà ga ở đâu?", "Where is the station?", "车站在哪里？", "chēzhàn zài nǎlǐ?", "สถานีอยู่ไหน", "sa-tha-nee yu nai"),
      row("Một vé đi trung tâm.", "One ticket to the centre.", "一张去市中心的票。", "yì zhāng qù shì zhōngxīn de piào.", "ตั๋วไปใจกลางเมืองหนึ่งใบ", "tua pai jai-klang mueang nueng bai"),
      row("Đi thẳng, rồi rẽ phải.", "Go straight, then turn right.", "直走，然后右转。", "zhí zǒu, ránhòu yòu zhuǎn.", "ตรงไป แล้วเลี้ยวขวา", "trong pai laeo liao khwa"),
      row("Còn xa không?", "Is it far?", "还远吗？", "hái yuǎn ma?", "ไกลไหม", "klai mai"),
      row("Mình lạc đường.", "I am lost.", "我迷路了。", "wǒ mílù le.", "ฉันหลงทาง", "chan long thang"),
      row("Xe buýt trễ mười phút.", "The bus is ten minutes late.", "公交车晚了十分钟。", "gōngjiāo chē wǎn le shí fēnzhōng.", "รถเมล์สายสิบนาที", "rot-me sai sip na-thee"),
      row("Xuống ở trạm sau.", "Get off at the next stop.", "下一站下车。", "xià yí zhàn xià chē.", "ลงป้ายต่อไป", "long pai tor pai"),
      row("Đi bộ năm phút.", "Five minutes on foot.", "走路五分钟。", "zǒulù wǔ fēnzhōng.", "เดินห้านาที", "doen ha na-thee"),
      row("Sân bay gần đây không?", "Is the airport nearby?", "机场离这儿近吗？", "jīchǎng lí zhèr jìn ma?", "สนามบินใกล้ที่นี่ไหม", "sa-nam-bin klai thee nee mai"),
      row("Bao lâu thì đến?", "How long does it take?", "要多久到？", "yào duō jiǔ dào?", "ถึงใช้เวลานานไหม", "thueng chai we-la nan mai"),
      row("Cho mình xem bản đồ.", "The map, please.", "请给我地图。", "qǐng gěi wǒ dìtú.", "ขอแผนที่หน่อย", "kho phaen-thee noi"),
      row("Mình đã đến nơi.", "I have arrived.", "我到了。", "wǒ dào le.", "ฉันถึงที่แล้ว", "chan thueng thee laeo"),
    ],
  },
  {
    id: "city",
    level: "B1",
    title: row("Trong thành phố", "In the city", "在城市里", "zài chéngshì lǐ", "ในเมือง", "nai mueang"),
    goal: row("Hỏi chỗ, ngân hàng, hiệu thuốc, nhà vệ sinh.", "Ask for places: bank, pharmacy, toilet.", "问地方：银行、药店、厕所。", "", "ถามที่ ธนาคาร ร้านยา ห้องน้ำ", ""),
    vocab: [
      row("thành phố", "city", "城市", "chéngshì", "เมือง", "mueang"),
      row("đường phố", "street", "街道", "jiēdào", "ถนน", "tha-non"),
      row("ngân hàng", "bank", "银行", "yínháng", "ธนาคาร", "tha-na-khan"),
      row("hiệu thuốc", "pharmacy", "药店", "yàodiàn", "ร้านยา", "ran ya"),
      row("bệnh viện", "hospital", "医院", "yīyuàn", "โรงพยาบาล", "rohng pha-ya-ban"),
      row("bưu điện", "post office", "邮局", "yóujú", "ไปรษณีย์", "prai-sa-nee"),
      row("nhà vệ sinh", "toilet", "厕所", "cèsuǒ", "ห้องน้ำ", "hong-nam"),
      row("công viên", "park", "公园", "gōngyuán", "สวน", "suan"),
      row("siêu thị", "supermarket", "超市", "chāoshì", "ซูเปอร์มาร์เก็ต", "su-poe-ma-ket"),
      row("tiền mặt", "cash", "现金", "xiànjīn", "เงินสด", "ngoen sot"),
      row("thẻ", "card", "卡", "kǎ", "บัตร", "bat"),
      row("mở cửa", "open", "开门", "kāi mén", "เปิด", "poet"),
      row("đóng cửa", "closed", "关门", "guān mén", "ปิด", "pit"),
      row("gần đây", "nearby", "附近", "fùjìn", "แถวนี้", "thaeo nee"),
      row("dãy số nhà", "address", "地址", "dìzhǐ", "ที่อยู่", "thee-yu"),
      row("giao thông", "traffic", "交通", "jiāotōng", "จราจร", "ja-ra-jon"),
      row("đông", "crowded", "挤", "jǐ", "คนเยอะ", "khon yoe"),
      row("yên", "quiet", "安静", "ānjìng", "เงียบ", "ngiap"),
      row("an toàn", "safe", "安全", "ānquán", "ปลอดภัย", "plot phai"),
      row("hỏi đường", "ask the way", "问路", "wèn lù", "ถามทาง", "tham thang"),
    ],
    sentences: [
      row("Nhà vệ sinh ở đâu?", "Where is the toilet?", "厕所在哪里？", "cèsuǒ zài nǎlǐ?", "ห้องน้ำอยู่ไหน", "hong-nam yu nai"),
      row("Gần đây có ngân hàng không?", "Is there a bank nearby?", "附近有银行吗？", "fùjìn yǒu yínháng ma?", "แถวนี้มีธนาคารไหม", "thaeo nee mee tha-na-khan mai"),
      row("Hiệu thuốc còn mở không?", "Is the pharmacy still open?", "药店还开着吗？", "yàodiàn hái kāi zhe ma?", "ร้านยายังเปิดอยู่ไหม", "ran ya yang poet yu mai"),
      row("Mình trả bằng thẻ.", "I'll pay by card.", "我用卡付。", "wǒ yòng kǎ fù.", "ฉันจ่ายด้วยบัตร", "chan jai duai bat"),
      row("Chỉ nhận tiền mặt.", "Cash only.", "只收现金。", "zhǐ shōu xiànjīn.", "รับเฉพาะเงินสด", "rap cha-pho ngoen sot"),
      row("Thành phố này đông.", "This city is crowded.", "这个城市很挤。", "zhège chéngshì hěn jǐ.", "เมืองนี้คนเยอะ", "mueang nee khon yoe"),
      row("Công viên yên.", "The park is quiet.", "公园很安静。", "gōngyuán hěn ānjìng.", "สวนเงียบ", "suan ngiap"),
      row("Địa chỉ này đúng không?", "Is this address right?", "这个地址对吗？", "zhège dìzhǐ duì ma?", "ที่อยู่นี้ถูกไหม", "thee-yu nee thuk mai"),
      row("Giao thông hôm nay chậm.", "Traffic is slow today.", "今天交通很慢。", "jīntiān jiāotōng hěn màn.", "จราจรวันนี้ช้า", "ja-ra-jon wan-nee cha"),
      row("Bệnh viện gần đây.", "The hospital is nearby.", "医院就在附近。", "yīyuàn jiù zài fùjìn.", "โรงพยาบาลอยู่ใกล้ๆ", "rohng pha-ya-ban yu klai klai"),
      row("Siêu thị đóng lúc mười giờ.", "The supermarket closes at ten.", "超市十点关门。", "chāoshì shí diǎn guānmén.", "ซูเปอร์มาร์เก็ตปิดสิบโมง", "su-poe-ma-ket pit sip mong"),
      row("Nơi này an toàn.", "This place is safe.", "这里很安全。", "zhèlǐ hěn ānquán.", "ที่นี่ปลอดภัย", "thee nee plot phai"),
    ],
  },
  {
    id: "body",
    level: "B1",
    title: row("Cơ thể và sức khỏe", "Body and health", "身体和健康", "shēntǐ hé jiànkāng", "ร่างกายและสุขภาพ", "rang-kai lae suk-kha-phap"),
    goal: row("Nói đau ở đâu, xin thuốc, hẹn bác sĩ.", "Say where it hurts, ask for medicine, see a doctor.", "说哪里疼、要药、看医生。", "", "บอกจุดที่เจ็บ ขอยา นัดหมอ", ""),
    vocab: [
      row("đầu", "head", "头", "tóu", "หัว", "hua"),
      row("bụng", "stomach", "肚子", "dùzi", "ท้อง", "thong"),
      row("tay", "hand", "手", "shǒu", "มือ", "mue"),
      row("chân", "foot / leg", "脚", "jiǎo", "เท้า", "thao"),
      row("mắt", "eye", "眼睛", "yǎnjing", "ตา", "ta"),
      row("đau", "hurt", "疼", "téng", "เจ็บ", "jep"),
      row("sốt", "fever", "发烧", "fāshāo", "ไข้", "khai"),
      row("ho", "cough", "咳嗽", "késou", "ไอ", "ai"),
      row("mệt", "tired", "累", "lèi", "เหนื่อย", "nueai"),
      row("thuốc", "medicine", "药", "yào", "ยา", "ya"),
      row("bác sĩ", "doctor", "医生", "yīshēng", "หมอ", "mo"),
      row("nước", "water", "水", "shuǐ", "น้ำ", "nam"),
      row("nghỉ", "rest", "休息", "xiūxi", "พัก", "phak"),
      row("dị ứng", "allergy", "过敏", "guòmǐn", "แพ้", "phae"),
      row("khẩn cấp", "emergency", "急诊", "jízhěn", "ฉุกเฉิน", "chuk-chen"),
      row("băng", "bandage", "绷带", "bēngdài", "ผ้าปิดแผล", "pha pit phlae"),
      row("lạnh", "cold (weather/body)", "冷", "lěng", "หนาว", "nao"),
      row("nóng", "hot", "热", "rè", "ร้อน", "ron"),
      row("khỏe", "healthy", "健康", "jiànkāng", "แข็งแรง", "khaeng-raeng"),
      row("uống thuốc", "take medicine", "吃药", "chī yào", "กินยา", "kin ya"),
    ],
    sentences: [
      row("Mình đau đầu.", "I have a headache.", "我头疼。", "wǒ tóu téng.", "ฉันปวดหัว", "chan puat hua"),
      row("Mình sốt.", "I have a fever.", "我发烧了。", "wǒ fāshāo le.", "ฉันมีไข้", "chan mee khai"),
      row("Cần gặp bác sĩ.", "I need a doctor.", "我需要看医生。", "wǒ xūyào kàn yīshēng.", "ฉันต้องพบหมอ", "chan tong phop mo"),
      row("Mình dị ứng thuốc này.", "I am allergic to this medicine.", "我对这个药过敏。", "wǒ duì zhège yào guòmǐn.", "ฉันแพ้ยานี้", "chan phae ya nee"),
      row("Uống thuốc sau ăn.", "Take the medicine after food.", "饭后吃药。", "fàn hòu chī yào.", "กินยาหลังอาหาร", "kin ya lang a-han"),
      row("Mình mệt, cần nghỉ.", "I am tired, I need rest.", "我累了，需要休息。", "wǒ lèi le, xūyào xiūxi.", "ฉันเหนื่อย ต้องพัก", "chan nueai tong phak"),
      row("Có hiệu thuốc gần đây không?", "Is there a pharmacy nearby?", "附近有药店吗？", "fùjìn yǒu yàodiàn ma?", "แถวนี้มีร้านยาไหม", "thaeo nee mee ran ya mai"),
      row("Đây là trường hợp khẩn cấp.", "This is an emergency.", "这是急诊。", "zhè shì jízhěn.", "นี่คือเหตุฉุกเฉิน", "nee khue het chuk-chen"),
      row("Uống nhiều nước.", "Drink a lot of water.", "多喝水。", "duō hē shuǐ.", "ดื่มน้ำเยอะๆ", "duem nam yoe yoe"),
      row("Chân mình đau.", "My foot hurts.", "我脚疼。", "wǒ jiǎo téng.", "เท้าฉันเจ็บ", "thao chan jep"),
      row("Mình bị ho.", "I have a cough.", "我咳嗽。", "wǒ késou.", "ฉันไอ", "chan ai"),
      row("Mình khỏe hơn rồi.", "I feel better now.", "我好多了。", "wǒ hǎo duō le.", "ฉันดีขึ้นแล้ว", "chan dee khuen laeo"),
    ],
  },
  {
    id: "study",
    level: "B1",
    title: row("Học tập", "Study", "学习", "xuéxí", "การเรียน", "kan rian"),
    goal: row("Nói về bài học 15 phút, hỏi nghĩa, xin nói chậm.", "Talk about a 15-minute lesson, ask meaning, ask to slow down.", "说十五分钟的课、问意思、请说慢。", "", "พูดถึงบท 15 นาที ถามความหมาย ขอพูดช้า", ""),
    vocab: [
      row("học", "to study", "学习", "xuéxí", "เรียน", "rian"),
      row("bài", "lesson", "课", "kè", "บทเรียน", "bot-rian"),
      row("từ", "word", "单词", "dāncí", "คำ", "kham"),
      row("câu", "sentence", "句子", "jùzi", "ประโยค", "pra-yok"),
      row("nghĩa", "meaning", "意思", "yìsi", "ความหมาย", "khwam-mai"),
      row("ví dụ", "example", "例子", "lìzi", "ตัวอย่าง", "tua-yang"),
      row("nghe", "listen", "听", "tīng", "ฟัง", "fang"),
      row("nói", "speak", "说", "shuō", "พูด", "phut"),
      row("đọc", "read", "读", "dú", "อ่าน", "an"),
      row("viết", "write", "写", "xiě", "เขียน", "khian"),
      row("nhớ", "remember", "记得", "jìde", "จำ", "jam"),
      row("quên", "forget", "忘记", "wàngjì", "ลืม", "luem"),
      row("lặp lại", "repeat", "重复", "chóngfù", "พูดซ้ำ", "phut sam"),
      row("chậm", "slow", "慢", "màn", "ช้า", "cha"),
      row("nhanh", "fast", "快", "kuài", "เร็ว", "reo"),
      row("đúng", "correct", "对", "duì", "ถูก", "thuk"),
      row("sai", "wrong", "错", "cuò", "ผิด", "phit"),
      row("hỏi", "ask", "问", "wèn", "ถาม", "tham"),
      row("hiểu", "understand", "懂", "dǒng", "เข้าใจ", "khao-jai"),
      row("phiên", "session", "时段", "shíduàn", "ช่วงเรียน", "chuang rian"),
    ],
    sentences: [
      row("Mình học 15 phút.", "I study for 15 minutes.", "我学习十五分钟。", "wǒ xuéxí shíwǔ fēnzhōng.", "ฉันเรียนสิบห้านาที", "chan rian sip-ha na-thee"),
      row("Từ này nghĩa là gì?", "What does this word mean?", "这个词是什么意思？", "zhège cí shì shénme yìsi?", "คำนี้แปลว่าอะไร", "kham nee plae wa a-rai"),
      row("Cho mình một ví dụ.", "Give me an example.", "给我一个例子。", "gěi wǒ yí gè lìzi.", "ขอตัวอย่างหน่อย", "kho tua-yang noi"),
      row("Làm ơn nói chậm.", "Please speak slowly.", "请说慢一点。", "qǐng shuō màn yìdiǎn.", "ได้โปรดพูดช้าๆ", "dai-prot phut cha-cha"),
      row("Mình chưa hiểu.", "I don't understand yet.", "我还没懂。", "wǒ hái méi dǒng.", "ฉันยังไม่เข้าใจ", "chan yang mai khao-jai"),
      row("Lặp lại giúp mình.", "Please repeat.", "请再重复一遍。", "qǐng zài chóngfù yí biàn.", "พูดซ้ำให้ที", "phut sam hai thee"),
      row("Câu này đúng không?", "Is this sentence correct?", "这句话对吗？", "zhè jù huà duì ma?", "ประโยคนี้ถูกไหม", "pra-yok nee thuk mai"),
      row("Mình quên từ này.", "I forgot this word.", "我忘了这个词。", "wǒ wàng le zhège cí.", "ฉันลืมคำนี้", "chan luem kham nee"),
      row("Nghe một lần nữa.", "Listen one more time.", "再听一遍。", "zài tīng yí biàn.", "ฟังอีกครั้ง", "fang ik khrang"),
      row("Phiên này đủ rồi.", "This session is enough.", "这个时段够了。", "zhège shíduàn gòu le.", "ช่วงนี้พอแล้ว", "chuang nee pho laeo"),
      row("Mai mình quay lại.", "I will come back tomorrow.", "我明天再来。", "wǒ míngtiān zài lái.", "พรุ่งนี้ฉันจะกลับมา", "phrung-nee chan ja klap ma"),
      row("Mình nhớ được hai câu.", "I can remember two sentences.", "我记得两句话。", "wǒ jìde liǎng jù huà.", "ฉันจำได้สองประโยค", "chan jam dai song pra-yok"),
    ],
  },
];

export const UNITS_EN_B2 = [
  {
    id: "opinion",
    level: "B2",
    title: row("Nêu ý kiến", "Giving opinions", "表达观点", "biǎodá guāndiǎn", "การให้ความเห็น", "kan hai khwam-hen"),
    goal: row(
      "Nêu ý, đồng ý, không đồng ý, và đưa một lý do ngắn.",
      "Give an opinion, agree, disagree, and add one short reason.",
      "提出看法、同意、不同意，并给一个短理由。",
      "",
      "ให้ความเห็น เห็นด้วย ไม่เห็นด้วย และให้เหตุผลสั้น",
      "",
    ),
    vocab: [
      row("ý kiến", "opinion", "看法", "kànfǎ", "ความเห็น", "khwam-hen"),
      row("tôi nghĩ", "I think", "我觉得", "wǒ juéde", "ฉันคิดว่า", "chan khit wa"),
      row("đồng ý", "agree", "同意", "tóngyì", "เห็นด้วย", "hen duai"),
      row("không đồng ý", "disagree", "不同意", "bù tóngyì", "ไม่เห็นด้วย", "mai hen duai"),
      row("lý do", "reason", "原因", "yuányīn", "เหตุผล", "het-phon"),
      row("ví dụ", "for example", "例如", "lìrú", "เช่น", "chen"),
      row("tuy nhiên", "however", "然而", "rán'ér", "อย่างไรก็ตาม", "yang-rai ko tam"),
      row("quan trọng", "important", "重要", "zhòngyào", "สำคัญ", "sam-khan"),
      row("có lợi", "beneficial", "有益", "yǒuyì", "เป็นประโยชน์", "pen pra-yot"),
      row("có hại", "harmful", "有害", "yǒuhài", "เป็นโทษ", "pen thot"),
      row("xu hướng", "trend", "趋势", "qūshì", "แนวโน้ม", "naeo-nom"),
      row("bằng chứng", "evidence", "证据", "zhèngjù", "หลักฐาน", "lak-than"),
      row("nhìn chung", "overall", "总体来说", "zǒngtǐ lái shuō", "โดยรวม", "doi ruam"),
      row("một mặt", "on the one hand", "一方面", "yì fāngmiàn", "ด้านหนึ่ง", "dan nueng"),
      row("mặt khác", "on the other hand", "另一方面", "lìng yì fāngmiàn", "อีกด้าน", "ik dan"),
      row("kết luận", "conclusion", "结论", "jiélùn", "ข้อสรุป", "kho sa-rup"),
      row("nên", "should", "应该", "yīnggāi", "ควร", "khuan"),
      row("có thể", "might", "可能", "kěnéng", "อาจ", "at"),
      row("rõ ràng", "clear", "清楚", "qīngchǔ", "ชัดเจน", "chat-jen"),
      row("phức tạp", "complex", "复杂", "fùzá", "ซับซ้อน", "sap-son"),
    ],
    sentences: [
      row("Tôi nghĩ 15 phút mỗi ngày tốt hơn một buổi dài.", "I think 15 minutes a day is better than one long session.", "我觉得每天十五分钟比一次学很久更好。", "wǒ juéde měi tiān shíwǔ fēnzhōng bǐ yí cì xué hěn jiǔ gèng hǎo.", "ฉันคิดว่าสิบห้านาทีต่อวันดีกว่าเรียนยาวครั้งเดียว", "chan khit wa sip-ha na-thee tor wan dee kwa rian yao khrang diao"),
      row("Tôi đồng ý, vì não cần thời gian sắp xếp.", "I agree, because the mind needs time to file things away.", "我同意，因为脑子需要时间整理。", "wǒ tóngyì, yīnwèi nǎozi xūyào shíjiān zhěnglǐ.", "ฉันเห็นด้วย เพราะสมองต้องมีเวลาจัดของ", "chan hen duai phor sa-mong tong mee we-la jat khong"),
      row("Tôi không hoàn toàn đồng ý.", "I do not completely agree.", "我不完全同意。", "wǒ bù wánquán tóngyì.", "ฉันไม่เห็นด้วยทั้งหมด", "chan mai hen duai thang mot"),
      row("Ví dụ, học từ theo tình huống thật.", "For example, learn words by real situations.", "例如，按真实情境学词。", "lìrú, àn zhēnshí qíngjìng xué cí.", "เช่น เรียนคำตามสถานการณ์จริง", "chen rian kham tam sa-than-ka-ran jing"),
      row("Tuy nhiên, một số người cần buổi học dài hơn.", "However, some people still need a longer class.", "然而，有些人仍需要更长的课。", "rán'ér, yǒuxiē rén réng xūyào gèng cháng de kè.", "อย่างไรก็ตาม บางคนยังต้องการคาบที่ยาวกว่า", "yang-rai ko tam bang khon yang tong kan khap thee yao kwa"),
      row("Nhìn chung, nhịp đều quan trọng hơn số phút.", "Overall, a steady rhythm matters more than the minutes.", "总体来说，稳定的节奏比分钟数更重要。", "zǒngtǐ lái shuō, wěndìng de jiézòu bǐ fēnzhōng shù gèng zhòngyào.", "โดยรวม จังหวะสม่ำเสมอสำคัญกว่าจำนวนนาที", "doi ruam jang-wa samam-samer sam-khan kwa jam-nuan na-thee"),
      row("Một mặt, thi giúp có mục tiêu.", "On the one hand, exams give a target.", "一方面，考试能给目标。", "yì fāngmiàn, kǎoshì néng gěi mùbiāo.", "ด้านหนึ่ง การสอบให้เป้าหมาย", "dan nueng kan sop hai pau-mai"),
      row("Mặt khác, thi có thể làm người ta học gấp.", "On the other hand, exams can make people rush.", "另一方面，考试可能让人学得很急。", "lìng yì fāngmiàn, kǎoshì kěnéng ràng rén xué de hěn jí.", "อีกด้าน การสอบอาจทำให้คนเรียนรีบ", "ik dan kan sop at tham hai khon rian rip"),
      row("Có bằng chứng từ thói quen hằng ngày.", "There is evidence from daily habits.", "日常习惯里就有证据。", "rìcháng xíguàn lǐ jiù yǒu zhèngjù.", "มีหลักฐานจากนิสัยประจำวัน", "mee lak-than jak ni-sai pra-jam wan"),
      row("Kết luận: học chậm, nhớ lâu.", "Conclusion: go slowly and keep it.", "结论：学得慢，记得久。", "jiélùn: xué de màn, jì de jiǔ.", "สรุป: เรียนช้า จำได้นาน", "sa-rup: rian cha jam dai nan"),
      row("Điều này khá phức tạp.", "This is rather complex.", "这件事比较复杂。", "zhè jiàn shì bǐjiào fùzá.", "เรื่องนี้ค่อนข้างซับซ้อน", "rueang nee khon kang sap-son"),
      row("Chúng ta nên nói rõ lý do.", "We should state the reason clearly.", "我们应该把理由说清楚。", "wǒmen yīnggāi bǎ lǐyóu shuō qīngchǔ.", "เราควรพูดเหตุผลให้ชัด", "rao khuan phut het-phon hai chat"),
    ],
  },
  {
    id: "work",
    level: "B2",
    title: row("Công việc", "Work", "工作", "gōngzuò", "งาน", "ngan"),
    goal: row("Nói lịch họp, deadline, xin hỗ trợ.", "Talk about meetings, deadlines, and asking for help.", "说会议、截止日期、请求帮助。", "", "พูดเรื่องประชุม เดดไลน์ และขอความช่วยเหลือ", ""),
    vocab: [
      row("công việc", "work", "工作", "gōngzuò", "งาน", "ngan"),
      row("họp", "meeting", "会议", "huìyì", "ประชุม", "pra-chum"),
      row("hạn", "deadline", "截止日期", "jiézhǐ rìqī", "กำหนดส่ง", "kam-not song"),
      row("dự án", "project", "项目", "xiàngmù", "โปรเจกต์", "pro-jek"),
      row("đồng nghiệp", "colleague", "同事", "tóngshì", "เพื่อนร่วมงาน", "phuean ruam ngan"),
      row("sếp", "manager", "经理", "jīnglǐ", "หัวหน้า", "hua-na"),
      row("email", "email", "邮件", "yóujiàn", "อีเมล", "i-men"),
      row("báo cáo", "report", "报告", "bàogào", "รายงาน", "rai-ngan"),
      row("kế hoạch", "plan", "计划", "jìhuà", "แผน", "phaen"),
      row("vấn đề", "issue", "问题", "wèntí", "ปัญหา", "pan-ha"),
      row("giải pháp", "solution", "办法", "bànfǎ", "ทางแก้", "thang kae"),
      row("bận", "busy", "忙", "máng", "ยุ่ง", "yung"),
      row("trễ hạn", "overdue", "过期", "guòqī", "เลยกำหนด", "loei kam-not"),
      row("cập nhật", "update", "更新", "gēngxīn", "อัปเดต", "ap-det"),
      row("hỗ trợ", "support", "支持", "zhīchí", "ช่วยเหลือ", "chuai-luea"),
      row("ưu tiên", "priority", "优先", "yōuxiān", "สิ่งสำคัญก่อน", "sing sam-khan kon"),
      row("lịch", "schedule", "日程", "rìchéng", "ตาราง", "ta-rang"),
      row("từ xa", "remote", "远程", "yuǎnchéng", "ทำงานจากที่อื่น", "tham-ngan jak thee uen"),
      row("văn phòng", "office", "办公室", "bàngōngshì", "สำนักงาน", "sam-nak-ngan"),
      row("xong việc", "done", "做完", "zuò wán", "งานเสร็จ", "ngan set"),
    ],
    sentences: [
      row("Cuộc họp lúc 9 giờ.", "The meeting is at nine.", "会议九点开始。", "huìyì jiǔ diǎn kāishǐ.", "ประชุมเก้าโมง", "pra-chum kao mong"),
      row("Hạn là thứ Sáu.", "The deadline is Friday.", "截止日期是周五。", "jiézhǐ rìqī shì zhōuwǔ.", "กำหนดส่งคือวันศุกร์", "kam-not song khue wan suk"),
      row("Mình cần hỗ trợ với báo cáo này.", "I need support with this report.", "这份报告我需要帮忙。", "zhè fèn bàogào wǒ xūyào bāngmáng.", "ฉันต้องการความช่วยเรื่องรายงานนี้", "chan tong kan khwam chuai rueang rai-ngan nee"),
      row("Bạn cập nhật giúp mình được không?", "Could you send me an update?", "你能给我一个更新吗？", "nǐ néng gěi wǒ yí gè gēngxīn ma?", "ช่วยอัปเดตให้หน่อยได้ไหม", "chuai ap-det hai noi dai mai"),
      row("Đây là ưu tiên hôm nay.", "This is today's priority.", "这是今天的优先事项。", "zhè shì jīntiān de yōuxiān shìxiàng.", "นี่คือสิ่งสำคัญของวันนี้", "nee khue sing sam-khan khong wan-nee"),
      row("Mình làm từ xa.", "I work remotely.", "我远程工作。", "wǒ yuǎnchéng gōngzuò.", "ฉันทำงานจากที่อื่น", "chan tham-ngan jak thee uen"),
      row("Đồng nghiệp đang bận.", "My colleague is busy.", "我的同事很忙。", "wǒ de tóngshì hěn máng.", "เพื่อนร่วมงานกำลังยุ่ง", "phuean ruam ngan kam-lang yung"),
      row("Dự án hơi trễ hạn.", "The project is a bit overdue.", "项目有点过期了。", "xiàngmù yǒudiǎn guòqī le.", "โปรเจกต์เลยกำหนดนิดหน่อย", "pro-jek loei kam-not nit noi"),
      row("Mình gửi email tóm tắt.", "I will send a short email.", "我会发一封简短的邮件。", "wǒ huì fā yì fēng jiǎnduǎn de yóujiàn.", "ฉันจะส่งอีเมลสรุปสั้นๆ", "chan ja song i-men sa-rup san-san"),
      row("Giải pháp đơn giản hơn.", "The solution is simpler.", "办法更简单。", "bànfǎ gèng jiǎndān.", "ทางแก้เรียบง่ายกว่า", "thang kae riap ngai kwa"),
      row("Lịch tuần này đầy.", "This week's schedule is full.", "这周日程排满了。", "zhè zhōu rìchéng pái mǎn le.", "ตารางสัปดาห์นี้เต็ม", "ta-rang sap-da nee tem"),
      row("Xong việc rồi.", "The work is done.", "做完了。", "zuò wán le.", "งานเสร็จแล้ว", "ngan set laeo"),
    ],
  },
  {
    id: "environment",
    level: "B2",
    title: row("Môi trường", "Environment", "环境", "huánjìng", "สิ่งแวดล้อม", "sing waet-lom"),
    goal: row("Nói về thành phố, rác, xe, và thói quen nhỏ.", "Talk about cities, waste, transport, and small habits.", "谈城市、垃圾、交通和小习惯。", "", "พูดเรื่องเมือง ขยะ การเดินทาง และนิสัยเล็กๆ", ""),
    vocab: [
      row("môi trường", "environment", "环境", "huánjìng", "สิ่งแวดล้อม", "sing waet-lom"),
      row("rác", "waste", "垃圾", "lājī", "ขยะ", "kha-ya"),
      row("tái chế", "recycle", "回收", "huíshōu", "รีไซเคิล", "ree-sai-khoen"),
      row("không khí", "air", "空气", "kōngqì", "อากาศ", "a-kat"),
      row("ô nhiễm", "pollution", "污染", "wūrǎn", "มลพิษ", "mon-la-phit"),
      row("xe", "vehicle", "车辆", "chēliàng", "ยานพาหนะ", "yan pha-ha-na"),
      row("xe đạp", "bicycle", "自行车", "zìxíngchē", "จักรยาน", "jak-kra-yan"),
      row("cây", "tree", "树", "shù", "ต้นไม้", "ton-mai"),
      row("năng lượng", "energy", "能源", "néngyuán", "พลังงาน", "phlang-ngan"),
      row("tiết kiệm", "save", "节约", "jiéyuē", "ประหยัด", "pra-yat"),
      row("nhựa", "plastic", "塑料", "sùliào", "พลาสติก", "phlat-satik"),
      row("túi", "bag", "袋子", "dàizi", "ถุง", "thung"),
      row("công cộng", "public", "公共", "gōnggòng", "สาธารณะ", "sa-tha-ra-na"),
      row("tương lai", "future", "未来", "wèilái", "อนาคต", "a-na-khot"),
      row("thói quen", "habit", "习惯", "xíguàn", "นิสัย", "ni-sai"),
      row("giảm", "reduce", "减少", "jiǎnshǎo", "ลด", "lot"),
      row("tăng", "increase", "增加", "zēngjiā", "เพิ่ม", "phoem"),
      row("chính sách", "policy", "政策", "zhèngcè", "นโยบาย", "na-yo-bai"),
      row("cộng đồng", "community", "社区", "shèqū", "ชุมชน", "chum-chon"),
      row("chịu trách nhiệm", "responsible", "负责", "fùzé", "รับผิดชอบ", "rap phit-chop"),
    ],
    sentences: [
      row("Không khí trong thành phố hôm nay kém.", "The air in the city is poor today.", "今天城里的空气不好。", "jīntiān chéng lǐ de kōngqì bù hǎo.", "อากาศในเมืองวันนี้ไม่ดี", "a-kat nai mueang wan-nee mai dee"),
      row("Chúng ta nên giảm túi nhựa.", "We should reduce plastic bags.", "我们应该减少塑料袋。", "wǒmen yīnggāi jiǎnshǎo sùliào dài.", "เราควรลดถุงพลาสติก", "rao khuan lot thung phlat-satik"),
      row("Đi xe đạp tốt cho sức khỏe và môi trường.", "Cycling is good for health and the environment.", "骑自行车对健康和环境都好。", "qí zìxíngchē duì jiànkāng hé huánjìng dōu hǎo.", "ขี่จักรยานดีต่อสุขภาพและสิ่งแวดล้อม", "khi jak-kra-yan dee tor suk-kha-phap lae sing waet-lom"),
      row("Tái chế là một thói quen nhỏ.", "Recycling is a small habit.", "回收是一个小习惯。", "huíshōu shì yí gè xiǎo xíguàn.", "รีไซเคิลคือนิสัยเล็กๆ", "ree-sai-khoen khue ni-sai lek-lek"),
      row("Năng lượng nên được tiết kiệm.", "Energy should be saved.", "能源应该节约。", "néngyuán yīnggāi jiéyuē.", "พลังงานควรถูกประหยัด", "phlang-ngan khuan thuk pra-yat"),
      row("Ô nhiễm ảnh hưởng đến trẻ em.", "Pollution affects children.", "污染会影响孩子。", "wūrǎn huì yǐngxiǎng háizi.", "มลพิษส่งผลต่อเด็ก", "mon-la-phit song phon tor dek"),
      row("Cộng đồng có thể trồng thêm cây.", "The community can plant more trees.", "社区可以多种树。", "shèqū kěyǐ duō zhòng shù.", "ชุมชนปลูกต้นไม้เพิ่มได้", "chum-chon pluk ton-mai phoem dai"),
      row("Chính sách cần rõ ràng.", "Policy needs to be clear.", "政策需要清楚。", "zhèngcè xūyào qīngchǔ.", "นโยบายต้องชัดเจน", "na-yo-bai tong chat-jen"),
      row("Tương lai phụ thuộc vào việc làm hôm nay.", "The future depends on what we do today.", "未来取决于我们今天做什么。", "wèilái qǔjué yú wǒmen jīntiān zuò shénme.", "อนาคตขึ้นกับสิ่งที่เราทำวันนี้", "a-na-khot khuen kap sing thee rao tham wan-nee"),
      row("Xe công cộng giảm kẹt xe.", "Public transport reduces traffic.", "公共交通能减少堵车。", "gōnggòng jiāotōng néng jiǎnshǎo dǔchē.", "ขนส่งสาธารณะช่วยลดรถติด", "khon-song sa-tha-ra-na chuai lot rot tit"),
      row("Mỗi người chịu trách nhiệm một phần.", "Each person is responsible for a part.", "每个人都有一份责任。", "měi gè rén dōu yǒu yí fèn zérèn.", "แต่ละคนรับผิดชอบส่วนหนึ่ง", "tae-la khon rap phit-chop suan nueng"),
      row("Giảm rác bắt đầu từ nhà.", "Reducing waste starts at home.", "减少垃圾从家里开始。", "jiǎnshǎo lājī cóng jiā lǐ kāishǐ.", "การลดขยะเริ่มที่บ้าน", "kan lot kha-ya roem thee ban"),
    ],
  },
  {
    id: "education",
    level: "B2",
    title: row("Giáo dục", "Education", "教育", "jiàoyù", "การศึกษา", "kan suek-sa"),
    goal: row("Nói về cách học, kỳ thi, và áp lực.", "Talk about study methods, exams, and pressure.", "谈学习方法、考试和压力。", "", "พูดเรื่องวิธีเรียน การสอบ และความกดดัน", ""),
    vocab: [
      row("giáo dục", "education", "教育", "jiàoyù", "การศึกษา", "kan suek-sa"),
      row("kỳ thi", "exam", "考试", "kǎoshì", "การสอบ", "kan sop"),
      row("áp lực", "pressure", "压力", "yālì", "ความกดดัน", "khwam kot-dan"),
      row("kỹ năng", "skill", "技能", "jìnéng", "ทักษะ", "thak-sa"),
      row("trí nhớ", "memory", "记忆", "jìyì", "ความจำ", "khwam-jam"),
      row("thói quen", "habit", "习惯", "xíguàn", "นิสัย", "ni-sai"),
      row("động lực", "motivation", "动力", "dònglì", "แรงจูงใจ", "raeng chung-jai"),
      row("thất bại", "failure", "失败", "shībài", "ความล้มเหลว", "khwam lom-laeo"),
      row("tiến bộ", "progress", "进步", "jìnbù", "ความก้าวหน้า", "khwam kao-na"),
      row("giáo viên", "teacher", "老师", "lǎoshī", "ครู", "khru"),
      row("học sinh", "student", "学生", "xuéshēng", "นักเรียน", "nak-rian"),
      row("tài liệu", "material", "材料", "cáiliào", "สื่อ", "sue"),
      row("luyện", "practice", "练习", "liànxí", "ฝึก", "fuek"),
      row("chấm", "to mark", "打分", "dǎ fēn", "ให้คะแนน", "hai kha-naen"),
      row("mục tiêu", "goal", "目标", "mùbiāo", "เป้าหมาย", "pau-mai"),
      row("tự học", "self-study", "自学", "zìxué", "เรียนด้วยตนเอง", "rian duai ton-eng"),
      row("lo lắng", "anxious", "焦虑", "jiāolǜ", "กังวล", "kang-won"),
      row("tự tin", "confident", "自信", "zìxìn", "มั่นใจ", "man-jai"),
      row("kết quả", "result", "结果", "jiéguǒ", "ผลลัพธ์", "phon-lap"),
      row("cân bằng", "balance", "平衡", "pínghéng", "สมดุล", "som-dun"),
    ],
    sentences: [
      row("Tự học 15 phút vẫn là học.", "Fifteen minutes of self-study still counts.", "自学十五分钟也是学习。", "zìxué shíwǔ fēnzhōng yě shì xuéxí.", "เรียนด้วยตนเองสิบห้านาทีก็คือการเรียน", "rian duai ton-eng sip-ha na-thee ko khue kan rian"),
      row("Kỳ thi tạo áp lực, nhưng không phải tất cả.", "Exams create pressure, but they are not everything.", "考试带来压力，但不是全部。", "kǎoshì dài lái yālì, dàn bú shì quánbù.", "การสอบสร้างความกดดัน แต่ไม่ใช่ทั้งหมด", "kan sop sang khwam kot-dan tae mai chai thang mot"),
      row("Trí nhớ cần nhịp đều, không cần nhồi.", "Memory needs a steady rhythm, not stuffing.", "记忆需要稳定的节奏，而不是硬塞。", "jìyì xūyào wěndìng de jiézòu, ér bú shì yìng sāi.", "ความจำต้องการจังหวะสม่ำเสมอ ไม่ใช่การยัด", "khwam-jam tong kan jang-wa samam-samer mai chai kan yat"),
      row("Thất bại một bài không phải thất bại cả lộ trình.", "Failing one lesson is not failing the path.", "一课失败不等于整条路失败。", "yí kè shībài bù děngyú zhěng tiáo lù shībài.", "พลาดหนึ่งบทไม่ได้แปลว่าทั้งเส้นทางพลาด", "phlat nueng bot mai dai plae wa thang sen-thang phlat"),
      row("Động lực đến từ câu mình nói được.", "Motivation comes from a sentence you can say.", "动力来自你能说出的一句话。", "dònglì lái zì nǐ néng shuō chū de yí jù huà.", "แรงจูงใจมาจากประโยคที่พูดได้", "raeng chung-jai ma jak pra-yok thee phut dai"),
      row("Học sinh cần cân bằng nghỉ và luyện.", "Students need a balance of rest and practice.", "学生需要休息和练习的平衡。", "xuéshēng xūyào xiūxi hé liànxí de pínghéng.", "นักเรียนต้องสมดุลระหว่างพักกับฝึก", "nak-rian tong som-dun ra-wang phak kap fuek"),
      row("Giáo viên giỏi làm bài nhỏ và rõ.", "A good teacher keeps lessons small and clear.", "好老师把课留小、留清楚。", "hǎo lǎoshī bǎ kè liú xiǎo, liú qīngchǔ.", "ครูที่ดีทำให้บทเล็กและชัด", "khru thee dee tham hai bot lek lae chat"),
      row("Kết quả đến chậm, và điều đó bình thường.", "Results come slowly, and that is normal.", "结果来得慢，这很正常。", "jiéguǒ lái de màn, zhè hěn zhèngcháng.", "ผลลัพธ์มาช้า และนั่นเป็นเรื่องปกติ", "phon-lap ma cha lae nan pen rueang pok-ka-ti"),
      row("Mình lo lắng trước khi nói.", "I feel anxious before I speak.", "开口前我会焦虑。", "kāikǒu qián wǒ huì jiāolǜ.", "ฉันกังวลก่อนจะพูด", "chan kang-won kon ja phut"),
      row("Tự tin đến sau vài câu đúng.", "Confidence comes after a few correct lines.", "自信来自几句说对的话。", "zìxìn lái zì jǐ jù shuō duì de huà.", "ความมั่นใจมาหลังพูดถูกไม่กี่ประโยค", "khwam man-jai ma lang phut thuk mai ki pra-yok"),
      row("Tài liệu hay không thay thói quen.", "Good materials do not replace the habit.", "好材料代替不了习惯。", "hǎo cáiliào dàitì bùliǎo xíguàn.", "สื่อดีทดแทนนิสัยไม่ได้", "sue dee thot-thaen ni-sai mai dai"),
      row("Mục tiêu tuần này: bốn phiên nhỏ.", "This week's goal: four small sessions.", "本周目标：四个小时段。", "běn zhōu mùbiāo: sì gè xiǎo shíduàn.", "เป้าหมายสัปดาห์นี้: สี่ช่วงสั้น", "pau-mai sap-da nee: si chuang san"),
    ],
  },
];
